// ⚠️ 자동 생성 아님 — 손으로 고쳐도 된다. 다만 **6개 언어 파일의 키 집합은 같아야 한다**.
//    (없는 키는 tr() 이 한국어로 폴백하고, 한국어에도 없으면 키 문자열이 그대로 화면에 뜬다.)
//
// 언어별로 파일을 쪼갠 이유 (2026-08-14):
//   예전엔 i18n.tsx 한 파일에 키 × 6개국어가 전부 있었다(490KB). 이 파일은 최상위 프로바이더라
//   **모든 화면이 무조건** 6개국어를 통째로 받아 파싱했고, 첫 진입 JS 의 절반 가까이가 이거였다.
//   지금은 한국어만 정적으로 싣고(기본 언어 + 폴백) 나머지는 그 언어를 고른 사람만 받는다.
//
// ⚠️ 이 파일을 다른 데서 직접 import 하지 말 것 — 조회는 i18n.tsx 의 tr()/useT() 하나로만.
const JA: Record<string, string> = {
  "common.home": "ホーム",
  "common.close": "閉じる",
  "common.cancel": "キャンセル",
  "common.ranking": "ランキング",
  "common.hub": "ハブ",
  "common.my_home": "My Home",
  "common.leveltest": "WORLD ARENA",
  "common.login_google": "Googleでログイン",
  // 로그인 수단이 여럿(구글·카카오)이라 특정 수단이 아니라 로그인 페이지로 보낼 때 쓰는 라벨
  "common.login": "ログイン",
  "common.logout": "ログアウト",
  "common.retry_test": "テストを再受験する",
  "common.loading": "読み込み中…",

  "fab.guest": "ゲスト",
  "fab.account": "マイアカウント",
  "fab.loggedin": "ログイン中 · ティア保存",
  "fab.savehint": "ログインでティア保存",
  "fab.login_needed": "ログインが必要",
  "fab.brand": "GARA · WORLD ARENA",
  "fab.language": "言語",
  "fab.admin": "管理者ページ",
  "fab.edit_name": "名前を変更",
  "fab.save": "保存",
  "fab.change_avatar": "キャラ変更",
  "fab.upload_image": "画像をアップロード",
  "fab.upload_fail": "アップロード失敗",

  // 온보딩/지역 (ISO 3166-2:KR 17 시도)
  "region.KR-11": "ソウル特別市",
  "region.KR-26": "釜山広域市",
  "region.KR-27": "大邱広域市",
  "region.KR-28": "仁川広域市",
  "region.KR-29": "光州広域市",
  "region.KR-30": "大田広域市",
  "region.KR-31": "蔚山広域市",
  "region.KR-41": "京畿道",
  "region.KR-42": "江原特別自治道",
  "region.KR-43": "忠清北道",
  "region.KR-44": "忠清南道",
  "region.KR-45": "全北特別自治道",
  "region.KR-46": "全羅南道",
  "region.KR-47": "慶尚北道",
  "region.KR-48": "慶尚南道",
  "region.KR-49": "済州特別自治道",
  "region.KR-50": "世宗特別自治市",
  "onboarding.title": "どの地域から参加しますか？",
  // 지역 목록이 없는 나라용 제목 — 화면에 지역 칸이 없는데 "어느 지역에서" 라고 물으면 없는 걸 묻는 말이 된다.
  "onboarding.title_country": "どの国から参加しますか？",
  // 1단계(설명) — 왜 지역을 받는지. 짧게, 크게.
  "onboarding.intro_title": "地域ごとに順位を競います",
  "onboarding.intro_body": "同じ地域・国の人たちと順位がつきます。",
  "onboarding.intro_next": "始める",
  "onboarding.country": "国",
  "onboarding.region": "地域",
  // 연령대 — 밴드만(정확한 나이는 안 받는다). '공개 안 함' 도 하나의 답으로 저장한다.
  "onboarding.age": "年代",
  // 지역을 이미 확정한 회원이 연령대만 받으러 들어왔을 때의 제목(지역 질문이 없는 화면)
  "onboarding.age_title": "年代を教えてください",
  "onboarding.age_hint": "統計にのみ使います。正確な年齢は伺いません。",
  "onboarding.age_10s": "10代以下",
  "onboarding.age_20s": "20代",
  "onboarding.age_30s": "30代",
  "onboarding.age_40s": "40代",
  "onboarding.age_50s": "50代",
  "onboarding.age_60s": "60代以上",
  "onboarding.age_private": "回答しない",
  // ⚠️ 2026-08-12: '영영 못 바꾼다' 가 아니다 — 마이페이지에서 딱 한 번 바꿀 수 있다. 문구가 규칙보다
  //    무섭게 남아 있으면 사용자가 이 화면에서 얼어붙는다(실제 규칙 = set-region 의 change 경로).
  "onboarding.lock_warn": "後でマイページから一度だけ変更できます。",
  "onboarding.start": "このまま始める",
  "onboarding.region_prefill_hint": "IPからの推定値です。確認・修正してください。",
  "mypage.region_locked": "地域・国は変更できません。誤割当ての場合はお問い合わせください。",
  // 국가·지역 1회 변경(2026-08-12). 닉네임 1회 변경과 같은 성격이라 문구 결도 맞춘다.
  "mypage.region_change_once": "国・地域を変更（1回）",
  "mypage.region_change_warn": "保存すると二度と変更できません。チャンスは一度だけです。",
  "mypage.region_change_used": "変更の機会はすでに使用済みです。",
  "mypage.region_none": "この国は地域を分けていません。",
  "mypage.profile_title": "基本情報",

  "landing.lead": "今すぐ自分の実力を確認しましょう。",
  "landing.cta": "CARISを受ける",
  // 레벨 추천(무료 진단 검색창) — /test/* 모듈용
  "reco.heading": "AIの使い方を一言で書いてみてください",
  "reco.placeholder": "あなたのAI活用力はどのくらい？",
  "reco.button": "レベルを提案",
  "reco.loading": "分析中…",
  // 홈 검색 라우터(route-query) — 의미 기반 페이지 이동
  // 뒤에 붙던 예시(WORLD ARENA·시험안내·문의…)는 뺐다 — 메인 검색창은 질문 한 줄만 둔다.
  "route.placeholder": "何をお探しですか？",
  "route.notfound": "正しくない検索語です。もう一度入力してください。",
  // CARIS ARENA 이식 잔여 키 (gara-cbt에 없던 7개)
  "rank.title": "ランキング",
  "report.btn": "🚩 誤りを報告",
  "report.placeholder": "この問題の誤字・誤りをお知らせください",
  "report.send": "送信",
  "report.cancel": "キャンセル",
  "report.sent": "✅ 報告を受け付けました。ありがとうございます！",
  "report.fail": "送信失敗",
  "reco.result": "その内容なら Lv.{n} {name} がおすすめ",
  "reco.pct_range": "その内容なら世界で上位 {lo}〜{hi}% くらいです",
  "reco.result_alt": " · Lv.{n}に挑戦しても",
  "reco.error": "提案に失敗しました。少し後でお試しください。",
  "reco.start_lv": "Lv.{n}で始める",
  "reco.unclear": "うまく認識できませんでした。使い方を一文で書いてください。(例: 初心者です / 自動化も得意)",
  "nav.about": "グローバルAIロボット協会",
  "nav.privacy": "プライバシーポリシー",
  "nav.more": "詳しく見る",
  "nav.lecture": "講義",
  "nav.terms": "利用規約",
  "terms.title": "利用規約",
  "terms.todo": "準備中です。",
  "withdraw.title": "退会",
  "withdraw.desc": "退会するとアカウントは無効化され、{d}日間の保管後に会員情報が破棄されます。それまでに再ログインして復元できます。",
  "withdraw.button": "退会する",
  "withdraw.confirm": "本当に退会しますか？ アカウントは無効化され、{d}日後に会員情報が破棄されます。それまでに再ログインして復元できます。",
  "withdraw.done": "退会処理が完了しました。ご利用ありがとうございました。",
  "withdraw.failed": "エラーが発生しました。後ほど再度お試しください。",
  "withdraw.gate_title": "退会申請済みのアカウントです",
  "withdraw.gate_body": "このアカウントは退会申請されています。保管期間{d}日以内に復元すれば、ランク・記録・購入した教材がそのまま戻ります。復元しない場合は会員情報が破棄され、このアカウントには二度とログインできません。",
  "withdraw.gate_left": "復元できる期間はあと{n}日です",
  "withdraw.gate_purge_on": "{date}に破棄されます",
  "withdraw.gate_restore": "アカウントを復元する",
  "withdraw.gate_logout": "復元せずログアウト",
  "withdraw.restoring": "復元中…",
  "withdraw.restore_failed": "復元できませんでした。後ほど再度お試しください。",
  "lecture.title": "講義ページです",
  "lecture.sub": "講義コンテンツは準備中です。",

  "about.title": "グローバルAIロボット協会",
  "about.eyebrow": "Global AI & Robotics Association",
  "about.tag": "AI・ロボット時代、人類が変化に適応し成長できるよう支援する機関です。",
  "about.desc": "AIとロボット技術の融合における新たな標準を先導するグローバル協会です。",
  "about.note": "協会会員・会員企業の募集や活動情報など、詳細は順次公開予定です。",

  // 레벨선택 페이지 제목 — 아레나 지도(WORLD ARENA)와 겹치지 않게 런처 버튼과 같은 '레벨 테스트'로.
  "lv.title": "レベルテスト",
  "lv.rule_btn": "等級ルール",
  // 북두칠성 별자리(레벨 선택) 아래 한 줄 안내 — 인증서와 같은 별 순서라는 걸 알려준다
  "lv.dipper_hint": "星をタップしてレベルを選択 — 到達したレベルは金色に灯ります",
  // 닉네임 — 최초 1회 설정(/onboarding/nickname) + 마이페이지에서 1회 변경
  "nick.title": "ニックネームを決めてください",
  "nick.body": "ランキング・チャット・認証書に表示される名前です。Googleアカウントの実名の代わりに使う名前を決めてください。",
  "nick.label": "ニックネーム",
  "nick.placeholder": "2〜12文字",
  "nick.rule": "{min}〜{max}文字 · 文字と数字、アンダースコア(_)のみ · 空白と記号は使えません。",
  "nick.once_warn": "ニックネームは今後1回だけ変更できます。",
  "nick.confirm": "確定",
  "nick.saving": "保存中…",
  "nick.change_once": "変更（残り1回）",
  "nick.last_chance": "変更はこれが最後です。確定すると二度と変更できません。",
  "nick.used_up": "変更回数を使い切りました",
  "nick.err_length": "2〜12文字で入力してください。",
  "nick.err_shape": "文字・数字・アンダースコア(_)のみ使えます。",
  "nick.err_taken": "すでに使われているニックネームです。",
  "nick.err_reserved": "使用できないニックネームです。",
  "nick.err_locked": "変更回数を使い切りました。カスタマーセンターへお問い合わせください。",
  "nick.err_failed": "保存に失敗しました。しばらくしてからお試しください。",
  // 레벨테스트 인증서(/test/certificate) — 무료, 누르면 바로 발급
  "lcert.issue_btn": "認証書を発行",
  "lcert.print": "📄 PDFで保存 / 印刷",
  "lcert.no_name": "名前未設定",
  "lcert.empty": "まだ発行できる認証書がありません。レベルテストで1段階を突破すると旅の最初の星が灯ります。",
  "lcert.load_failed": "認証書を読み込めませんでした。しばらくしてからお試しください。",
  "lcert.go_test": "レベルテストへ",
  // 문항 수는 레벨 구간별(10/20/30)이고 제한시간(분)이 그 수와 같다. 승급은 개수가 아니라 정답률. 강등은 없다.
  "lv.rule_up": "Lv.1~4は{p1}%以上、Lv.5~7は{p2}%以上で昇級",
  "lv.rule_nodown": "点数が低くても等級は下がりません",
  "lv.rule_daily": "1日{n}回まで受験でき、昇級すると1回追加されます",
  // 레벨 선택(D안) — '지금 도전' 카드
  "lv.prev_level": "前のレベル",
  "lv.next_level": "次のレベル",
  "lv.start_now": "受験を開始 →",
  "lv.fact_q": "{n}問",
  "lv.fact_min": "{n}分",
  "lv.fact_cut": "{n}問正解で昇級",
  "lv.left_today": "本日残り{n}回 · 昇級すると1回追加",
  "lv.daily_limit": "本日の受験回数を使い切りました。明日また挑戦するか、昇級すると1回追加されます。",
  "lv.rule_note": "Lv.{max}は最高等級",
  "lv.login_to_save": "テスト結果を保存するにはログインが必要です",
  "lv.sub_tail": "選んだ難易度に合わせて出題 · ログインユーザーは{d}日に1回",
  "lv.rec_firsttime": "初めてならLv.3から気軽に",
  "lv.rec_for_user": "現在の実力ではLv.{c}がおすすめ",
  "lv.rec_challenge": " · Lv.{n}に挑戦しても",
  "lv.tag_rec": "おすすめ",
  "lv.tag_challenge": "挑戦",
  "lv.locked": "ロック",
  "lv.locked_hint": "昇格すると解除されます",

  "lv.select": "選択 →",
  "lv.preparing": "準備中…",
  // 문제은행이 아직 없는 레벨(COMING_SOON_LEVELS)의 카드 문구
  "lv.coming_soon": "公開予定",
  "lv.start_failed": "開始に失敗しました。",
  "lv.1.name": "入門 I",
  // Lv.1 = 3축(다른 레벨은 6축) — AI 프롬프트 활용 · AI 도구 이해 · AI를 활용한 문제해결
  "lv.1.desc": "AIツールの理解・プロンプト活用とAIを活用した問題解決の入門",
  "lv.2.name": "入門 II",
  "lv.2.desc": "ビジネス・日常プロンプト、プロンプト技法、AIツール活用と生産性・協働",
  "lv.3.name": "基礎",
  "lv.3.desc": "生成AIリテラシー・AI倫理、プロンプトエンジニアリング基礎",
  "lv.4.name": "中級",
  "lv.4.desc": "生成AI中級、PythonでAIとハードウェアをソフトウェア的に接続",
  "lv.5.name": "上級",
  "lv.5.desc": "生成AI上級(LLM・RAG・アプリ開発)、基礎ビジョンAI(物体認識)、C/C++基礎",
  "lv.6.name": "発展",
  "lv.6.desc": "STM32精密制御、ROS2システム統合、PLCプログラミング、工程シミュレーション",
  "lv.7.name": "マスター",
  "lv.7.desc": "デジタルツインと群ロボットを統合する最終マスター",

  "test.nodata": "進行中のテストが見つかりません。更新すると無効になります。",
  "test.restart": "もう一度始める",
  // 응시 화면(레벨테스트·CBT 공용) 키보드 단축키 안내. 마우스 있는 기기에서만 노출.
  //   hint_nav = 보기가 없는 주관식 문항용(숫자키 안 먹음).
  "kbd.hint": "1–{n}で選択・←→で移動",
  "kbd.hint_nav": "←→ で移動",
  // 응시 화면 상단 이탈 카운터. '전체화면 유지' 안내 문구는 뺐다 — 시작 전 경고 게이트에서 이미 말하고,
  // 응시 중 상단바는 숫자(문항·시간·이탈) 셋만 크게 보이는 게 목적.
  "test.guard": "離脱 {v}/3",
  "test.quit": "✕ 中断",
  "test.quit_confirm": "テストを中断しますか？\n回答は保存されず、今回の受験は無効になります。",
  "test.solved": "解答 {a}/{t}",

  // 시작 전 경고 게이트 (TestRunner)
  "intro.title": "開始前に必ずお読みください",
  "intro.meta": "Lv.{lv} · 全{q}問 · 制限時間{min}分",
  // 응시 전 경고 화면의 시험 정보 줄(규칙 목록과 같은 행 모양으로 위에 붙는다)
  "intro.fact_q": "全{q}問",
  "intro.fact_min": "制限時間{min}分",
  "intro.anticheat": "🛡️ 不正防止システム作動中 🛡️",
  "intro.fullscreen": "全画面モード必須",
  "intro.rule_exit": "タブ切替・ウィンドウ移動・全画面解除で警告発生",
  "intro.rule_void": "警告{m}回累積で自動的に無効処理",
  "intro.rule_block": "コピー・右クリック・ドラッグ機能を制限",
  "intro.start": "全画面で開始 →",
  "intro.cancel": "キャンセル",
  // 이동 한 쌍은 화살표를 같이 단다 — 한쪽만 달면 짝으로 안 읽힌다. 상단 키보드 안내(←→)와도 맞는다.
  "test.prev": "← 前へ",
  "test.next": "次へ →",
  "test.submit": "提出する",
  "test.submitting": "提出中…",
  "test.submit_confirm_unanswered": "未回答の問題が{n}問あります。\nそれでも提出しますか？",
  "test.submit_confirm": "解答を最終提出しますか？\n提出後は修正できません。",
  "test.submit_failed": "提出に失敗しました。",
  "void.title": "テストが無効になりました",
  "void.body": "画面離脱が3回累積し不正と判断されました。今回の受験は",
  "void.body_strong": "保存されずレーティングに反映されません。",
  "void.restart": "もう一度",
  "void.home": "ホームへ",
  "warn.left": "画面離脱を検知（{n}/{m}）。{r}",
  "warn.tab": "タブを切り替えました。",
  "warn.blur": "フォーカスが外れました。",
  "warn.fs": "全画面を解除しました。",

  "result.loading": "結果を読み込み中…",
  "result.notfound": "結果が見つかりません。",
  "result.load_failed": "結果の読み込みに失敗しました。",
  "result.level_result": "レベル{n}の結果",
  "result.accuracy": "正答率{p}%",
  // ⚠️ 여기 적는 건 **로그인하면 실제로 열리는 것**이어야 한다(= UnlockedPanel 이 그리는 것).
  //    옛 문구 '티어 · 6축 누적 분석 · 오답 해설' 은 없는 기능 두 개를 미끼로 걸고 있었다 —
  //    티어는 2026-08-04 제거, 오답노트는 결과창에서 제거됐다(Result.tsx 의 UnlockedPanel 끝 주석).
  //    UnlockedPanel 구성이 바뀌면 이 줄도 같이 고칠 것.
  "locked.title": "昇級判定 · 6軸分析 · 学習プラン",
  "locked.peek": "あと少し — ロック解除まで1秒",
  "locked.desc": "ログインすると累積レーティングに反映され、詳細が開きます。",
  "locked.blocked": "直近3日以内に受験履歴があるため連携されません。3日後の再受験で反映されます。",
  "locked.cta": "Googleでログインして分析を見る",
  "result.overall": "累積総合レーティング {o} / 100",
  "result.placing": " · 配置中",
  "result.promoted": "昇格！",
  // 승급했을 때만 뜨는 결과창 CTA — 누르면 다음 레벨 응시를 바로 시작한다(응시 전 경고 화면으로 이동).
  "result.next_level": "Lv.{n}に挑戦 →",
  "rank.cur_level": "現在の等級 · レベル{n}",
  "db.points": "ランキングスコア {p}",
  "db.skill_score": "実力スコア",
  "db.activity_score": "活動スコア",
  "db.season_total": "シーズン合計",
  // 랭킹 점수 = 레벨 + 맞힌 개수 (히어로 옆 인라인 분해). 수치는 scoring.ts 와 일치 — 규칙 바뀌면 같이 갱신.
  "db.score_break_h": "スコアの決まり方",
  "db.eq_level": "レベル",
  "db.eq_correct": "正解数",
  "db.eq_points": "スコア",
  "db.howto_up": "16問以上正解でレベルが上がると点数が大きく上昇",
  "db.howto_within": "同じレベルでは正解が多いほど少しずつ上昇",
  "result.radar_title": "領域別のテスト結果",
  "result.legend_thistest": "今回",
  "result.legend_prevtest": "前回(同レベル)",
  "result.legend_me": "あなた",
  "result.legend_avg": "ティア平均",
  "result.legend_prev": "前回",
  "result.delta_title": "今回の変動",
  "result.delta_legend": "▲上昇 / ▼下降",
  "result.answers_title": "解説 · 復習",
  // 결과창 하단 이북 추천 칸(eBook Store 로 연결)
  "result.books_title": "おすすめ E-BOOK",
  "result.books_more": "Learning Library",
  "result.books_read": "すぐ学習する",
  "result.correct": "正解",
  "result.wrong": "不正解",
  "result.mychoice": "（あなたの選択）",

  "rx.title": "テスト分析と次のステップ",
  "rx.promote": "{tier}まであと{p}点",
  "rx.master": "最高ティア達成！🎉",
  "rx.focus": "重点補強ポイント：[{axis}] 領域",
  "rx.focus_peer": "（平均より{gap}↓）",
  "rx.weak": "{axis}が{tier}平均より{gap}低い",
  "rx.next_up": "よくできました！Lv.{n} 挑戦に向けて Learning Library で学習しましょう。",
  "rx.next_same": "Lv.{n}をもう一度",
  "rx.next_down": "Lv.{n}で基礎固め",
  // 승급 못 했을 때(유지) 처방 둘째 줄 — 약점 영역을 짚고 교재로 유도한다.
  //   ⚠️ 이북에 레벨·영역 메타데이터가 없어 '이 축을 다루는 책'을 특정하지 못한다. 문구로만 연결하고
  //      실제 목록은 결과창 아래 추천 이북 칸(스토어 노출순)이다. 메타데이터가 생기면 여기서 매칭할 것.
  "rx.study_weak": "この領域を補強すると、全体の実力向上に大きく役立ちます。",
  "rx.study_pass": "Lv.{n} 合格に向けて Learning Library で学習しましょう。",
  "rx.study_cta": "👉 おすすめ E-BOOK を見る",
  "tip.prompt": "出力形式・例を入れ、作業を段階に分けて指示する練習をしましょう。",
  "tip.model": "タスクごとに最適なAIと、各モデルの苦手分野を学びましょう。",
  "tip.verify": "AIの回答を鵜呑みにせず、出典・事実を確認する習慣を。",
  "tip.automation": "繰り返し作業をAIとツールで自動化する方法を学びましょう。",
  "tip.data": "表・データをAIで整理・分析する練習をしましょう。",
  "tip.ethics": "個人情報・著作権・セキュリティを守って安全に使う方法を学びましょう。",
  "resnav.top": "↑ 上へ",
  "resnav.label": "問題（正解・不正解）",

  "rank.unplaced": "未配置",
  "rank.guest_bar": "ログインすると順位が表示されます",
  "rank.guest_login": "ログイン",
  "rank.skill_sub": "レーティング {o} · 受験{n}回",
  "rank.no_record": "受験履歴がありません — テストで配置を",
  "rank.login_hint": "ログインするとティアが表示されます",
  "rank.top": "上位{p}%",
  "rank.top_label": "上位",
  "rank.among": "全受験者中",
  "rank.me_pct": "あなた · {v}%",
  "rank.league": "{tier}リーグ",
  "rank.league_pop": "リーグ人数",
  "rank.tier_total": "参加者{n}人",
  "rank.my_rank": "自分の順位",
  "rank.hall": "殿堂",
  "rank.loading_more": "読み込み中…",
  "rank.hall_sub": "全体TOP10",
  "rank.global_rank": "全体順位",
  "rank.global_top": "全体上位",
  "rank.to_promote": "昇格まで",
  "rank.to_promote_pt": "{p}点",
  "rank.promotion_zone": "昇格ゾーン",
  "rank.top_tier": "最高ティア",
  "rank.pt": "{n}点",
  "rank.nth": "{n}位",
  "rank.trend_title": "順位の推移",
  "rank.trend_empty": "この期間の記録はありません。",
  "rank.you": "あなた",
  "rank.cta_test": "テストでランク配置",
  // 집계 리더보드(지역·국가·학교) — 협력 서사(하락/꼴찌 없음). /arena 지도 전용(랭킹 탭에서는 제거됨)
  "rank.coop_header": "みんなで上がっていく",
  // 랭킹 탭 = World / 내 국가 / 내 지역. 국가·지역 탭 라벨은 실제 이름(대한민국·서울)으로 치환되고,
  // 아래 tab_region·tab_country 는 코드가 없을 때(비로그인·온보딩 전) 폴백이다.
  // ⚠️ 'World' 는 WORLD ARENA 와 같은 **브랜드 영문 고정**이다(2026-08-11) — 6개국어 모두 같은 글자.
  "rank.tab_world": "World",
  "rank.tab_region": "自分の地域",
  "rank.tab_country": "自分の国",
  "rank.tab_school": "学校",
  "rank.scope_sub": "{name} TOP10",
  "rank.scope_guest": "ログインすると自分の国・地域のランキングが見られます",
  "rank.scope_no_region": "国・地域を設定するとこのランキングが開きます",
  "rank.scope_set_region": "地域を設定",
  "rank.next_gap": "次まで{n}点",
  "hub.today_todo": "今日のやること",
  "hub.todo_attendance": "出席",
  "hub.todo_problem": "今日の問題",
  "hub.todo_learn": "DAILY QUIZ",
  "hub.todo_game": "ミニゲーム",
  "rank.win_daily": "今日",
  "rank.win_season": "シーズン",
  "rank.aggregating": "集計中",
  "rank.avg": "平均",
  "rank.active_today": "今日の参加率",
  "country.KR": "韓国",

  "db.title": "マイ記録",
  "db.empty": "まだ提出したテストがありません。",
  "db.start": "テストを始める",
  "db.stat_maxlevel": "最高レベル",
  "db.stat_maxlevel_d": "最も高い挑戦",
  "db.stat_attempts": "累積受験",
  "db.unit_times": "回",
  "db.placed_before": "配置前",
  "db.recent": "最近 {d}",
  "db.stat_avgacc": "平均正答率",
  "db.recent_n": "直近{n}回",
  "db.stat_lastchange": "直近の変動",
  "db.last_lp": "前回のLP",
  "db.trend_title": "ランキング推移",
  // 랭킹 추이 기간 선택 — 시즌 = 6개월
  "db.trend_1w": "1週間",
  "db.trend_3m": "3ヶ月",
  "db.trend_season": "シーズン",
  "db.trend_season_hint": "シーズン = 6ヶ月",
  "db.trend_empty": "この期間の受験記録はありません。",
  "db.radar_title": "領域バランス",
  "db.radar_me": "自分",
  "db.radar_avg": "レベル平均",
  "db.vs_avg": "平均比",
  "db.cum_rating": "累積",
  "db.growth_title": "領域別の成長",
  // 대시보드 하단 = 승급 기록(옛 '응시 기록'은 삭제). 승급한 응시만 보여준다.
  "db.promo_title": "昇級履歴",
  "db.promo_total_n": "計{n}回昇級",
  "db.promo_empty": "まだ昇級の記録がありません。昇級するとここに残ります。",
  "db.hist_correct": "正解 {a}/{t}",

  "cal.summary": "直近6ヶ月 · {n}日活動",
  "cal.active": "活動日",
  "cal.days_active": "今月{n}日活動",
  // 활동 기록 달력은 출석만 표시한다 → 문구도 '활동'이 아니라 '출석'
  "cal.days_attended": "今月{n}日出席",
  "cal.weekdays": "日,月,火,水,木,金,土",
  "cal.did": "活動あり",
  "cal.none": "活動なし",
  "cal.dominant_attendance": "出席",
  "cal.dominant_learn": "学習",
  "cal.dominant_minigame": "ゲーム",
  "cal.dominant_leveltest": "受験",
  "cal.full_combo": "フルコンボ!",

  "auth.processing": "ログイン処理中…",

  "tier.iron": "アイアン",
  "tier.bronze": "ブロンズ",
  "tier.silver": "シルバー",
  "tier.gold": "ゴールド",
  "tier.platinum": "プラチナ",
  "tier.diamond": "ダイヤ",
  "tier.master": "マスター",

  "cat.prompt": "プロンプト設計",
  "cat.prompt.short": "プロンプト",
  "cat.model": "モデル・ツール理解",
  "cat.model.short": "モデル・ツール",
  "cat.verify": "検証・批判的思考",
  "cat.verify.short": "検証・批判",
  "cat.automation": "自動化・ワークフロー",
  "cat.automation.short": "自動化",
  "cat.data": "データ活用",
  "cat.data.short": "データ",
  "cat.ethics": "倫理・セキュリティ",
  "cat.ethics.short": "倫理・安全",
  "gate.seb_not_ready": "セキュアブラウザの設定が準備できていません。しばらくしてから再度お試しいただくか、管理者にお問い合わせください。",
  "gate.seb_opened_q": "セキュアブラウザは開きましたか？",
  "gate.seb_opened_desc": "まもなく自動で開きます。開かない場合は下でインストールして再実行してください。",
  "gate.seb_install_new": "📥 SEBをインストール（新しいウィンドウ）",
  "gate.title": "CARIS",
  "gate.fullname": "AI・ロボット融合能力資格試験\nCertification for AI & Robotics Integrated Skills (CARIS)",
  "gate.sub": "グローバルAI・ロボット協会公認 CARIS（CBT）",
  "gate.meta_questions": "問",
  "gate.meta_minutes": "分",
  "gate.meta_choices": "択",
  "gate.note_release": "• 受験後{d}日後に採点結果が公開されます。",
  "gate.note_block": "• 試験中の画面キャプチャ・コピー・離脱はブロックされ記録されます。",
  "gate.note_pc": "• モバイル・タブレットでは受験できず、PC（デスクトップ・ノートPC）でのみ受験できます。",
  "gate.btn_seb": "セキュアブラウザで受験開始",
  "gate.btn_start": "CARISを受ける",
  "gate.my_tickets": "マイ受験券",
  "gate.no_ticket": "今すぐ受験できる試験はありません。申し込むとここに表示されます。",
  "gate.btn_login": "ログインして受験する",
  "gate.login_hint": "CARISは本人確認のためGoogleログイン後に受験します。",
  "gate.check_link": "🧪 初めてですか？ 試験環境テスト（事前点検）→",
  "gate.instr_title": "重要なご案内",
  "gate.login_modal_title": "ログインが必要です",
  "gate.login_modal_desc": "ログインしていません。ログイン後に受験できます。",
  "prep.step_exam": "検定案内",
  "prep.exam_lead": "本試験は {exam} 検定です。以下の科目・試験構成・合格基準をご確認ください。",
  "prep.exam_unknown": "この受験券の等級情報が見つからず、検定案内を表示できません。以下の準備ステップはそのまま進めてください。",
  "prep.step_guide": "案内事項",
  "prep.step_notice": "注意事項",
  "prep.step_seb": "セキュリティソフト",
  // 유의사항 스텝 — SEB 부정행위 방지 기능 안내(12개)
  "prep.af_lead": "本試験はセキュアブラウザ（SEB）で実施され、次の不正防止機能が適用されます。",
  "prep.af1": "全画面の強制ロック",
  "prep.af2": "アプリ・ウィンドウ切り替えのブロック",
  "prep.af3": "画面キャプチャ・録画のブロック",
  "prep.af4": "クリップボードのブロック（コピー・貼り付け）",
  "prep.af5": "右クリック・ドラッグのブロック",
  "prep.af6": "更新・戻るのブロック",
  "prep.af7": "アドレスバーの除去",
  "prep.af8": "提出時に自動終了",
  "prep.af9": "サブモニターのブロック",
  "prep.af10": "仮想マシン（VM）実行のブロック",
  "prep.af11": "SEB（Safe Exam Browser）偽装の検証",
  "prep.af13": "開発者ツールのブロック",
  "prep.af12": "その他、協会が不正防止システムとして認める方法",
  "prep.step_menu": "メニュー説明",
  "prep.step_practice": "問題演習",
  "prep.step_ready": "受験準備完了",
  "prep.chk_pc": "PC（デスクトップ）環境",
  "prep.chk_screen": "画面サイズ（横1024px以上）",
  "prep.chk_fs": "全画面対応",
  "prep.chk_net": "インターネット接続",
  "prep.err_seb_not_ready": "セキュアブラウザの設定がまだ準備できていません。管理者にお問い合わせください。",
  "prep.err_start": "試験を開始できません。",
  "prep.guide_lead": "CARIS（CBT）の受験画面です。下記の案内を最後までご確認ください。",
  "prep.guide_li1": "全{q}問、制限時間{min}分、4択の選択式です。",
  "prep.guide_li2": "制限時間が終わると自動的に提出されます。",
  "prep.guide_li3": "採点結果は提出{d}日後に公開されます。",
  "prep.guide_li4": "本試験はPC（デスクトップ／ノートPC）専用です。",
  "prep.resume_title": "試験中断時の再接続・自動提出の規定",
  "prep.resume_li1": "停電・ネットワーク障害などで接続が切れた場合、その受験は一時的にロックされます。1:1お問い合わせでご連絡いただければ中断記録を確認のうえ復旧します。確認には営業日基準で時間がかかる場合があります。",
  "prep.resume_li2": "復旧すると、中断時点の解答と残り時間そのままで受験を継続できます。",
  "prep.resume_li3": "再受験は必ず試験運営期間内にのみ可能です。",
  "prep.resume_li4": "試験運営期間および締切時刻はすべて韓国標準時（UTC+9）基準です。",
  "prep.notice_lead": "次の注意事項を必ずお守りください。違反すると採点で不利益を受ける場合があります。",
  "prep.notice_li3": "未解答の問題があると提出されず、未回答の問題に移動します。",
  "prep.notice_li4": "モニターは1台のみ推奨で、セキュアブラウザが追加画面を遮ります。",
  "prep.notice_li5": "不正行為が確認されると受験が無効になる場合があります。",
  "prep.seb_running": "✅ セキュアブラウザで実行中です。次へ進んでください。",
  "prep.seb_install_btn": "セキュリティソフト（SEB）をインストール",
  "prep.seb_li1": "インストール時にWindowsで「発行元: ETH Zürich」と表示されれば正常です。",
  "prep.seb_li2": "「WindowsによってPCが保護されました」→ 詳細情報 → 実行（正常な手順）。",
  "prep.seb_li3": "インストール後、最後のステップの「試験開始」を押すとセキュアブラウザで開きます。",
  "prep.menu_lead": "試験画面の構成は次のとおりです。",
  "prep.menu_li1": "左：問題と選択肢。上部に残り時間を表示。",
  "prep.menu_li2": "右：答案用紙（番号ごとに1～4を選択）",
  "prep.menu_li3": "解答は選択肢をクリックするか、答案用紙の番号をクリックして選びます。",
  "prep.menu_li4": "スクラップした問題は状況で★で表示されます。",
  "prep.menu_li5": "下部の「前へ／次へ／提出」で移動・提出します。",
  "prep.menu_li_choose": "解答は選択肢をクリックするか、答案用紙の番号をクリックして選びます。",
  "prep.check_title": "受験環境の自動点検",
  "prep.check_ok": "正常",
  "prep.check_no": "要確認",
  "prep.chk_seb": "セキュアブラウザ（SEB）",
  "prep.chk_seb_running": "実行中",
  "prep.chk_seb_info": "実際の試験はセキュアブラウザで開始されます",
  "prep.sample_title": "模擬問題",
  "prep.sample_note": "下の選択肢をクリックして解答の選択を練習してみてください。（採点されません）",
  "prep.sample_eg": "例",
  "prep.sample_q": "次のうち、CARISの正しい受験方法はどれですか？",
  "prep.sample_opt1": "選択肢をクリックするか答案用紙の番号を押して解答を選ぶ",
  "prep.sample_opt2": "携帯電話で受験する",
  "prep.sample_opt3": "画面をキャプチャして保存する",
  "prep.sample_opt4": "別のタブを開いて検索する",
  "prep.sample_fb_ok": "正解です！実際の試験もこのように解答を選びます。",
  "prep.sample_fb_no": "練習なので大丈夫です。1番が正しい方法です。",
  "prep.sample_practice_btn": "セキュアブラウザで模擬1問を解いてみる →",
  "prep.ready_lead": "すべての案内を確認しました。準備ができたら試験を開始してください。",
  "prep.ready_li1": "「試験開始」を押すとすぐに試験が始まります。",
  "prep.ready_li2": "開始後は制限時間がすぐに始まり、最初からやり直すことはできません。",
  "prep.agree": "上記の案内と注意事項をすべて確認し、試験に応じます。",
  "prep.prev": "前へ",
  "prep.next": "次へ",
  "prep.starting": "試験を準備中…",
  "prep.start": "試験開始",
  "check.title": "試験環境テスト（事前点検）",
  "check.eyebrow": "事前点検",
  "check.sub": "実際の試験前に、このPCでセキュアブラウザが正しく開くか、受験環境が整っているかを事前に確認してください。",
  "check.sec1_title": "セキュリティソフト（Safe Exam Browser）の設置",
  "check.sec1_desc": "試験は、画面キャプチャ・コピー・アプリ切替を遮断するセキュリティプログラム（Safe Exam Browser）内で行われます。",
  "check.sec1_hint": "上の確認でセキュアブラウザが開かなかった場合は、ここから設置してください。",
  "check.install_btn": "セキュリティソフト（SEB）をインストール",
  "check.install_note1": "· インストール時にWindowsが「発行元: ETH Zürich」と表示すれば正常です。",
  "check.install_note2": "· 「WindowsによってPCが保護されました」と表示されたら、詳細情報 → 実行 を押してください。（正常な設置手順）",
  "check.sec2_title": "受験環境の点検",
  "check.sec2_desc": "セキュアブラウザを起動すると、以下の項目を点検します。",
  "check.chk_pc": "PC（デスクトップ）環境",
  "check.chk_screen": "画面サイズ",
  "check.chk_fs": "全画面対応",
  "check.chk_net": "インターネット接続",
  "check.chk_seb": "セキュアブラウザ（SEB）の起動",
  "check.monitor_note": "· モニター数はセキュアブラウザ実行時に自動点検されます。外部モニターは1台のみ接続してください。",
  "check.sebtest_btn": "セキュアブラウザで開いて確認",
  "check.sebtest_desc": "実際の試験と同じ方法でセキュアブラウザを起動し、このPCで正しく開くかを確認します。\n試験問題は出ません。",
  "check.back": "受験券に戻る",
  "done.title": "提出が完了しました",
  "done.sub1": "受験が正常に受け付けられました。セキュアブラウザは自動的に終了します。",
  "done.sub2": "採点結果は発表日以降にマイページで確認できます。",
  "done.home": "ホームへ",
  "complete.title": "提出が完了しました",
  "complete.sub": "受験が正常に受け付けられました。\n採点結果は発表日以降にマイページで確認できます。",
  "complete.voided_title": "受験を終了しました",
  "complete.voided_sub": "今回の受験は無効となり、採点されません。\n再受験するには最初からやり直してください。",
  "complete.practice_title": "模擬受験が終了しました",
  "complete.practice_sub": "本番の試験もこれと同じように進みます。\n準備ができたら本試験に挑戦してください。",
  "complete.close_seb": "試験を終了する",
  "complete.auto_close": "{n}秒後に自動的に終了します。",
  "complete.to_check": "受験状況を見る",
  "complete.home": "ホームへ",
  "seb.title": "セキュアブラウザで受験してください",
  "seb.sub": "この試験は画面キャプチャ・コピー・他プログラムへの切替を遮断するSafe Exam Browser（SEB）でのみ受験できます。",
  "seb.reqs_title": "✅ 受験前の確認事項",
  "seb.req_monitor": "モニターは1台のみ接続してください。ノートPCに外部モニターをつないでいる場合は外してください。",
  "seb.req_install": "Safe Exam Browserがインストールされている必要があります。（下の「SEB設置」）",
  "seb.req_vm": "仮想マシン（VM）・リモート操作（TeamViewer・AnyDeskなど）では受験できません。",
  "seb.req_record": "画面録画・キャプチャプログラムと不要なアプリをすべて終了してください。",
  "seb.install": "SEB設置",
  "seb.start": "セキュアブラウザで開始",
  "seb.start_unset": "セキュアブラウザで開始（設定前）",
  "seb.trouble_summary": "開始できず、英語のエラー画面が出ます",
  "seb.err_display": "モニターが2台以上接続されています。1台だけ残して他を外し、もう一度開始してください。",
  "seb.err_vm": "仮想マシン（VM）では受験できません。実際のPCで実行してください。",
  "seb.err_process": "ブロックされたプログラム（リモート操作・画面録画・メッセンジャーなど）が実行中です。すべて終了してから再度開始してください。",
  "seb.trouble_foot": "その他のエラーが続く場合は、エラー画面をキャプチャして管理者にお問い合わせください。",
  "run.lost_title": "試験情報を読み込めません",
  "run.lost_sub": "リロードされたか、不正なアクセスです。CARISページからやり直してください。",
  "run.to_exam": "CARISへ",
  "run.practice_done": "模擬問題が終了しました。本番の試験もこれと同じように動作します。",
  "run.submit_fail": "提出に失敗しました。もう一度お試しください。",
  "run.unanswered_warn": "未回答の問題が{n}問あります。\n最初の未回答問題（{first}番）に移動します。",
  "run.submit_confirm": "解答を最終提出しますか？\n提出後は修正できません。",
  "run.short_placeholder": "ここに解答を記入してください。",
  "run.short_hint": "記述式 · 管理者が検討して採点します",
  "run.short_chars": "文字",
  "run.short_label": "記述式",
  "run.short_done": "記入済み",
  "run.short_todo": "未記入",
  "run.time_up": "試験時間が終了したため自動提出されます。",
  "run.mask_title": "画面離脱が検知されました",
  "run.mask_sub": "試験画面に戻ってください。キャプチャ・離脱は記録されます。",
  "run.submit": "提出",
  "run.top_title": "{title} 問題演習",
  "run.q_badge": "選",
  "run.timer_title": "残り時間",
  "run.progress_title": "進捗（回答済み/全体）",
  "run.minutes": "{m}分",
  "run.font_size": "文字サイズ",
  "run.tab_canvas": "キャンバス",
  "run.tab_sheet": "解答用紙",
  "run.tab_status": "解答状況",
  "run.completed": "作成完了",
  "run.written": "回答",
  "run.legend_done": "完了",
  "run.legend_undone": "未完了",
  "run.legend_current": "現在の問題",
  "run.canvas_note": "計算・メモ用（提出されません）",
  "run.canvas_placeholder": "ここに自由にメモしてください。提出する解答には含まれません。",
  "run.prev": "前へ",
  "run.next": "次へ",
  "run.submitting": "提出中…",
  "run.quit": "終了",
  "run.quit_title": "試験を放棄しますか？",
  "run.quit_confirm": "今終了すると今回の受験は無効となり、採点されません。\n再受験するには最初からやり直す必要があります。",
  "run.quit_yes": "放棄して終了",
  "run.quit_no": "受験を続ける",
  "result.voided_title": "受験が無効になりました",
  "result.voided_sub": "管理者にお問い合わせください。",
  "result.home": "ホームへ",
  "result.load_failed_title": "結果を読み込めません",
  "result.submitted_title": "提出が完了しました",
  "result.submitted_sub": "全{n}問の解答が正常に受け付けられました。",
  "result.submitted_at": "提出日時",
  "result.release_at": "採点結果公開",
  "result.release_note_pre": "採点結果は",
  "result.release_days": "{d}日後",
  "result.release_note_post": "にこの画面で確認できます。",
  "result.graded_title": "採点結果",
  "result.submitted_prefix": "提出",
  "result.pass": "合 格",
  "result.fail": "不合格",
  "result.pass_criteria": "合格基準 — 全問題の60%以上正解",
  "result.issue_cert": "📜 資格証発行 (PDF)",
  "result.back": "← 戻る",
  "exresult.pass_badge": "おめでとうございます！合格です",
  "exresult.fail_badge": "残念ながら今回は不合格です",
  "exresult.score_unit": "取得点数",
  "exresult.earned_grade": "取得資格",
  "exresult.correct_count": "正解数",
  "exresult.cert_fallback": "CARIS",
  "exresult.info_pass": "この資格が認証する力を取得しました",
  "exresult.info_fail": "合格基準は60点以上です",
  "exresult.subject_title": "科目別の達成度",
  "exresult.subject_n": "科目 {n}",
  "exresult.correct_suffix": "正解",
  // 누르면 바로 PDF 가 나오는 게 아니라 결제 유도 화면으로 간다 → '(PDF)' 대신 '발급 신청'
  "exresult.issue_cert": "資格証の発行申請",
  "exresult.to_attempts": "← 受験履歴へ",
  "my.status.in_progress": "受験中",
  "my.status.submitted": "提出完了",
  "my.status.voided": "無効",
  "my.status.expired": "期限切れ",
  "my.tab.attempts": "受験状況",
  "my.tab.earned": "資格取得状況",
  "my.tab.issuance": "資格証発行状況",
  "my.load_failed": "履歴を読み込めません。",
  "my.login_required": "ログインが必要です",
  "my.login_required_sub": "マイページはログイン後にご利用いただけます。",
  "my.title": "マイページ",
  "my.eyebrow": "マイCARIS",
  "my.greeting": "{name} 様",
  "my.empty_attempts": "まだ受験履歴がありません。",
  "my.take_exam": "CARISを受ける",
  "my.submitted_prefix": "提出",
  "my.not_submitted": "提出されなかった受験です。",
  "my.grading_pre": "採点中 · ",
  "my.grading_days": "{d}日後",
  "my.grading_post": "（{date}）発表",
  "my.released": "結果が発表されました。成績をご確認ください。",
  "my.view_score": "成績を見る",
  "my.empty_earned": "取得した資格がありません。",
  "my.earned_badge": "取得",
  "my.earned_meta": "取得日 {date} · 資格番号 {no} · 得点 {correct}/{total}",
  "my.empty_issuance": "発行可能な資格証がありません。",
  "my.cert_no": "資格番号 {no}",
  "my.issued": "発行済み",
  "my.not_issued": "未発行",
  "my.reissue": "再発行",
  "my.issue": "資格証発行",
  "cert.alt": "資格証",
  "cert.print": "📄 PDFで保存 / 印刷",
  "cert.back": "← 戻る",
  // 발급(결제) 전 = 결제 유도 화면. 증서는 이 화면에서 일절 노출하지 않는다.
  // ⚠️ 한국어 표기는 화면 전체가 '인증서'로 통일됐다(2026-08-04). '자격증'으로 되돌리지 말 것.
  //    단 '자격번호'(cert_no)는 법정 서식 명칭이라 그대로 둔다 — 인증번호로 바꾸지 말 것.
  //    en/zh/hi/vi 는 원래 중립어(certificate)라 그대로, ja(資格証)도 지시 범위 밖이라 손대지 않았다.
  "cert.gate_title": "{grade} 資格証",
  "cert.gate_lead": "合格が確認されました。資格証は発行（決済）完了後に閲覧できます。",
  "cert.gate_acquired": "取得日",
  "cert.gate_perk_pdf": "資格証の原本閲覧・PDF保存・印刷",
  "cert.gate_perk_qr": "QR真偽確認が有効化 — 第三者がオンラインで検証可能",
  "cert.gate_perk_no": "資格番号の全体公開・発行記録の登録",
  "cert.gate_paid_note": "資格証の発行は有料サービスです。",
  // 디자인 견본(/certificate/sample) — 더미 인물 + 진한 워터마크
  "cert.sample_badge": "見本",
  "cert.sample_note": "資格証のデザイン見本です。記載の氏名・資格番号は例であり、発行するとご本人の情報と真偽確認QRが入った原本を受け取れます。",
  "cert.sample_wm": "見本 · SAMPLE",
  "cert.sample_wm_sub": "発行前 · 無断使用禁止",
  "cert.sample_cta": "資格証の発行申請",
  "cert.qr_locked": "発行後に有効",
  // 영문 성명 — 신규 시안이 영문 서식이라 증서에 각인되는 유일한 이름. 발급 신청 때 받는다.
  // ⚠️ 입력은 성·이름 두 칸(화면 순서 = 성 → 이름)인데 증서 각인은 "이름 성" 순이다.
  //    두 순서가 다르므로 hint 가 각인 순서를 반드시 말해줘야 한다.
  "cert.roman_last_label": "英文の姓 (Family name)",
  "cert.roman_first_label": "英文の名 (Given name)",
  "cert.roman_last_ph": "例: Ahn",
  "cert.roman_first_ph": "例: Hyeongjun",
  "cert.roman_hint": "パスポートの表記と同じに入力してください。資格証には «名 姓» の順で記載され、発行後は修正できません。",
  // 각인 확인 단계 — 이름은 발급 후 수정 불가라 결제 버튼과 실제 발급 사이에 한 번 보여준다.
  "cert.confirm_title": "この表記で記載されます",
  "cert.confirm_note": "発行後は修正できません。パスポートの表記と一致するか、姓と名を逆に書いていないかご確認ください。",
  "cert.confirm_ok": "この表記で発行",
  "cert.confirm_edit": "修正する",
  "cert.roman_invalid": "英文氏名をローマ字で入力してください（英字・空白・ハイフンのみ）。",
  "cert.qr_caption": "Verify authenticity",
  "cert.gate_pay": "決済して発行する",
  "cert.gate_later": "あとで",
  "cert.issuing": "発行中…",
  "cert.issue_failed": "発行に失敗しました。しばらくしてからもう一度お試しください。",
  "cert.issue_no_attempt": "発行できる受験記録がありません。マイページからもう一度お試しください。",
  "verify.title": "資格証の真偽確認",
  "verify.loading": "確認中…",
  "verify.valid_badge": "有効な資格証",
  "verify.expired_badge": "有効期限切れ",
  "verify.invalid_badge": "確認できません",
  "verify.invalid_desc": "この資格証の発行記録が見つかりません。QRコードまたはリンクを再度ご確認ください。",
  "verify.name": "氏名",
  "verify.grade": "資格名",
  "verify.cert_no": "資格番号",
  "verify.issued_at": "発行日",
  "verify.expires_at": "有効期限",
  "verify.no_expiry": "無期限",
  "verify.status": "状態",
  "verify.status_valid": "有効",
  "verify.status_expired": "期限切れ",
  "verify.system_sub": "資格真偽確認システム",
  "verify.official_body": "公認AI・ロボット資格検定機関",
  "verify.headline_valid": "有効な資格証です",
  "verify.headline_expired": "有効期限が切れた資格証です",
  "verify.headline_invalid": "確認できない資格証です",
  "verify.status_invalid": "無効",
  "verify.record_title": "資格情報",
  "verify.trust": "本結果はグローバルAI・ロボット協会の公式資格データベースをリアルタイムで照会したものです。",
  "verify.checked_at": "照会時刻",
  "guide.title": "CARISのご案内",
  "guide.lead": "グローバルAI・ロボット協会が実施する公認CBT試験 CARIS です。AI活用能力を客観的に評価します。",
  "guide.areas.title": "評価領域",
  "guide.areas.1.h": "AI活用・基礎",
  "guide.areas.1.d": "AIの概念と活用全般",
  "guide.areas.2.h": "データ・前処理",
  "guide.areas.2.d": "データの理解と加工",
  "guide.areas.3.h": "モデル・学習",
  "guide.areas.3.d": "モデルの原理と学習過程",
  "guide.areas.4.h": "倫理・セキュリティ",
  "guide.areas.4.d": "AI倫理とデータセキュリティ",
  "guide.areas.5.h": "実務・適用",
  "guide.areas.5.d": "現場での適用事例",
  "guide.exam.title": "試験の構成",
  "guide.exam.count.label": "問題数：",
  "guide.exam.count.value": "{n}問",
  "guide.exam.count.note": "（4択選択式）",
  "guide.exam.time.label": "試験時間：",
  "guide.exam.time.value": "{n}分",
  "guide.exam.pass.label": "合格基準：",
  "guide.exam.pass.value": "全問題の60%以上",
  "guide.exam.pass.note": "正解",
  "guide.exam.result.label": "結果発表：",
  "guide.exam.result.pre": "提出から",
  "guide.exam.result.value": "{n}日後",
  "guide.exam.result.note": "マイページで確認",
  "guide.how.title": "受験方法",
  "guide.how.1.h": "PC（デスクトップ・ノート）専用",
  "guide.how.1.d": "モバイル・タブレット不可",
  "guide.how.2.pre": "画面キャプチャ・コピー・離脱を遮断する",
  "guide.how.2.h": "セキュアブラウザ（SEB）",
  "guide.how.2.post": "で受験します",
  "guide.how.3.pre": "受験前に",
  "guide.how.3.h": "試験環境テスト",
  "guide.how.3.post": "で設置・環境を事前に確認できます",
  "guide.cta.take": "CARISを受ける →",
  "guide.cta.check": "試験環境テスト",
  "guide.eyebrow.intro": "ひと目で分かる",
  "guide.eyebrow.exam": "試験概要",
  "guide.eyebrow.areas": "評価基準",
  "guide.eyebrow.how": "受験案内",
  "guide.eyebrow.next": "次の案内",
  "guide.next.title": "次のステップ",
  "guide.next.score.d": "受験後、結果と合否をマイページで確認できます。",
  "guide.next.notice.d": "試験運営や受験環境に関する最新のお知らせを確認できます。",
  "guide.next.about.d": "CARISを実施する協会とその活動を紹介します。",
  "guide.callout.eyebrow": "なぜGARAか",
  "guide.callout.title": "誰でも、無料で、6か国語で証明",
  "guide.callout.desc": "追加費用や日程の制約なく、PCのセキュア環境で公正にAI活用能力を検証します。",
  "guide.callout.v1": "常時受験",
  "guide.callout.v1d": "決まった回次なくいつでも受験",
  "guide.callout.v2": "無料受験",
  "guide.callout.v2d": "受験・採点・資格証発行まで無料",
  "guide.callout.v3": "6か国語対応",
  "guide.callout.v3d": "韓国語・英語・日本語・中国語・ヒンディー語・ベトナム語",
  "guide.callout.v4": "PCセキュア受験",
  "guide.callout.v4d": "セキュアブラウザ(SEB)で公正に受験",
  "header.exam": "試験を受ける",
  "header.score": "成績確認",
  "header.support": "カスタマーサポート",
  "header.nav": "メインメニュー",
  "footer.quick": "クイックリンク",
  "footer.blurb": "CARISでAI・ロボット活用力を客観的に証明しましょう。常時・無料・6か国語で提供します。",
  "footer.rights": "© 2026 GARA. All rights reserved.",
  "login.welcome": "ようこそ",
  "login.subtitle": "GARAをご利用いただくにはログインしてください。",
  "login.google_title": "Googleで続ける",
  "login.kakao_title": "カカオで続ける",
  "fab.login_cta": "ログイン",
  "about.hero_line1": "グローバルAIロボット協会",
  "about.hero_line2": "AI・ロボット時代、人類が変化に適応し成長できるよう支援する機関です。",
  "about.subtitle": "超格差技術の時代をリードするグローバル標準資格\nGARAとともにあなたの専門性を証明し、未来産業の中核人材へと飛躍しましょう",
  "about.cta_exam": "CARISを受験する",
  "about.cta_brochure": "協会案内をダウンロード",
  // 히어로 로고 락업의 부제(큰 글씨 'CARIS' 는 브랜드명이라 번역하지 않는다).
  //   hero_title_l1/l2 는 락업 이전의 2줄 제목 — 현재 미사용이나 되돌릴 수 있게 남겨둔다.
  "guide.hero_lockup_sub": "AI・ロボット 融合力 資格試験",
  "guide.hero_title_l1": "全世界のAI・ロボット",
  "guide.hero_title_l2": "融合力 資格試験",
  "guide.hero_subtitle": "GARAは実務中心の生成AI活用能力を客観的な指標で評価する国際標準資格です。5つの核心領域を通じて、あなたの完璧なAI競争力を証明してください。",
  "guide.btn_apply": "試験を申し込む",
  "guide.btn_mock": "模擬テスト",
  // 브랜드 고유명 — 티어 이름처럼 전 언어 동일 표기.
  "guide.schedule_title": "CARIS Plan",
  "guide.status_open": "受付中",
  "guide.status_upcoming": "予定",
  "guide.status_closed": "受付終了",
  "sched.rolling_badge": "常時受付",
  "sched.prev": "前へ",
  "sched.next": "次へ",
  "guide.areas_title": "5大評価領域",
  "guide.areas_subtitle": "GARAはAI技術の単なる理解を超え、実際の業務環境での活用能力を総合的かつ体系的に評価します。",
  "guide.area1_title": "AI活用・基礎",
  "guide.area1_desc": "プロンプトエンジニアリングの基本原理と生成AIツールの特性の理解、および基本操作能力を評価します。",
  "guide.area2_title": "データ・前処理",
  "guide.area2_desc": "AIモデルの学習および成果物の導出のためのデータ収集・精製・加工などの前処理プロセスの理解度を評価します。",
  "guide.area3_title": "モデル・学習",
  "guide.area3_desc": "様々なAIモデルの特性を把握し、目的に合ったモデル選択および微調整（Fine-tuning）の概念を評価します。",
  "guide.area4_title": "倫理・セキュリティ",
  "guide.area4_desc": "AI活用時に発生し得る著作権、個人情報保護、バイアスの問題など、倫理的ガイドラインの遵守可否を評価します。",
  "guide.area5_title": "実務・適用",
  "guide.area5_desc": "テキスト、画像、コーディングなど様々なビジネス状況でAIツールを活用し、実際の成果物を効率的に導出する総合的な問題解決能力を重点的に評価します。",
  "guide.methods_title": "受験方法",
  "guide.methods_subtitle": "CARISは公正で確実な環境で実施されます。",
  "guide.method1_title": "PC（デスクトップ・ノートPC）専用",
  "guide.method1_desc": "安定した検定のため、モバイル・タブレット機器では受験できません。",
  "guide.method2_title": "セキュアブラウザ（SEB）",
  "guide.method2_desc": "画面キャプチャや離脱を根本から遮断する専用セキュアブラウザにより、評価の信頼性を保証します。",
  "guide.method3_title": "試験環境テスト",
  "guide.method3_desc": "受験前に必ず環境テストを行い、最適なシステム状態を点検してください。",
  "notice.hero_sub": "CARISの最新情報、試験案内、重要なお知らせをご確認ください。",
  "notice.filter_all": "すべて",
  "notice.tag_notice": "お知らせ",
  "notice.tag_guide": "案内",
  "notice.tag_required": "必読",
  "notice.empty": "「{filter}」カテゴリのお知らせはありません。",
  "notice.more": "もっと見る",
  "notice.read_more": "詳しく見る",
  "notice.back_list": "一覧へ戻る",
  "notice.not_found": "お知らせが見つかりません。",
  "faq.eyebrow2": "カスタマーセンター",
  "faq.hero_title": "何を",
  "faq.hero_title_em": "お手伝いしましょうか？",
  "faq.hero_sub": "グローバルなAI・ロボット工学資格、試験日程、資格認証プロセスに関する包括的なガイドと回答をご覧ください。",
  "faq.search_ph": "質問を検索...",
  "faq.search_go": "検索",
  "faq.card_schedule_title": "CARIS PLAN",
  "faq.card_schedule_desc": "今後のCARIS試験の日程をご確認ください。",
  "faq.card_verify_title": "資格認証",
  "faq.card_verify_desc": "マイページで取得した資格と資格証をご確認ください。",
  "faq.categories": "カテゴリー",
  "faq.help_title": "解決しませんでしたか？",
  "faq.help_body": "1:1 お問い合わせをいただければ、確認のうえご返信します。",
  "faq.help_link": "1:1 お問い合わせ",
  "faq.search_results": "検索結果",
  "faq.searching_sub": "「{query}」に関する質問です。",
  "faq.no_results": "「{query}」の検索結果はありません。",
  "faq.cat_empty": "このカテゴリーの問い合わせは準備中です。",
  "faq.q1.tag": "受験環境",
  "faq.q2.tag": "セキュアブラウザ",
  "faq.q3.tag": "結果",
  "faq.q4.tag": "採点",
  "faq.q5.tag": "再受験",
  "faq.q6.tag": "資格証",
  "faq.q7.tag": "受験中",
  "mypage.tab_attempts": "受験状況",
  "mypage.tab_earned": "資格取得状況",
  "mypage.tab_issuance": "証明書発行状況",
  "mypage.tab_inquiry": "1:1 お問い合わせ",
  "mypage.default_name": "受験者",
  "mypage.exam_fallback": "CARIS",
  "mypage.login_required": "ログインが必要です",
  "mypage.login_desc": "マイページはログイン後にご利用いただけます。",
  "mypage.login_google": "Googleでログイン",
  "mypage.login_kakao": "Kakaoでログイン",
  "mypage.title": "マイページ",
  "mypage.greeting_hello": "こんにちは、",
  "mypage.greeting_name": "{name} 様",
  "mypage.greeting_tail": "。",
  "mypage.empty_attempts": "まだ受験履歴がありません。",
  "mypage.go_exam": "CARISを受ける",
  "mypage.cta_sub": "CARIS公式の受験ページへ移動します。",
  "mypage.online": "オンライン",
  "mypage.grading": "採点中です。結果は約{days}日後に発表されます。",
  "mypage.expired": "受験期間終了",
  "mypage.view_score": "成績を確認",
  "mypage.empty_earned": "まだ取得した資格がありません。",
  "mypage.passed": "合格",
  // WORLD ARENA 레벨 인증서 — 레벨테스트에서 승급할 때마다 한 장씩 쌓인다(자격 취득 현황 탭)
  "mypage.cert_no": "認証番号",
  "mypage.empty_issuance": "発行可能な証明書がありません。",
  "mypage.tab_ebooks": "マイライブラリ",
  "mypage.empty_ebooks": "まだ購入したE-Book・講義がありません。",
  // 메인 3번째 CTA(landing.cta_learn)와 같은 이름. 브랜드 라벨이라 6개국어 동일 표기.
  "ebook.store_title": "Learning Library",
  // 안내에 쓰는 '서재' 이름은 실제 마이페이지 탭 라벨(mypage.tab_ebooks = 내 서재)과 같아야 한다.
  "ebook.store_sub": "購入した本はマイページ › マイライブラリで読めます。",
  "ebook.empty_store": "登録されたE-Bookがありません。",
  "ebook.buy": "購入する",
  "ebook.get_free": "無料で入手",
  "ebook.free": "無料",
  "ebook.owned": "所有中",
  "ebook.read": "読む",
  "ebook.view": "見る",
  "ebook.cover_zoom": "表紙を大きく見る",
  "ebook.processing": "処理中…",
  "ebook.bought": "購入完了 — マイライブラリに追加しました。",
  "ebook.login_to_buy": "ログイン後に購入できます。",
  // 비로그인이 구매 버튼을 눌렀을 때 뜨는 로그인 모달(제목 한 줄 + 버튼만 — 책 정보·설명은 넣지 않는다)
  "ebook.login_modal_title": "ログインが必要です",
  "ebook.go_store": "Learning Library へ",
  "ebook.go_library": "マイライブラリで見る",
  "ebook.load_failed": "E-Bookを読み込めません。",

  // ---- 결제(/checkout · /pay/success · /pay/fail) ----
  // ⚠️ 통화는 화면 언어와 무관하게 **원(KRW)** 이다. 금액 문자열은 여기 넣지 말고 lib/money.ts 의 krw() 로 찍을 것.
  "pay.title": "お支払い",
  "pay.back": "戻る",
  "pay.login_title": "ログインが必要です",
  "pay.order": "注文内容",
  "pay.preparing": "決済画面を準備しています…",
  "pay.pay_button": "支払う",
  "pay.moving": "決済画面へ移動中…",
  "pay.reopen": "決済画面をもう一度開く",
  "pay.reopen_hint": "決済画面を閉じましたか？まだ決済は行われていません — 上のボタンでもう一度開けます。",
  // 테스트 키로 붙어 있을 때만 뜬다 — 실키와 헷갈리면 안 되므로 문구를 부드럽게 쓰지 않는다.
  "pay.test_mode": "テスト環境です — 実際には決済されません。",
  "pay.not_configured": "決済はまだ準備中です。しばらくしてからお試しください。",
  "pay.bad_request": "決済情報が正しくありません。",
  "pay.error_generic": "決済を進められません。",
  "pay.confirming": "決済を確認しています",
  "pay.confirming_body": "画面を閉じずにお待ちください。",
  "pay.success_title": "決済が完了しました",
  "pay.free_title": "追加しました",
  "pay.free_body": "無料資料のため、そのままライブラリに追加されました。",
  "pay.free_title_exam": "受験券が発行されました",
  "pay.free_body_exam": "無料の級のため、決済なしで発行されました。",
  // 가상계좌 — 계좌만 발급된 상태다. 여기서 '완료'라고 하면 안 된다(입금 전이라 지급도 안 됐다).
  "pay.waiting_title": "入金をお待ちしています",
  // 결제는 성공했는데 지급이 보류된 상태(paid + fulfilled_at=null). **실패 문구를 쓰면 안 된다** — 돈은 이미 빠졌다.
  // 실패로 읽히면 사용자가 다시 결제하려다 '이미 결제 완료'를 보고 두 화면이 정반대로 말하게 된다.
  "pay.hold_title": "決済は完了しました",
  "pay.hold_body": "ただし付与処理が保留されています。運営が確認して対応します — 再決済はしないでください。",
  "pay.waiting_body": "発行された仮想口座へ入金されると自動的に付与されます。",
  "pay.fail_title": "決済できませんでした",
  "pay.fail_body": "決済がキャンセルされたか、承認されませんでした。",
  "pay.retry": "もう一度",
  "ebook.reader_back": "マイライブラリ",
  "ebook.reader_lang": "表示言語",
  "ebook.reader_fs": "全画面",
  // 러닝 라이브러리(/ebooks) — 레벨 | 교재 | 강의 3열. 레벨 이름·설명은 lv.N.name / lv.N.desc 를 그대로 쓴다.
  //   ⚠️ "레벨을 고르면 교재와 강의가 나타납니다" 같은 사용법 설명문은 넣지 않는다 — 화면을 보면 아는 것이다(2026-08-06 삭제).
  //   카탈로그 이름(LEVELTEST / CARIS)은 여기 없다 — 급수 이름(Beginner…)처럼 브랜드
  //   고유명이라 언어 무관 영문 고정이고, 단일 출처는 Ebooks.tsx 의 CATALOG_LABEL 이다.
  "ll.catalog": "教材の種類",
  "ll.level_col": "レベル",
  "ll.tier_col": "級",
  // ⚠️ 브랜드 표기라 6개국어 모두 같은 글자다(ko.ts 주석 참고).
  "ll.books": "E-Book",
  "ll.lectures": "講義",
  "ll.no_books": "このレベルの教材は準備中です。",
  "ll.no_lectures": "このレベルの講義は準備中です。",
  "ll.no_books_tier": "この級の教材は準備中です。",
  "ll.no_lectures_tier": "この級の講義は準備中です。",
  "ll.any_level": "レベル問わず",
  "ll.any_level_desc": "レベルに関係なく使える資料です。",
  "ll.any_tier": "級問わず",
  "ll.any_tier_desc": "級に関係なく使える資料です。",
  "ll.play": "再生",
  // 페이지 넘김(한 페이지에 한 개). 화면엔 ‹ 1 / 3 › 만 보이고 이 문구는 읽어주는 이름표다.
  "ll.prev": "前へ",
  "ll.next": "次へ",
  "ll.watch": "視聴する",
  "ll.playing": "再生中",
  "ll.empty_owned": "購入した教材はありません。",
  // 전체구매(2026-08-19) — 왼쪽 열 맨 위 칸. {n} = 할인율(BUNDLE_OFF_PCT).
  "ll.bundle": "まとめ買い",
  "ll.bundle_desc": "教材と講義を選んでまとめて追加できます。",
  "ll.bundle_hint": "{c}件すべて入れると{n}%割引",
  "ll.bundle_on": "{c}件すべて · {n}%割引を適用",
  "ll.pick": "選択",
  "ll.picked": "選択済み",
  "ll.pick_all": "すべて選択",
  "ll.pick_none": "選択解除",
  "ll.pick_count": "{n}件選択",
  "ll.pick_of": "{a} / {b}件選択",
  "ll.total": "合計",
  "ll.bundle_buy": "選択した項目を購入",
  "ll.bundle_empty": "追加できる項目がまだありません。",
  "mypage.reissue": "再発行",
  "mypage.issue": "発行申請",
  "mypage.view_sample": "見本を見る",
  "mypage.sample_title": "資格証の見本",
  "mypage.sample_desc": "資格証のデザインをご確認ください。",
  "gate.btn_check": "試験環境テスト",
  "gate.login_required": "受験にはGoogleログインが必要です。（未ログイン時は自動でご案内します）",
  "gate.format_value": "択一式（客観式）",
  "gate.instr_result_h": "結果発表（{d}日後）",
  "gate.instr_result_d": "試験終了後{d}日以内に個別に通知されます。",
  "gate.instr_security_h": "セキュリティ規定（キャプチャ禁止）",
  "gate.instr_security_d": "試験中の画面キャプチャおよび外部機器の使用は固く禁止されています。",
  "gate.instr_pc_h": "環境要件（PC専用）",
  "gate.instr_pc_d": "円滑な進行のため、必ずデスクトップ環境で受験してください。",
  "mobile.title": "PCでのみ受験できます",
  "mobile.desc": "CARISはセキュリティ・画面構成のため、デスクトップ／ノートPCでのみ受験できます。モバイル・タブレットでは試験を開始できません。",
  "mobile.home": "ホームへ",
  "run.question": "問題",
  "notice.title": "お知らせ",
  "notice.eyebrow": "お知らせ・案内",
  "notice.lead": "CARISの最新情報と重要なお知らせをご確認ください。",
  "notice.cat.notice": "お知らせ",
  "notice.cat.guide": "案内",
  "notice.cat.required": "必読",
  "notice.item1.title": "CARISの正式オープンのお知らせ",
  "notice.item1.body": "AI活用能力を評価するCARISが正式にオープンしました。PCでセキュアブラウザ（SEB）を使って受験できます。",
  "notice.item2.title": "セキュアブラウザ（SEB）受験のご案内",
  "notice.item2.body": "本試験は画面キャプチャ・コピー・離脱を遮断するSafe Exam Browserでのみ受験できます。受験前に「試験環境テスト」で設置・環境を事前にご確認ください。",
  "notice.item3.title": "不正行為防止のご案内",
  "notice.item3.body": "試験中の画面キャプチャ・コピー・他のウィンドウへの離脱は遮断・記録されます。不正行為が確認された場合、受験が無効になることがありますのでご注意ください。",
  "faq.title": "よくある質問",
  "faq.eyebrow": "ヘルプ・FAQ",
  "faq.lead": "受験前によくある質問をまとめました。お探しの答えがなければお知らせをご確認ください。",
  "faq.q1.q": "モバイルやタブレットで受験できますか？",
  "faq.q1.a": "いいえ。CARISはPC（デスクトップ・ノート）専用です。モバイル・タブレットでは受験できません。",
  "faq.q2.q": "セキュアブラウザ（SEB）とは何ですか？",
  "faq.q2.a": "試験中の画面キャプチャ・コピー・他プログラムへの切り替えを遮断する公式の試験セキュリティプログラムです。受験開始時に案内に従って一度インストールするだけです。",
  "faq.q3.q": "試験結果はいつ出ますか？",
  "faq.q3.a": "提出から1週間後、マイページの「成績確認」で合否と点数を確認できます。",
  "faq.q4.q": "合格基準はどうなっていますか？",
  "faq.q4.a": "全問題の60%以上正解で合格です。",
  "faq.q5.q": "再受験できますか？",
  "faq.q5.a": "各回のCARISは1回のみ受験でき、提出後は同じ回を再受験できません。次回の回であらためて受験いただけます。",
  "faq.q6.q": "資格証はどうやって受け取りますか？",
  "faq.q6.a": "合格すると、マイページの「資格証発行状況」または成績確認画面から資格証をPDFで発行・印刷できます。",
  "faq.q7.q": "試験中に未回答の問題があるとどうなりますか？",
  "faq.q7.a": "未回答の問題があると提出されず、警告の後に未回答の問題へ移動します。制限時間が終了すると自動的に提出されます。",
  "nav.exam": "CARIS",
  "nav.guide": "CARIS 案内",
  "nav.caris": "CARIS",
  // FAB 네비 전용 라벨 — 옆의 WORLD ARENA·CARIS 와 맞춰 전 언어 영문 대문자 고정.
  //   (본문에서 쓰는 common.home · ebook.store_title 은 현지화 그대로 둔다)
  "fab.home": "HOME",
  "nav.apply": "CARIS 申込",
  "nav.mypage": "マイページ",
  "nav.certpreview": "資格証プレビュー",
  "nav.certgatepreview": "資格証の決済誘導画面",
  "nav.notice": "お知らせ",
  "nav.faq": "よくある質問",
  "nav.support": "カスタマーセンター",
  "fab.dark": "ダークモード",
  "fab.light": "ライトモード",
  "nav.assoc": "協会紹介",
  "fab.login": "Googleでログイン",
  "fab.loginhint": "ログインすると受験できます",
  "fab.morebtn": "もっと見る",
  "fab.changeChar": "キャラクター変更",
  "fab.editName": "名前変更",
  "fab.logout": "ログアウト",
  "fab.uploadImg": "画像アップロード",
  "fab.uploadFail": "アップロードに失敗しました。",
  "fab.toTop": "トップへ",
  // FAB 의 빨간 점(1:1 문의 새 답변) 안내 — 점 자체는 aria-hidden 이라 이 문구가 유일한 설명이다.
  "fab.newanswer": "お問い合わせに新しい返信があります",
  // ── 의견함(/feedback) — FAB 패널의 빨간 항목. 1:1 문의와 달리 답변이 없다(수집 전용). ──
  "fab.feedback": "ご意見を送る",
  "feedback.title": "ご意見を送る",
  "feedback.sub": "ホームページ公開を前に、皆さまの貴重なご意見をお聞かせください。\nご利用中に不便だった点や、追加してほしいアイデアを自由にお寄せください。\nいただいたすべてのフィードバックに個別のご返信は難しいですが、担当チームがもれなく確認し、より良いサービスづくりに積極的に反映いたします。",
  "feedback.f_org": "所属",
  "feedback.f_name": "お名前",
  "feedback.f_path": "場所",
  "feedback.f_body": "内容",
  "feedback.ph_org": "例：経営企画室",
  "feedback.ph_name": "例：山田太郎",
  "feedback.ph_path": "例：https://gara-cbt.airobotassn.workers.dev/hub",
  "feedback.ph_body": "例：背景の色をもう少し濃くしてほしいです。",
  "feedback.hint_path": "ご意見の対象となる画面やメニューをお書きください。",
  "feedback.f_files": "ファイル添付（任意）",
  "feedback.files_drop": "ここにファイルをドラッグするか、スクリーンショットを貼り付け（Ctrl+V）してください。",
  "feedback.files_pick": "ファイルを選択",
  "feedback.files_hint": "最大3件・1件20MBまで。画像・PDF・PPT・Word・Excel・HWP・画面録画・ZIP に対応しています。",
  "feedback.files_up": "アップロード中…",
  "feedback.files_remove": "添付を外す",
  "feedback.err_file_type": "この形式はアップロードできません。",
  "feedback.err_file_size": "ファイル1件が20MBを超えています。",
  "feedback.err_file_many": "ファイルは3件まで添付できます。",
  "feedback.err_file_quota": "短時間にアップロードが多すぎます。しばらくしてからお試しください。",
  "feedback.err_file_fail": "ファイルをアップロードできませんでした。しばらくしてからお試しください。",
  "feedback.submit": "送信",
  "feedback.again": "もう一件書く",
  "feedback.done_title": "送信しました",
  "feedback.done_body": "いただいたご意見は運営に届きました。読んで改善に活かします。",
  "feedback.err_fail": "送信できませんでした。しばらくしてからもう一度お試しください。",
  "feedback.err_too_long": "内容が長すぎます。短くしてから送信してください。",
  "feedback.err_too_many": "短時間に送りすぎです。しばらくしてからお試しください。",
  "landing.hero_pre": "フィジカルAIの時代、",
  "landing.hero_em": "あなたの能力を",
  "landing.hero_post": "CARISで確かめよう",
  "landing.hero_cta": "CARISを受ける",
  "landing.cta_diagnose": "WORLD ARENA",
  "landing.cta_exam": "CARIS",
  // WORLD ARENA·CARIS 와 나란한 3번째 버튼이라 브랜드 라벨처럼 6개국어 동일 표기. 목적지 = /ebooks.
  "landing.cta_learn": "Learning Library",
  "landing.cta_learn_main": "Learning Library",
  "landing.card.guide.d": "試験構成・評価領域・受験方法をひと目で確認。",
  "landing.card.check.d": "受験前にセキュリティプログラムと環境を事前点検。",
  "landing.card.notice.d": "オープン情報と受験前に必読のお知らせをまとめました。",
  "nav.exampreview": "受験画面プレビュー",
  "nav.resultpasspreview": "合格画面プレビュー",
  "nav.resultfailpreview": "不合格画面プレビュー",

  // ── CARIS 자격 데이터(caris.ts) 다국어 — getTracks/getRolling 이 tr() 로 참조 ──
  // 공용 스펙 라벨(Guide·ExamApply 공유)
  "caris.lbl.subjects": "検定科目",
  "caris.lbl.format": "試験構成",
  "caris.lbl.duration": "試験時間",
  "caris.lbl.method": "検定方法",
  "caris.lbl.practical": "実技",
  "caris.lbl.pass": "合格基準",
  "caris.lbl.eligibility": "受験資格",
  "caris.lbl.target": "対象",

  // ── CARIS-Ⅰ (전국민 AI·로봇 리터러시): Beginner / Pro / Elite — 티어별 독립 시험, 고정 60% 합격 ──
  // 트랙 표기는 브랜드 하나로 통일 — 화면에서 'CARIS-Ⅰ/Ⅱ' 숫자는 쓰지 않는다(내부 키 t1/t2 는 유지).
  "caris.t1.name": "CARIS",
  "caris.t1.tagline": "全国民のAI・ロボットリテラシー",
  "caris.t1.eligibility": "受験資格の制限なし",
  "caris.t1.caption": "Beginner・Pro・Eliteの3段階で、日常の教養から専門家への入口までを各段階の個別試験で取得します。",
  "caris.t1.beginner.target": "誰もが取得する基礎教養",
  "caris.t1.beginner.format": "選択式（4択）40問 · 40分",
  "caris.t1.beginner.pass": "60点（24問）以上",
  "caris.t1.beginner.subj.0": "生成AIの日常活用",
  "caris.t1.beginner.subj.1": "日常のロボット技術とフィジカルAIの理解",
  "caris.t1.beginner.subj.2": "AI・ロボット倫理とデジタル安全リテラシー",
  "caris.t1.pro.target": "中高生・社会人の基礎",
  "caris.t1.pro.format": "選択式（4択）50問 · 50分",
  "caris.t1.pro.pass": "60点（30問）以上",
  "caris.t1.pro.subj.0": "生成AIツール活用とプロンプトエンジニアリング基礎",
  "caris.t1.pro.subj.1": "AI・ロボット自動化技術の理解と活用",
  "caris.t1.pro.subj.2": "フィジカルAIブロックコーディングとロボット制御基礎",
  "caris.t1.elite.target": "管理者・講師および専門家入門課程",
  "caris.t1.elite.format": "選択式50問 + 短答式10問 · 60分",
  "caris.t1.elite.pass": "60点（36問）以上",
  "caris.t1.elite.subj.0": "エッジAIデバイスとセンサーデータ処理",
  "caris.t1.elite.subj.1": "AI・ロボットシステム設計とサービス企画",
  "caris.t1.elite.subj.2": "PythonとAPIベースのAI・ロボット連携プログラミング",

  // ── CARIS-Ⅱ (피지컬 AI 전문가): Master / Grand Master / Zenith — 기존 Master 내용 유지, 이름만 교체 ──
  "caris.t2.name": "CARIS",
  "caris.t2.tagline": "フィジカルAI専門家課程",
  "caris.t2.eligibility": "下位ティアの順次取得が原則",
  "caris.t2.caption": "CARIS-Ⅰ Elite取得後、Masterから上位ティアへ順次受験する専門家課程です。",
  "caris.t2.master.prereq": "Elite取得者",
  // ⚠️ method·pass 는 ' · ' 로 잘라 줄바꿈한다(ExamApply). 구분자를 다른 문자로 바꾸면 한 줄로 뭉친다.
  //    문항 수·시간은 caris.ts 의 TIER_EXAM_SPEC 과 한 쌍이다 — 한쪽만 고치면 문항 관리 화면과 어긋난다.
  "caris.t2.master.method": "筆記 選択50+記述10（計60問）/ 60分 · 実技 PC作業型 / 120分",
  "caris.t2.master.subj.0": "AI・ロボットのハードウェアとモデル最適化",
  "caris.t2.master.subj.1": "ROS 2 ロボットソフトウェア開発",
  "caris.t2.master.subj.2": "基礎AI API連携、Python/C++による単一ロボット制御とLLM連携",
  "caris.t2.master.practical": "基礎AI API連携、Python/C++による単一ロボット制御とLLM連携",
  "caris.t2.master.pass": "筆記 科目別40点↑・平均60点↑ · 実技70点↑",
  "caris.t2.grandmaster.prereq": "Master取得者",
  "caris.t2.grandmaster.method": "筆記 選択50+記述10（計60問）/ 60分 · 実技 複合作業型 / 120分",
  "caris.t2.grandmaster.subj.0": "デジタルツイン設計と AI によるシミュレーション検証",
  "caris.t2.grandmaster.subj.1": "AI・ロボット融合システムのアーキテクチャ設計と知能制御の適用",
  "caris.t2.grandmaster.subj.2": "Isaac Sim・Gazebo による自動運転・ビジョンパイプライン構築と仮想-物理最適化",
  "caris.t2.grandmaster.practical": "Isaac Sim・Gazebo による自動運転・ビジョンパイプライン構築と仮想-物理最適化",
  "caris.t2.grandmaster.pass": "筆記 科目別40点↑・平均60点↑ · 実技70点↑",
  "caris.t2.zenith.prereq": "Grand Master取得者",
  // ⚠️ Zenith 는 **필기 서술·논술형 하나**다(2026-08-13). 옛 값은 '포트폴리오 제출 + 심층 면접 30분'
  //    이었는데 성격이 통째로 바뀌었다. 실기가 없으므로 caris.t2.zenith.practical 키는 계속 안 쓴다.
  "caris.t2.zenith.method": "筆記 記述・論述型 / 120分",
  "caris.t2.zenith.subj.0": "大規模 AI・ロボットシステム統合(SI)とエンドツーエンドのプロジェクト管理",
  // ⚠️ Zenith 는 **3과목**이다(2026-08-13). 예전엔 기능안전과 거버넌스·윤리가 subj.1 한 과목에 묶여 2과목이었는데,
  //    둘을 갈라 각각 과목으로 세우고 '보안'·'DX 전략'을 넣었다. 표준 3종은 각자 해당 과목을 따라갔다
  //    (ISO 10218=기능안전 · IEC 62443=보안 → subj.1 / ISO/IEC 42001=AI 거버넌스 → subj.2).
  //    과목 수는 caris.ts 의 T2_TIERS(subj)가 정한다 — 키만 늘리면 화면에 안 나온다.
  "caris.t2.zenith.subj.1": "国際標準(ISO 10218・IEC 62443)に基づく機能安全とセキュリティの適用",
  "caris.t2.zenith.subj.2": "AI ガバナンス(ISO/IEC 42001)・倫理・DX 戦略",
  "caris.t2.zenith.pass": "ルーブリック審査 · 審査委員3名の平均80点以上",
  // 상시(Rolling) 항목
  "caris.rolling.pro_cbt.name": "CARIS 常時検定 (CBT)",
  "caris.rolling.pro_cbt.badge": "常時受付",
  "caris.rolling.pro_cbt.date": "通年 · 予約日に受験",
  "caris.rolling.pro_cbt.desc": "ご希望の日付を予約してオンライン（CBT）で受験する常時検定です。",

  // ── Guide 히어로 (2026-07 개편: 로고 락업 + 일정 패널 → 카피 + CARIS PLAN 버튼 + 로봇 이미지) ──
  // h1 은 2줄. 1줄은 브랜드 표기라 전 언어 'AI·Robot' 고정, 2줄만 번역 + 끝의 'CARIS' 는 컴포넌트가 파란색으로 붙인다.
  "guide.hero_h1_l2": "融合力",
  // 소개 문단 — '|' 로 줄바꿈(2줄). 1줄=지향점, 2줄=CARIS 가 하는 일.
  "guide.hero_lead": "AIとロボット技術を理解し活用する未来型人材へ|CARISがあなたの融合力を検証し認証します。",
  "guide.plan_cta": "CARIS PLAN",

  // ── Guide '무엇인가요' 섹션 — 제목 + 영문 정식명 + 한 줄 정의 + 특징 카드 8장 ──
  "guide.what_title": "とは？",
  "guide.what_def": "CARISはAI・Robot融合力の資格検定です。",
  "guide.f1.t": "AI・Robot融合力の認証",
  "guide.f1.d": "体系的な能力検証システム",
  "guide.f2.t": "体系的な資格等級",
  "guide.f2.d": "段階別の成長ロードマップ",
  "guide.f3.t": "誰でも受験可能",
  "guide.f3.d": "年齢・専攻・経歴の制限なし",
  "guide.f4.t": "グローバルに活用可能",
  "guide.f4.d": "国際標準に準拠",
  "guide.f5.t": "技術の理解",
  "guide.f5.d": "AI・ロボット技術の基本原理を理解",
  "guide.f6.t": "実務での活用",
  "guide.f6.d": "業務・日常で使える実務力",
  "guide.f7.t": "創造的な融合",
  "guide.f7.d": "AI・ロボットの融合で新たな価値を創出",
  "guide.f8.t": "未来の力",
  "guide.f8.d": "未来社会の中核能力を確保",

  // ── Guide '자격 체계' 섹션 제목/부제 ──
  "guide.ladder_title": "資格体系",
  "guide.ladder_sub": "一段ずつ着実に、あなたの夢へ進みましょう！",

  // ── Plan(/plan · 시험 일정) ──
  "plan.title": "CARIS PLAN",
  "plan.sub": "CARIS資格検定の毎月の定期運営スケジュールです。",
  "plan.back": "CARIS",
  // ── /plan 접수중 회차 일정표(2026-08-20) — 줄 이름 4개. 날짜는 그 회차 값에서 온다. ──
  "plan.step_apply": "出願受付",
  "plan.step_exam": "受験期間",
  "plan.step_grade": "採点期間",
  "plan.step_result": "合格者照会",

  // ── Guide(자격검정 안내) 하드코딩 라벨 ──
  "guide.cert_intro_title": "AI・ロボット融合力 資格試験",
  // 피라미드 우측 그룹 라벨 — '|' 로 줄바꿈(브레이스 옆 2줄 세로 배치). 위 3티어=피지컬 AI, 아래 3티어=AI·로봇 리터러시
  "guide.group_physical": "フィジカルAI|専門家",
  "guide.group_literacy": "AI・ロボット|リテラシー",
  // CARIS-Ⅱ(피지컬 AI) 카드 배너 문구 — 응시화면의 prereq(응시자격)과 별개로 Guide 배너 전용. Master=초급/GM=중급/Zenith=고급
  "guide.ptrack.master": "フィジカルAI 初級専門家",
  "guide.ptrack.grandmaster": "フィジカルAI 中級専門家",
  "guide.ptrack.zenith": "フィジカルAI 上級専門家",
  "guide.ladder_hint": "級を押して試験科目を見る",
  "guide.aria_prev_track": "前の資格",
  "guide.aria_next_track": "次の資格",
  "guide.aria_prev_grade": "前の級",
  "guide.aria_next_grade": "次の級",

  // ── ExamSchedule(자격검정 접수) 하드코딩 라벨 ──
  "sched.badge": "試験日程",
  "sched.title": "CARISの申込",
  "sched.desc": "申し込む試験を選択してください。受付中の日程のみ申請できます。",
  "sched.regular": "定期試験日程",
  "sched.rolling": "常時試験",
  "sched.exam_date": "試験日",
  "sched.exam_period": "受験期間",
  "sched.apply_period": "受付期間",
  "sched.apply": "申し込む",
  "sched.empty": "登録された試験日程はありません。",

  // ── ExamApply(원서접수) 하드코딩 라벨 ──
  "apply.back": "CARIS PLAN",
  "apply.title": "願書受付",
  "apply.select_cert": "資格の選択",
  "apply.track": "トラック",
  "apply.tier": "等級",
  "apply.pay_summary": "決済サマリー",
  "apply.sel_cert": "選択資格",
  "apply.round": "回次",
  "apply.fee": "受験料",
  // exam_fees 에 그 티어의 행이 없을 때 — 금액 자리에 숫자를 지어내지 않고 이걸 띄우고 결제를 막는다.
  // (현재 CARIS-Ⅱ Master·Grand Master·Zenith 가 여기 해당)
  "apply.fee_tbd": "準備中",
  "apply.fee_free": "無料",
  "apply.free_btn": "無料で申し込む",
  "apply.total": "合計金額",
  // 추천 교재(원서접수 가운데 열) — 응시료와 **함께** 결제되는 곁다리다.
  "apply.book_col": "おすすめ教材",
  "apply.book_add": "購入する",
  "apply.book_added": "追加済み",
  "apply.book_row": "教材（{name}）",
  "apply.book_note": "申込と一緒に教材も購入すると便利です。",
  "apply.book_owned": "すでに購入済みの教材です。この本で一緒に準備しましょう。",
  "apply.book_owned_cta": "マイ書斎で見る",
  "apply.pay_btn": "決済する",
  "apply.pay_note": "決済には本人認証が必要です。受験料・本人認証・決済は後日連携予定（プレビュー）。",
  "apply.modal_title": "決済機能は準備中",
  "apply.modal_body": "現在は申込画面のプレビューです。本人認証・決済(PG)は近日連携予定です。",
  "apply.confirm": "確認",
  "apply.closed_title": "現在は申込期間ではありません",
  "apply.closed_body": "締切済み、またはまだ開始していない回次です。試験日程で申込受付中の回次をご確認ください。",
  "apply.closed_cta": "試験日程を見る",

  // ── SEB 설치 안내(SebInstall 컴포넌트) — ExamGate 모달 · ExamCheck Step1 공유 ──
  "seb.download": "セキュリティソフト(SEB)をダウンロード",
  "seb.dl_meta": "約{size} · インストールは一度だけ · 発行元 ETH Zürich（正常）",
  "seb.steps_title": "インストール方法（約2分）",
  "seb.step1_t": "ダウンロード",
  "seb.step1_d": "上のボタンを押すとインストーラーが保存されます。",
  "seb.step2_t": "実行（警告は正常）",
  "seb.step2_d_mac": ".dmg を開き SEB を「アプリケーション」へ移動し、初回は右クリック → 開く で起動してください。",
  "seb.step3_t": "試験を開く",
  "seb.step3_d": "インストール後、この画面に戻り下のボタンで SEB で試験を開きます。",
  "seb.launch_btn": "SEBで試験を開く",
  "seb.dialog_title": "WindowsによってPCが保護されました",
  "seb.dialog_more": "詳細情報",
  "seb.dialog_run": "実行",
  "seb.chip_once": "1回だけ",
  "seb.chip_publisher": "ETH Zürich 署名",
  "seb.chip_size": "約{size}",
  "seb.warn_title": "インストール中の警告は正常です",
  "seb.warn_title_win": "インストール中に「{dialog}」と表示されても正常です",
  "seb.warn_body_pre": "正式なプログラムなので、",
  "seb.warn_body_post": "の順に押すとインストールが続行されます。",
  "seb.fact_program": "プログラム",
  "seb.fact_maker": "開発元",
  "seb.fact_maker_v": "スイス連邦工科大学（ETH）の公式オープンソース — 世界中の大学・試験機関が使用",
  "seb.fact_install": "インストール",
  "seb.entry_loading": "試験を準備しています…",
  "seb.entry_retry": "再試行",
  // SEB 탈출 버튼. '취소'·'닫기' 처럼 모호하게 쓰지 말 것 — 갇힌 사람이 한눈에 알아봐야 하는 문구다.
  "envcheck.saving": "点検結果を保存しています…",
  "envcheck.save_failed": "点検記録を保存できませんでした。セキュアブラウザを閉じてもう一度お試しください。",
  "envcheck.ok_title": "環境チェック完了",
  "envcheck.ok_desc": "このコンピュータで受験できます。下のボタンでセキュアブラウザを閉じてください。",
  "envcheck.warn_title": "確認が必要な項目があります",
  "envcheck.warn_desc": "下の ✕ の項目を解決してから、もう一度点検してください。",
  "envcheck.row_seb": "セキュアブラウザで起動",
  "envcheck.row_fs": "全画面表示",
  "envcheck.row_net": "インターネット接続",
  "envcheck.row_screen": "画面サイズ",
  "seb.exit": "セキュアブラウザを終了",
  // SEB 로 로그인을 넘기는 인계표가 주소에 없을 때. 옛 .seb 파일로 들어왔거나 설정에서
  // startURLAppendQueryParameter 가 빠진 경우다 — SEB 안에서는 로그인할 방법이 없으므로 나가서 다시 시작해야 한다.
  // 재진입 무효 안내 — 사유와 다음 행동(문의)까지 말해줘야 한다. 무감독이라 옆에서 설명해 줄 사람이 없다.
  // ⚠️ "도와드립니다" 로 끝내면 안 된다 — 응시자는 (1) 남은 시간이 사라졌는지 (2) 응시 기간이 끝나면
  //    끝인지 (3) 언제 처리되는지를 모른 채 기다리게 된다. 세 가지를 다 말해준다.
  //    24시간 상주 운영이 아니므로 "바로 처리"를 약속하지 않는다.
  "seb.voided_how": "機器の故障・停電・ネットワーク切断で中断された場合はお問い合わせください。中断記録を確認し、復旧後は中断時点の解答と残り時間のまま続けて受験できます。ただし再受験は受験期間内のみ可能で、確認には営業日ベースでお時間をいただく場合があります。",
  "seb.err_no_handoff": "受験情報を確認できませんでした。",
  "seb.err_no_handoff_how": "セキュアブラウザを閉じて、通常のブラウザの受験準備画面から再度開始してください。",

  // ── 월드 아레나(/arena) — 지도·랭킹 패널·하단 런처 ──
  //   arena.b* = 하단 이동 버튼(Hub · 레벨테스트 · 오늘의 문제 · 미니게임)
  "arena.low": "低",
  "arena.high": "高",
  // ⚠️ arena.avgLevel 은 레벨테스트 시절 문구다. 지도 지표가 레벨 → 랭킹점수(season_total 평균, 베이지안 보정)로
  //    바뀌면서 arena.regionScore 로 대체했다. 다른 곳에서 안 쓰면 avgLevel 은 지워도 된다.
  "arena.avgLevel": "平均レベル",
  "arena.regionScore": "地域スコア",
  // ⚠️ 세계 지도의 칸은 '나라'고, 나라 안으로 들어가야 '지역'이다 — 그래서 한 쌍으로 둔다(`level === 0` 이 고른다).
  "arena.countryScore": "国スコア",
  "arena.part": "参加者",
  "arena.rankL": "順位",
  "arena.ourRank": "順位",
  "arena.topRegion": "最高地域",
  "arena.topCountry": "最高の国",
  "arena.totalPart": "参加人数",
  "arena.search": "地域を検索…",
  "arena.searchCountry": "国を検索…",
  "arena.world": "世界",
  "arena.worldLeague": "ワールドリーグ",
  "arena.league": " リーグ",
  "arena.ppl": "人",
  "arena.unit": "位",
  "arena.avg": "平均",
  "arena.drillHint": "「{n}」選択 · もう一度で市郡区へ",
  "arena.our0": "· 世界",
  "arena.our1": "· 自地域",
  "arena.our2": "· 自町",
  "arena.bLevel": "レベルテスト",
  "arena.bLevelS": "AI & ロボット実力テスト",
  "arena.bHub": "マイホーム",
  "arena.bHubS": "マイキャラクター",
  "arena.bDaily": "DAILY QUIZ",
  "arena.bDailyS": "今日の一問",
  // 아레나 화면 제목 — 제품명은 6개국어 영문 유지(ko 만 기존 표기 보존)
  "arena.title": "WORLD ARENA",
  "arena.bGame": "ミニゲーム",
  // 용어 퀴즈 게임 3종 + 로봇 조작/코딩 퍼즐 2종이라 '용어'로 못 묶는다 → AI·로봇 전체로 넓힌 문구.
  "arena.bGameS": "AI・ロボットゲーム",
  "arena.loading": "地図を読み込み中…",
  "arena.zoom_in": "拡大",
  "arena.zoom_out": "縮小",
  "arena.zoom_reset": "元に戻す",
  "arena.numbers_hide": "順位番号を隠す",
  "arena.numbers_show": "順位番号を表示",
  "arena.tabLeague": "世界リーグ",
  "arena.tabChat": "チャット",
  "arena.panelToggle": "パネル切替",
  "arena.dokdo": "獨島",
  // 유사채팅(pseudo-chat) 보드
  "chat.title": "チャット",
  "chat.placeholder": "メッセージを入力…",
  "chat.send": "送信",
  "chat.sending": "送信中…",
  "chat.empty": "まだメッセージがありません。最初の投稿をしてみましょう！",
  "chat.report": "通報",
  // 아바타 탭 → 그 사람 카드. 실패(랭킹 기록 없음·익명·탈퇴)는 조용히 삼키지 않고 한 줄로 알려준다.
  "chat.cardOf": "{name} のカード",
  "chat.noCard": "まだランキング記録のないユーザーです",
  "chat.reported": "通報しました",
  // 삭제 안내문은 남긴다 — 관리자 가림(chatHide)으로 여전히 이 상태가 나온다.
  //  ⚠️ 사용자 수정·삭제는 2026-08-13 제거됐다(chat.edit/delete/editedMark/editWindow/confirmDelete 키도 같이 삭제).
  //     수정이 있으면 욕설을 쓰고 신고당한 뒤 10분 안에 본문을 고쳐 증거를 지울 수 있었다.
  "chat.deleted": "削除されたメッセージです",
  // 번역 토글(2026-08-13). 대상 언어는 국가에서 정해지므로 문구에 언어 이름을 넣지 않는다
  //  — 넣으려면 전 세계 언어 이름을 6개국어로 들고 있어야 하고, 그건 사전이 아니라 Intl.DisplayNames 의 일이다.
  "chat.trOff": "翻訳",
  "chat.trOn": "原文を表示",
  "chat.trLoading": "翻訳中…",
  "chat.trMark": "翻訳済み",
  "chat.trFailed": "翻訳に失敗しました。しばらくして再度お試しください",
  "chat.blockedLocal": "不適切な表現が含まれています",
  "chat.blockedLink": "リンクは送信できません",
  "chat.justNow": "たった今",
  "chat.minutesAgo": "{n}分前",
  "chat.blockedMod": "ポリシー違反のため投稿できません",
  "chat.modUnavailable": "検閲システム点検中です。しばらくして再度お試しください",
  "chat.tooFast": "送信が速すぎます。少し待ってから再度お試しください",
  "chat.duplicate": "同じ内容を送信済みです",
  "chat.rateLimited": "リクエストが多すぎます。しばらくして再度お試しください",
  "chat.loginToJoin": "チャットに参加するにはログインしてください",
  "chat.scamNotice": "CARIS 運営がアカウント情報・認証番号・金品を要求することはありません。なりすましや利用者間の個人取引による被害について、当社は責任を負いません。",
  // 방(room) — World 1개 + 나라별 1개. 어느 방인지는 지도 선택이 정한다(/arena).
  // ⚠️ 'World' 는 브랜드 영문 고정(2026-08-11) — 6개국어 모두 같은 글자. 돌아가기 버튼도 같은 글자다
  //    (나라 방에 있을 때만 보이므로 '어디로 가는지'가 이름만으로 읽힌다).
  "chat.roomGlobal": "World",
  "chat.roomBack": "World",
  "chat.anonBadge": "匿名",
  "chat.reportTitle": "通報理由を選んでください",
  "chat.reportSpam": "スパム・広告",
  "chat.reportAbuse": "暴言・ヘイト表現",
  "chat.reportSexual": "わいせつ・性的表現",
  "chat.reportFlood": "連投・荒らし",
  "chat.reportPrivacy": "個人情報の掲載",
  "chat.reportOther": "その他",
  "chat.reportDetail": "詳細（任意）",
  "chat.reportSubmit": "通報する",

  // ══════════════════════════════════════════════════════════════════════════
  //  응시권(exam_tickets) · 응시료 결제 — 2026-08 추가
  //  한 기능이 여러 화면(원서접수 · 결제 · 마이페이지 · 응시 게이트)에 걸쳐 있어서
  //  네임스페이스별로 흩지 않고 여기 한 덩어리로 모았다. 위쪽 apply.* / pay.* / gate.* /
  //  prep.* / mypage.* 블록에도 같은 접두사의 옛 키가 있으니 검색으로 찾을 것.
  // ══════════════════════════════════════════════════════════════════════════

  // ── 응시권 상태·라벨 (ticket.*) — 마이페이지 '보유 응시권' 블록이 주 사용처 ──
  "ticket.section_title": "保有中の受験チケット",
  "ticket.empty": "まだ受験チケットがありません。",
  "ticket.empty_cta": "申し込みへ",
  "ticket.count": "{n}枚",
  // status_issued 를 '발급됨' 이 아니라 '미사용' 으로 쓰는 이유: 목록에 서는 모든 응시권은 이미 발급된 것이라
  // '발급됨' 은 정보가 0이다. 사용자가 알아야 하는 건 "아직 안 썼다" 는 사실이다.
  "ticket.status_issued": "未使用",
  // consumed 는 '응시 완료' 가 아니다 — 응시를 시작한 순간 소진되므로 진행 중일 수도 있다.
  "ticket.status_consumed": "使用済み",
  "ticket.status_void": "無効",
  "ticket.status_expired": "期限切れ",
  // 서버(my-attempts)가 내려주는 usableReason 코드 5종과 1:1 로 대응한다.
  //   before_exam_day · window_closed · already_taken · in_progress · expired
  // 서버는 코드만 주고 문구는 여기가 정한다 — 새 코드가 생기면 여기에도 키를 추가할 것.
  "ticket.usable": "今すぐ受験できます",
  "ticket.reason_before_exam_day": "{date}から受験できます",
  "ticket.reason_window_closed": "受験期間が終了しました",
  "ticket.reason_already_taken": "すでに受験済みです",
  "ticket.reason_in_progress": "受験が進行中です",
  "ticket.reason_expired": "受験チケットの有効期限が切れました",
  "ticket.go_exam": "受験へ進む",
  // 시험환경 점검 게이트 — 점검을 마쳐야 응시 버튼이 열린다(2026-08-11).
  //   잠금 브라우저가 안 켜지는 PC 라는 걸 시험 당일에 알면 손쓸 방법이 없어서 미리 걸러낸다.
  "ticket.env_do": "受験環境テスト",
  "ticket.env_done": "環境テスト済み",
  "ticket.env_required": "受験環境テストを終えると受験できます。",
  "ticket.open_now": "今すぐ受験できる試験 {n}件",
  "ticket.open_now_sub": "受験券から環境テストの後に受験してください。",
  // 필드 라벨 — 회차·등급은 원서접수 화면(apply.round / apply.tier)과 같은 말을 써야 한다.
  "ticket.round": "回次",
  "ticket.tier": "等級",
  "ticket.issued_at": "発行日",
  "ticket.exam_period": "受験期間",
  "ticket.price_paid": "お支払い金額",
  // 발급 출처(exam_tickets.source) — pg 는 평상시 굳이 안 띄우지만, 관리자/무료 발급과 구분이 필요할 때 쓴다.
  "ticket.source_pg": "決済で発行",
  "ticket.source_admin": "管理者発行",
  "ticket.source_free": "無料受験チケット",

  // ── 원서접수(/exam/apply) 추가분 ──
  // 회차가 연 급수(exam_rounds.open_tiers)에 없는 티어는 숨기지 않고 비활성 + 이 배지로 보여준다
  // — 어떤 급수가 존재하는지 알리는 값이 있어서다.
  "apply.tier_not_open": "この回次は未開設",
  "apply.owned": "購入済み",
  "apply.owned_cta": "受験チケットを見る",
  "apply.already_applied": "すでに申し込み済みの等級です",
  "apply.login_required": "ログイン後に申し込めます。",
  // 짧은 인라인 배지용. 전체 화면 안내는 기존 apply.closed_title / apply.closed_body 를 쓴다.
  "apply.period_closed": "申込期間ではありません",
  "apply.pay_go": "お支払いへ進む",
  // ⚠️ 기존 apply.pay_note 는 '결제는 추후 연결(미리보기)' 라고 적혀 있어 결제가 실동작하면 거짓말이 된다.
  //    실결제 연결 후에는 이 키로 갈아끼울 것(옛 키는 지우지 않고 남겨둔다).
  //    문구 안의 '마이페이지 › 시험 응시 현황' 은 mypage.tab_attempts 와 같은 말이어야 한다.
  "apply.pay_note_live": "お支払い後、マイページ › 受験状況で受験チケットを確認できます。",

  // ── 결제(/checkout · /pay/success) 추가분 ──
  "pay.go_tickets": "受験チケットを見る",
  "pay.go_plan": "試験日程を見る",
  "pay.exam_success_title": "受験チケットが発行されました",
  "pay.exam_success_body": "マイページ › 受験状況で確認し、受験期間になったら受験してください。",
  // 응시료는 카드·간편결제만 판다(가상계좌 제외). 그래도 가상계좌 결제가 들어오면 응시권을 발급하지 않으므로
  // 이북과 같은 '입금하면 자동 지급' 문구(pay.waiting_body)를 쓰면 안 된다.
  "pay.exam_waiting_body": "受験料はカード・簡単決済のみ対応しています。仮想口座へ入金しても受験チケットは自動発行されませんので、お問い合わせください。",
  // 자격증 발급비 — 결제로 끝나는 게 아니라 **발급이 한 걸음 남아 있다**. '결제 완료'로만 닫으면
  // 사용자는 자격증이 어디 있는지 못 찾는다(지급물이 따로 없는 유일한 상품이라 더 그렇다).
  "pay.go_cert": "資格証を発行する",
  "pay.go_attempts": "受験履歴を見る",
  "pay.cert_success_title": "発行料のお支払いが完了しました",
  "pay.cert_success_body": "続けて資格証を発行します。下のボタンを押してください。",
  "pay.cert_waiting_body": "発行された仮想口座へ入金されると資格証を発行できます。",
  // 통화 고지 — 화면 가격은 달러인데 토스 결제창은 원화로 뜬다. 이 문구가 없으면 사용자는 금액이 다르다고 느낀다.
  //   {krw} = lib/money.ts 의 krw() 로 찍은 실제 청구액 문자열.
  // ⚠️ 문장 안의 '1,500' 은 하드코딩이다 — lib/money.ts 의 KRW_PER_USD 를 바꾸면 6개국어를 전부 같이 고칠 것.
  // ⚠️ '○월○일 기준 환율' 이라고 쓰지 마라. 시장 환율이 아니라 우리가 정한 고정 환산값이다.
  "pay.currency_note": "実際の請求額は {krw} です（本日のレートで換算）。",
  // 해외 결제(엑심베이)는 **달러로 청구**된다 — 원화 고지문을 그대로 쓰면 화면과 결제창이 다른 돈을 말한다.
  //   {usd} = 실제 청구되는 달러 금액(서버가 정한 값 그대로).
  "pay.currency_note_usd": "海外決済は米ドルで請求されます。実際の請求額は {usd} です。",
  // 엑심베이 결제창은 우리 페이지에 아무것도 그리지 않는다 — 안내가 없으면 화면이 빈 것으로 읽힌다.
  "pay.cert_fee_note": "合格後に資格証を発行する際、別途費用が請求されます。",
  "pay.pg_eximbay_note": "「決済する」を押すと Eximbay の決済画面が開き、そこで支払い方法を選びます。",
  // ── 결제 전 취소·환불 규정 동의(2026-08-20) ──
  //    표 4줄은 응시료·자격증 발급비용, terms_ebook 은 이북·묶음용(디지털 콘텐츠라 기준이 다르다).
  //    ⚠️ 법적 고지라 임의로 줄이거나 의역하지 말 것 — 문구를 바꾸려면 규정 자체를 먼저 고쳐야 한다.
  "pay.terms_title": "キャンセル・返金規定",
  "pay.terms_col_when": "キャンセル時点（当日24:00基準）",
  "pay.terms_col_rate": "返金率",
  "pay.terms_col_note": "備考",
  "pay.terms_none": "不可",
  "pay.terms_r1_when": "受験日の7日前まで",
  "pay.terms_r1_note": "全額返金",
  "pay.terms_r2_when": "受験日の6日前～3日前まで",
  "pay.terms_r2_note": "半額返金",
  "pay.terms_r3_when": "受験日の2日前～当日の受験開始前",
  "pay.terms_r3_note": "原則不可",
  "pay.terms_r3_note2": "例外的に全額返金 — 直系家族の死亡・入院、感染症による隔離など、やむを得ない事由を証明した場合",
  "pay.terms_r4_when": "受験開始以降",
  "pay.terms_r4_note": "キャンセル・返金は一切不可（未受験を含む）",
  "pay.terms_ebook": "電子書籍・講義はデジタルコンテンツです。決済後に閲覧を開始するとクーリングオフが制限され、一度も閲覧していない商品のみ決済日から7日以内に返金できます。",
  "pay.terms_agree": "上記のキャンセル・返金規定を確認し、同意します。（必須）",
  "pay.terms_required": "返金規定に同意しないと決済できません。",
  // 위 고지문의 짧은 버전 — 가격만 달러로 보여주는 목록(/ebooks · /exam/apply)용. 청구액 보간이 없다.
  "pay.currency_hint": "国内決済は決済時点のレートでウォン請求されます。",

  // ── 응시 게이트(/exam) 거절 안내 ──
  // 여기서 막는 건 보안이 아니라 UX 다(준비 7단계를 다 밟고 마지막에 403 을 받지 않게 하는 것).
  // 실제 차단은 start-exam 이 응시권으로 한다.
  "gate.no_ticket_title": "受験チケットがありません",
  "gate.no_ticket_body": "受験するには、まず願書受付と受験料のお支払いが必要です。",
  "gate.no_ticket_cta": "申し込みへ",
  "gate.pick_ticket_title": "受験する試験を選んでください",
  "gate.pick_ticket_body": "受験チケットが複数あります。受験する試験を選択してください。",
  "gate.not_exam_period_title": "現在は受験期間ではありません",
  "gate.not_exam_period_body": "受験期間は {from} ～ {to} です。",
  // 익명(게스트) 세션에는 응시권이 붙을 수 없다 — 결제 자체가 로그인 계정에만 열려 있기 때문이다.
  "gate.login_paid_title": "決済したアカウントでログインしてください",
  "gate.login_paid_body": "受験チケットは決済したアカウントに発行されます。ゲスト（未ログイン）では受験できません。",

  // ── 응시 준비(/exam/prepare) — start-exam 이 돌려주는 에러 코드를 사람이 읽을 문구로 ──
  //   no_ticket · pick_ticket · attempt_exists · (응시창 밖) · (익명)
  "prep.err_no_ticket": "受験チケットがないため試験を開始できません。",
  "prep.err_pick_ticket": "受験する試験を選択してください。",
  "prep.err_exam_closed": "現在は受験期間ではありません。",
  "prep.err_login_paid": "決済したアカウントでログインしないと受験できません。",
  "prep.err_attempt_exists": "すでに受験済みの試験です。",

  // ── SEB 진입로(/exam/seb) — 익명 세션으로는 응시권을 가질 수 없어 로그인으로 돌린다 ──
  "seb.login_required": "受験するには決済したアカウントでログインしてください。",

  // ── 마이페이지 '시험 응시 현황' 빈 상태 분기 (응시권 없음 → 접수 / 응시권 있음 → 기존 mypage.go_exam) ──
  "mypage.empty_no_ticket": "まだ申し込んだ試験がありません。",
  "mypage.go_apply": "試験に申し込む",

  // ── DAILY QUIZ(/daily) · 미니게임(/games) ────────────────────────────────
  // ⚠️ 여기 있는 건 **화면 문구뿐**이다. 문제 자체(용어·설명·보기)는 src/lib/terms.ts 와
  //    public/games/*.html 의 POOL 에 한국어로 들어 있고 아직 다국어가 아니다.
  //    레벨테스트(questions 다국어 JSONB + translate-questions)처럼 콘텐츠 파이프라인을 붙이면
  //    그때 문항도 언어를 따라간다 — 그 전까지는 틀만 번역되고 문제는 한국어로 나온다.
  "daily.title": "DAILY QUIZ",
  "daily.login_note": "ログインするとDAILY QUIZ完了が記録されます",
  "daily.term_label": "今日の用語",
  "daily.correct": "正解です！🎉 本日のDAILY QUIZ完了。",
  "daily.wrong": "惜しい — 正解は {answer} です。挑戦したので完了！",
  "daily.already": "本日のDAILY QUIZは完了済みです。正解は {answer} です。",
  "daily.theory": "理論",
  "daily.hint_lead": "迷ったら",
  "daily.reward_head": "完了すると",
  "daily.done_note": "本日のDAILY QUIZ完了 ✓ 明日新しい問題が開きます。今日の分は見返せます（報酬は1日1回）。",
  "daily.saving": "記録中…",
  "daily.pop_title": "DAILY QUIZ完了！",
  "daily.pop_bonus": "7日達成 +{b}P",
  "daily.pop_grew": "キャラクターが今日もひとまわり成長しました。",
  "daily.pop_already": "本日の出席でコインは受け取り済みです。DAILY QUIZの記録は残りました。",

  "mg.title": "ミニゲーム",
  "mg.preparing": "準備中のミニゲームです。",
  "mg.to_list": "ミニゲーム一覧へ",
  "mg.guest_hint": "記録は残りません · ログイン",
  "mg.locked_hint": "ログインするとプレイできます",
  "mg.locked_title": "ログインすると開きます",
  "mg.locked_body": "未ログインでは「{game}」だけ遊べます。ログインするとすべてのゲームが開き、自己ベストとランキングも残ります。",
  "mg.not_saved": "この記録は保存されませんでした",
  "mg.not_saved_body": "ログインすると最高記録が残り、ゲームランキングに載ります。今は見るだけです。",
  "mg.keep_playing": "このまま続ける",
  "mg.rank_title": "{title} ランキング",
  "mg.rank_fail": "ランキングを読み込めませんでした。",
  "mg.rank_rule_level": "到達レベルが高い順 · 同じなら所要時間が短い順",
  "mg.rank_rule_score": "スコアが高い順 · 同じなら先に到達した順",
  "mg.rank_players": " · 参加 {n}人",
  "mg.rank_empty": "まだ記録がありません。最初の記録を作りましょう！",
  "mg.rank_need_login": "ログインすると自分の順位が表示されます。",
  "mg.rank_no_mine": "まだ自分の記録がありません — 一度プレイすると登録されます。",
  "mg.sec": "{n}秒",
  "mg.min_sec": "{m}分{s}秒",

  // 미니게임 카드(제목·소개·뱃지) — 'CARI' 는 캐릭터 이름이라 번역하지 않는다.
  "mg.beat-cari.title": "耐えろ CARI",
  "mg.beat-cari.tagline": "降りてくる天井から CARI を助けてあげて",
  "mg.beat-cari.badge": "AI · ロボット用語サバイバル",
  "mg.shoot-cari.title": "撃て CARI",
  "mg.shoot-cari.tagline": "迫りくる敵機から CARI を守ってあげて",
  "mg.shoot-cari.badge": "AI · ロボット用語シューティング",
  "mg.pick-cari.title": "選べ CARI",
  "mg.pick-cari.tagline": "足場が崩れる前に CARI を移してあげて",
  "mg.pick-cari.badge": "AI · ロボット用語○×サバイバル",
  "mg.reach-cari.title": "届け CARI",
  "mg.reach-cari.tagline": "CARI のロボットアームを動かして星に届かせて",
  "mg.reach-cari.badge": "ロボットアーム · 運動学パズル",
  "mg.program-cari.title": "プログラムしろ CARI",
  "mg.program-cari.tagline": "道がわからない CARI に手順を組んであげて",
  "mg.program-cari.badge": "ロボット · ブロックコーディングパズル",
  "mg.build-cari.title": "築け CARI",
  "mg.build-cari.tagline": "CARI の工場にコンベアを敷いてあげて",
  "mg.build-cari.badge": "スマートファクトリー · ライン設計パズル",
  "mg.block-cari.title": "止めろ CARI",
  "mg.block-cari.tagline": "CARI が送る書類、危ない所を隠してあげて",
  "mg.block-cari.badge": "AI に渡す前の情報マスキング",
  "mg.order-cari.title": "指示しろ CARI",
  "mg.order-cari.tagline": "図面どおりに作るよう CARI に指示してみて",
  "mg.order-cari.badge": "AI 指示文の設計パズル",
  "mg.feel-cari.title": "手探りで進め CARI",
  "mg.feel-cari.tagline": "前が見えない CARI にセンサーをつけてあげて",
  "mg.feel-cari.badge": "センサー · エッジAI探査",

  // ── 공유 카드(ShareCardModal + lib/shareCard.ts) ──────────────────────────
  // ⚠️ 카드 안 글자는 캔버스에 그려진다 — 훅을 못 쓰므로 renderShareCard 가 lang 을 받아 tr() 로 뽑는다.
  //    카드는 이미지로 밖으로 나가는 물건이라, 만든 사람의 화면 언어를 그대로 따라가는 게 맞다.
  "share.modal_title": "マイカードを共有",
  "share.making": "カードを作成中…",
  "share.make_fail": "カードを作成できませんでした",
  "share.img_fail": "画像を作成できませんでした",
  "share.saved": "画像を保存しました",
  "share.copied": "クリップボードにコピーしました",
  "share.copy_unsupported": "コピーに対応していないブラウザです",
  "share.do_share": "共有する",
  "share.do_save": "画像を保存",
  "share.do_copy": "画像をコピー",
  "share.note": "現在の順位・ティアで作ったカードです。",
  // 카드 안(캔버스)에 그려지는 글자
  "share.card.title": "シーズン記録",
  "share.card.rank_n": "{n}位",
  // ⚠️ 'World' 는 브랜드 영문 고정(2026-08-11) — 6개국어 모두 같은 글자.
  "share.card.world": "World",
  "share.card.country": "国",
  "share.card.region": "地域",
  "share.card.season_score": "シーズン点数",
  "share.card.joined": "登録日",
  "share.card.friend_code": "フレンドコード",

  // ── 캐릭터 허브(/hub) ─────────────────────────────────────────────────────
  // Hub.tsx 는 오래 한국어 하드코딩이었다(2026-08-07 일괄 이관). 문구를 새로 넣을 때 6개국어를 다 채울 것.
  // ⚠️ 토스트 아이콘은 예전에 문구를 정규식(/부족|필요|오류/)으로 검사해 골랐다 — 번역하면 그대로 깨져서
  //    Hub.tsx 가 종류(kind)를 들고 다니도록 바꿨다. 여기 문구를 고쳐도 아이콘은 영향받지 않는다.
  "hub.err.insufficient_points": "コインが足りません",
  "hub.err.already_owned": "すでに持っている限定アイテムです",
  "hub.err.unauthorized": "ログインが必要です",
  "hub.err.generic": "エラーが発生しました。しばらくしてからもう一度お試しください",
  // 방 저장 거절 사유(room 함수). 정상적으로 쓰면 안 뜬다 — 화면이 면 안 맞는 가구를 후보에서 이미 거른다.
  "hub.err.not_owned": "持っていない家具です",

  // ── 방 꾸미기(미니룸) ──

  // 가구 이름 — 상점·방 고르기가 같이 쓴다.

  // ── 남의 방(/room/:handle) ──
  "room.visit": "部屋を見る",
  "room.copy": "リンクをコピー",
  "room.copied": "コピーしました",
  "room.someone": "名前なし",
  "room.season_pt": "シーズン{n}点",
  "room.not_found": "部屋が見つかりません。",
  "room.my_room": "自分の部屋へ",
  "room.my_room_edit": "自分の部屋を模様がえ",

  // 꾸미기 파츠 이름 — 상점·토스트가 같이 쓴다.
  // ⚠️ 파츠 6종은 2026-08-14 에 상점에서 내려갔다(방 가구로 일원화). 이미 산 사람의 목록에는 남아 있어
  //    이름은 계속 필요하다 — 지우면 그 사람 화면에 키가 그대로 뜬다.
  "hub.part.hat_common_01": "ふたばキャップ",
  "hub.part.hat_common_02": "ニット帽",
  "hub.part.shoe_common_01": "ぬくぬく靴下",
  "hub.part.glasses_common_01": "まる眼鏡",
  "hub.part.wing_rare_01": "輝く翼",
  "hub.part.crown_rare_01": "小さな王冠",

  // 상단·공통
  "hub.gate_title": "ログインが必要です",
  "hub.gate_sub": "ログインして出席・ショップを使いましょう",
  "hub.banner_login": "出席・ショップはログインが必要です",
  "hub.share": "ランキング自慢",
  "hub.gift_btn": "ギフト",
  "hub.help_aria": "ポイントの獲得方法",
  "hub.coin_tip": "保有CARIコイン",
  "hub.mission_title": "今日のミッション",
  "hub.confirm": "OK",

  // 오른쪽 레일
  "hub.rail.closet": "きせかえ",
  "hub.rail.title": "称号",
  "hub.rail.invite": "招待報酬",

  // 오늘의 미션 칩
  "hub.mission.attendance": "出席",
  "hub.mission.daily_learn": "DAILY QUIZ",
  "hub.mission.minigame": "ミニゲーム",

  // 도크(출석 보상)
  "hub.reward_head": "出席報酬",
  "hub.attend.title": "出席履歴",
  "hub.attend.help": "サイトを開くと、その日の出席が自動で記録されます。",
  "hub.daily.claim": "今日の出席",
  "hub.daily.done": "本日の出席完了",
  "hub.day_n": "{n}日",

  // 토스트
  "hub.toast.no_points_item": "コインが足りません：{name}（{price}コイン）",

  // 구매/교환 완료 팝업
  "hub.buy.purchased": "購入完了！",


  // 상점 모달
  "hub.shop.balance": "保有CARIコイン",
  "hub.shop.owned": "保有中",
  "hub.shop.buy": "購入",
  "hub.shop.empty": "ショップに商品がありません。",
  "hub.shop.login": "ログインするとショップを利用できます。",
  // ── きせかえ（ショップ＋持ち物）・キャラ選択・チュートリアル (2026-08-20) ──
  "hub.shop.free": "無料",
  "hub.closet.title": "きせかえ",
  "hub.closet.tab_shop": "ショップ",
  "hub.closet.tryon_on": "プレビュー中",
  "hub.closet.tryon_back": "元に戻す",
  "hub.closet.tryon_buy": "{n}コインで購入",
  "hub.score_line": "シーズン {n}pt",
  "hub.score_top": "上位{n}%",
  "hub.closet.preview": "プレビュー",
  "hub.closet.tab_items": "持ち物",
  "hub.closet.g_character": "キャラクター",
  "hub.closet.g_skin": "背景・UIスキン",
  "hub.closet.g_part": "アイテム",
  "hub.closet.worn": "着用中",
  "hub.closet.wear": "着用する",
  "hub.closet.empty_character": "まだ持っているキャラクターがありません。ショップタブで見つけられます。",
  "hub.charpick.title": "一緒に過ごすキャラクターを選んでください",
  "hub.charpick.sub": "選べるのは一人だけです。選んだキャラクターはLv.1から一緒に育ちます。",
  "hub.charpick.g_m": "男性",
  "hub.charpick.g_f": "女性",
  "hub.charpick.go": "{name}ではじめる",
  "hub.charpick.pick_first": "先にキャラクターを選んでください",
  "hub.charpick.note": "あとでショップで別のキャラクターを手に入れれば、持ち物からいつでも変えられます。",
  "hub.tut.welcome_t": "CARIハブへようこそ",
  "hub.tut.welcome_b": "ここはキャラクターと過ごす場所です。どこに何があるか少しだけ見てみましょう。",
  "hub.tut.mission_t": "今日のミッション",
  "hub.tut.mission_b": "1日3つこなすとシーズンポイントが貯まります。ランキングを決める数値です。",
  "hub.tut.closet_t": "きせかえ",
  "hub.tut.closet_b": "貯めたコインでキャラクターや背景スキンを買い、持ち物から着替えられます。",
  "hub.tut.stamp_t": "出席スタンプ",
  "hub.tut.stamp_b": "サイトに入るだけで出席が自動で記録されます。何日続いたかはここで確認でき、7日そろえるとボーナスCARIコインがもらえます。",
  "hub.tut.prev": "戻る",
  "hub.tut.next": "次へ",
  "hub.tut.done": "はじめる",
  "hub.tut.skip": "スキップ",
  "hub.lvup.title": "LEVEL UP",
  "hub.lvup.before": "以前",
  "hub.lvup.now": "現在",
  "hub.lvup.ok": "確認",
  "hub.lvup.next": "次へ",
  "hub.err.invalid_character": "選べないキャラクターです",
  "hub.err.invalid_kind": "着用できない種類です",
  "hub.err.invalid_part": "着用できないアイテムです",
  "hub.part.char_a_m": "韓国風キャラ（男）",
  "hub.part.char_a_f": "韓国風キャラ（女）",
  "hub.part.char_b_m": "キャラB・男",
  "hub.part.char_b_f": "キャラB・女",
  "hub.part.char_c_m": "キャラC・男",
  "hub.part.char_c_f": "キャラC・女",
  "hub.part.skin_meadow": "草原",
  "hub.part.skin_palace_day": "古宮・昼",
  "hub.part.skin_palace_night": "古宮・夜",

  // 쿠폰함
  "hub.coupon.title": "クーポン",
  "hub.coupon.discount": "{n}%割引",
  "hub.coupon.sub": "Lv.{n}達成報酬",
  "hub.coupon.used": "使用済み",
  "hub.coupon.have": "保有",
  "hub.coupon.empty": "まだクーポンがありません。レベルアップで割引クーポンがもらえます！",
  "hub.coupon.login": "ログインするとクーポンが表示されます。",

  // 칭호
  "hub.title.title": "称号",
  "hub.title.login": "ログインすると称号コレクションが表示されます。",

  // 점수 획득 방법
  "hub.earn.title": "ポイント・コインの獲得方法",
  "hub.earn.lead": "いろいろな活動に参加してポイントを貯め、ランキングに挑戦しよう！",
  "hub.earn.col_act": "活動項目",
  "hub.earn.col_pt": "獲得ポイント",
  "hub.earn.pt": "+{n}点",
  "hub.earn.limit": "1日{n}回 · シーズン最大{max}点",
  "hub.earn.lv_head": "レベルテスト",
  "hub.earn.lv_sub": "レベルクリア時",
  "hub.earn.foot": "7段階すべて突破で{a}点 · 活動を合わせたシーズン満点は{b}点です。",
  "hub.earn.row.attendance": "出席する",
  "hub.earn.row.daily_learn": "DAILY QUIZを完了",
  "hub.earn.row.minigame": "ミニゲームをプレイ",
  "hub.earn.sec_score": "シーズンポイント",
  "hub.earn.sec_coin": "CARI コイン",
  "hub.earn.coin_lead": "ショップでキャラクターと部屋を飾るのに使う通貨です。ランキングのポイントとは別の財布です。",
  "hub.earn.col_coin": "獲得コイン",
  "hub.earn.coin_pt": "+{n}コイン",
  "hub.earn.coin_any": "もらった分",
  "hub.earn.coin.daily": "出席またはDAILY QUIZ",
  "hub.earn.coin.stamp": "7日スタンプの完成",
  "hub.earn.coin.referral": "友だち招待・招待コード登録",
  "hub.earn.coin.gift": "友だちからのプレゼント",
  "hub.earn.coin_note.daily": "1日1回 · 先に行った方",
  "hub.earn.coin_note.stamp": "7マスを埋めた日",
  "hub.earn.coin_note.referral": "招待した人・した人の両方に",
  "hub.earn.coin_note.gift": "送った人が決めた額",

  // 친구 초대 모달
  "hub.invite.title": "友達招待",
  "hub.invite.lead": "友達と一緒にCARISを！",
  "hub.invite.help": "友達が私の招待コードを入力すると、二人とも{n} CARIコインもらえます。",
  "hub.invite.my_code": "私の招待コード",
  "hub.invite.copied": "コピー済み",
  "hub.invite.copy": "コピー",
  "hub.invite.issuing": "招待コードを発行しています。",
  "hub.invite.login": "ログインすると招待コードが発行されます。",
  "hub.invite.redeem_head": "友達の招待コードを入力",
  "hub.invite.redeem_done": "✓ 招待コードを登録しました（1回のみ）",
  "hub.invite.checking": "確認中",
  "hub.invite.register": "登録",
  "hub.invite.hint": "友達に教えてもらった招待コードを入力すると、二人とも{n} CARIコインもらえます。",
  "hub.invite.err_not_found": "存在しない招待コードです。もう一度ご確認ください",
  "hub.invite.err_self": "自分の招待コードは使えません",
  "hub.invite.err_already": "すでに招待コードを登録済みです",
  "hub.invite.ok": "登録完了！あなたと招待してくれた友だちの両方が{n}コインを受け取りました",
  "hub.invite.fail": "登録できませんでした",

  // 코인 선물 모달
  "hub.gift.title": "コインギフト",
  "hub.gift.balance": "保有コイン",
  "hub.gift.received": "受け取ったギフト",
  "hub.gift.count_n": "{n}件",
  "hub.gift.older": "以前受け取ったギフト{n}件",
  "hub.gift.send_head": "コインを送る",
  "hub.gift.nick_label": "受け取る人のニックネーム",
  "hub.gift.nick_ph": "ニックネーム",
  "hub.gift.amount_label": "送るコイン",
  "hub.gift.send": "送る",
  "hub.gift.sending": "送信中",
  "hub.gift.confirm_q": "{name}さんに{n}コインを送りますか？",
  "hub.gift.confirm_warn": "送信後は取り消せません。",
  "hub.gift.history": "ギフト履歴",
  "hub.gift.empty": "まだやり取りしたギフトがありません。",
  "hub.gift.dir_in": "受取",
  "hub.gift.dir_out": "送信",
  "hub.gift.sent_ok": "{name}さんに{n}コインを送りました",
  "hub.gift.err_not_found": "そのニックネームの人はいません",
  "hub.gift.err_self_code": "自分のニックネームです",
  "hub.gift.err_too_many": "照会が多すぎます。しばらくしてからお試しください",
  "hub.gift.err_lookup": "確認できません",
  "hub.gift.err_amount_required": "送る金額を入力してください",
  "hub.gift.err_insufficient": "コインが足りません",
  "hub.gift.err_self": "自分には送れません",
  "hub.gift.err_invalid_amount": "送る金額が正しくありません",
  "hub.gift.err_too_fast": "同じ友達に送りすぎです。しばらくしてからお試しください",
  "hub.gift.err_send_fail": "送れませんでした",

  // 1:1 inquiry (My Page > Support). Category labels are keyed as `inq.cat.<code>`.
  "inq.intro": "お問い合わせいただければ、確認のうえご返信します。",
  "inq.private": "投稿者ご本人と運営のみが閲覧できます。",
  "inq.write": "問い合わせる",
  "inq.cat.exam": "受験・試験",
  "inq.cat.payment": "決済・返金",
  "inq.cat.account": "アカウント",
  "inq.cat.arena": "WORLD ARENA",
  "inq.cat.etc": "その他",
  "inq.ph_title": "タイトル",
  "inq.ph_body": "お問い合わせ内容をご記入ください。受験・決済のお問い合わせは、回次と級を一緒にご記入いただくと早く対応できます。",
  "inq.submit": "問い合わせを送信",
  "inq.sending": "送信中…",
  "inq.err_fields": "タイトルと内容をすべて入力してください。",
  "inq.err_login": "ログインが必要です。",
  "inq.login_required": "ログイン後にご利用いただけます。",
  "inq.empty": "まだお問い合わせがありません。",
  "inq.status_open": "返信待ち",
  "inq.status_answered": "回答済み",
  "inq.new_answer": "新しい回答",
  "inq.answer_at": "回答 · {d}",
  "inq.no_answer": "まだ回答が登録されていません。",
}

export default JA
