// ⚠️ 자동 생성 아님 — 손으로 고쳐도 된다. 다만 **6개 언어 파일의 키 집합은 같아야 한다**.
//    (없는 키는 tr() 이 한국어로 폴백하고, 한국어에도 없으면 키 문자열이 그대로 화면에 뜬다.)
//
// 언어별로 파일을 쪼갠 이유 (2026-08-14):
//   예전엔 i18n.tsx 한 파일에 키 × 6개국어가 전부 있었다(490KB). 이 파일은 최상위 프로바이더라
//   **모든 화면이 무조건** 6개국어를 통째로 받아 파싱했고, 첫 진입 JS 의 절반 가까이가 이거였다.
//   지금은 한국어만 정적으로 싣고(기본 언어 + 폴백) 나머지는 그 언어를 고른 사람만 받는다.
//
// ⚠️ 이 파일을 다른 데서 직접 import 하지 말 것 — 조회는 i18n.tsx 의 tr()/useT() 하나로만.
const KO: Record<string, string> = {
  "common.home": "홈",
  "common.close": "닫기",
  "common.cancel": "취소",
  "common.ranking": "랭킹",
  "common.hub": "허브",
  "common.my_home": "My Home",
  "common.leveltest": "WORLD ARENA",
  "common.login_google": "구글로 로그인",
  // 로그인 수단이 여럿(구글·카카오)이라 특정 수단이 아니라 로그인 페이지로 보낼 때 쓰는 라벨
  "common.login": "로그인",
  "common.logout": "로그아웃",
  "common.retry_test": "테스트 다시 응시하기",
  "common.loading": "불러오는 중…",

  "fab.guest": "게스트",
  "fab.account": "내 계정",
  "fab.loggedin": "로그인됨 · 티어 저장 중",
  "fab.savehint": "로그인하면 티어가 저장돼요",
  "fab.login_needed": "로그인 필요",
  "fab.brand": "GARA · WORLD ARENA",
  "fab.language": "언어",
  "fab.admin": "관리자 페이지",
  "fab.edit_name": "닉네임 변경",
  "fab.save": "저장",
  "fab.change_avatar": "캐릭터 변경",
  "fab.upload_image": "이미지 업로드",
  "fab.upload_fail": "업로드 실패",

  // 온보딩/지역 (ISO 3166-2:KR 17 시도)
  "region.KR-11": "서울특별시",
  "region.KR-26": "부산광역시",
  "region.KR-27": "대구광역시",
  "region.KR-28": "인천광역시",
  "region.KR-29": "광주광역시",
  "region.KR-30": "대전광역시",
  "region.KR-31": "울산광역시",
  "region.KR-41": "경기도",
  "region.KR-42": "강원특별자치도",
  "region.KR-43": "충청북도",
  "region.KR-44": "충청남도",
  "region.KR-45": "전북특별자치도",
  "region.KR-46": "전라남도",
  "region.KR-47": "경상북도",
  "region.KR-48": "경상남도",
  "region.KR-49": "제주특별자치도",
  "region.KR-50": "세종특별자치시",
  "onboarding.title": "어느 지역에서 함께 하시겠어요?",
  // 지역 목록이 없는 나라용 제목 — 화면에 지역 칸이 없는데 "어느 지역에서" 라고 물으면 없는 걸 묻는 말이 된다.
  "onboarding.title_country": "어느 나라에서 함께 하시겠어요?",
  // 1단계(설명) — 왜 지역을 받는지. 짧게, 크게.
  "onboarding.intro_title": "지역별로 순위를 겨뤄요",
  "onboarding.intro_body": "같은 지역·국가 사람들과 순위가 매겨져요.",
  "onboarding.intro_next": "시작",
  "onboarding.country": "국가",
  "onboarding.region": "지역",
  // 연령대 — 밴드만(정확한 나이는 안 받는다). '공개 안 함' 도 하나의 답으로 저장한다.
  "onboarding.age": "연령대",
  // 지역을 이미 확정한 회원이 연령대만 받으러 들어왔을 때의 제목(지역 질문이 없는 화면)
  "onboarding.age_title": "연령대를 알려주세요",
  "onboarding.age_hint": "통계에만 써요. 정확한 나이는 묻지 않아요.",
  "onboarding.age_10s": "10대 이하",
  "onboarding.age_20s": "20대",
  "onboarding.age_30s": "30대",
  "onboarding.age_40s": "40대",
  "onboarding.age_50s": "50대",
  "onboarding.age_60s": "60대 이상",
  "onboarding.age_private": "공개 안 함",
  // ⚠️ 2026-08-12: '영영 못 바꾼다' 가 아니다 — 마이페이지에서 딱 한 번 바꿀 수 있다. 문구가 규칙보다
  //    무섭게 남아 있으면 사용자가 이 화면에서 얼어붙는다(실제 규칙 = set-region 의 change 경로).
  "onboarding.lock_warn": "나중에 마이페이지에서 딱 한 번만 바꿀 수 있어요.",
  "onboarding.start": "이대로 시작",
  "onboarding.region_prefill_hint": "IP 추정값이에요. 확인/수정하세요.",
  "mypage.region_locked": "지역·국가는 변경할 수 없어요. 오배정은 문의해 주세요.",
  // 국가·지역 1회 변경(2026-08-12). 닉네임 1회 변경과 같은 성격이라 문구 결도 맞춘다.
  "mypage.region_change_once": "국가·지역 변경 (1회)",
  "mypage.region_change_warn": "저장하면 다시는 바꿀 수 없어요. 변경 기회는 한 번뿐이에요.",
  "mypage.region_change_used": "변경 기회를 이미 사용했어요.",
  "mypage.region_none": "이 국가는 지역을 나누지 않아요.",
  "mypage.profile_title": "내 정보",

  "landing.lead": "지금 바로 내 실력을 확인하세요.",
  "landing.cta": "CARIS 응시하기",
  // 레벨 추천(무료 진단 검색창) — /test/* 모듈용
  "reco.heading": "어느 정도 쓰는지 한마디로 적어보세요",
  "reco.placeholder": "내 AI 실력 어느 정도일까?",
  "reco.button": "레벨 추천받기",
  "reco.loading": "분석 중…",
  // 홈 검색 라우터(route-query) — 의미 기반 페이지 이동
  // 뒤에 붙던 예시(WORLD ARENA·시험안내·문의…)는 뺐다 — 메인 검색창은 질문 한 줄만 둔다.
  "route.placeholder": "무엇을 찾으세요?",
  "route.notfound": "올바르지 않은 검색어예요. 다시 입력해 주세요.",
  // CARIS ARENA 이식 잔여 키 (gara-cbt에 없던 7개)
  "rank.title": "랭킹",
  "report.btn": "🚩 오류 제보",
  "report.placeholder": "이 문항의 오타·오류를 알려주세요",
  "report.send": "보내기",
  "report.cancel": "취소",
  "report.sent": "✅ 제보 접수됐어요. 감사합니다!",
  "report.fail": "전송 실패",
  "reco.result": "입력하신 내용으로는 Lv.{n} {name}을(를) 추천해요",
  "reco.pct_range": "입력하신 내용이면 세계 상위 {lo}~{hi}% 정도예요",
  "reco.result_alt": " · Lv.{n}로 도전해도 좋아요",
  "reco.error": "추천에 실패했어요. 잠시 후 다시 시도해주세요.",
  "reco.start_lv": "Lv.{n}로 시작하기",
  "reco.unclear": "잘 이해하지 못했어요. 어느 정도 쓰는지 한 문장으로 적어주세요. (예: 나 초보야 / 자동화도 잘함)",
  "nav.about": "글로벌 AI 로봇협회",
  "nav.privacy": "개인정보처리방침",
  "nav.more": "자세히 알아보기",
  "nav.lecture": "강의",
  "nav.terms": "이용약관",
  "terms.title": "이용약관",
  "terms.todo": "내용 준비 중입니다.",
  "withdraw.title": "탈퇴",
  "withdraw.desc": "탈퇴 시 계정이 비활성화되고 {d}일 보관 후 회원정보가 파기됩니다. 그 전에 다시 로그인해 복구할 수 있어요.",
  "withdraw.button": "탈퇴",
  "withdraw.confirm": "정말 탈퇴하시겠어요? 계정이 비활성화되고 {d}일 후 회원정보가 파기됩니다. 그 전에 다시 로그인해 복구할 수 있어요.",
  "withdraw.done": "탈퇴 처리됐어요. 그동안 이용해 주셔서 감사합니다.",
  "withdraw.failed": "탈퇴 처리 중 오류가 발생했어요. 잠시 후 다시 시도해 주세요.",
  "withdraw.gate_title": "탈퇴 신청된 계정이에요",
  "withdraw.gate_body": "탈퇴하신 계정입니다. 보관기간 {d}일 안에 복구하면 등급·기록·구매하신 교재가 그대로 돌아와요. 복구하지 않으면 회원정보가 파기되고 이 계정으로는 다시 들어올 수 없어요.",
  "withdraw.gate_left": "복구할 수 있는 기간이 {n}일 남았어요",
  "withdraw.gate_purge_on": "{date}에 파기됩니다",
  "withdraw.gate_restore": "계정 복구하기",
  "withdraw.gate_logout": "복구하지 않고 로그아웃",
  "withdraw.restoring": "복구하는 중…",
  "withdraw.restore_failed": "복구하지 못했어요. 잠시 후 다시 시도해 주세요.",
  "lecture.title": "강의 화면입니다",
  "lecture.sub": "강의 콘텐츠는 준비 중입니다.",

  "about.title": "글로벌 AI 로봇협회",
  "about.eyebrow": "Global AI & Robotics Association",
  "about.tag": "AI & Robot 시대 인류가 변화에 적응하고 성장하도록 돕는 기관입니다.",
  "about.desc": "인공지능과 로봇 기술 융복합의 새로운 표준을 선도하는 글로벌 협회입니다.",
  "about.note": "협회 회원 및 회원사 모집, 활동 소식 등 자세한 내용은 순차적으로 공개될 예정입니다.",

  // 레벨선택 페이지 제목 — 아레나 지도(WORLD ARENA)와 겹치지 않게 런처 버튼과 같은 '레벨 테스트'로.
  "lv.title": "레벨 테스트",
  "lv.rule_btn": "등급 규칙",
  // 북두칠성 별자리(레벨 선택) 아래 한 줄 안내 — 인증서와 같은 별 순서라는 걸 알려준다
  "lv.dipper_hint": "별을 눌러 레벨을 고르세요 — 도달한 레벨은 금빛으로 켜집니다",
  // 닉네임 — 최초 1회 설정(/onboarding/nickname) + 마이페이지에서 1회 변경
  "nick.title": "닉네임을 정해 주세요",
  "nick.body": "랭킹·채팅·인증서에 표시되는 이름입니다. 구글 계정의 실명 대신 쓸 이름을 정해 주세요.",
  "nick.label": "닉네임",
  "nick.placeholder": "2~12자",
  "nick.rule": "{min}~{max}자 · 글자와 숫자, 밑줄(_)만 · 공백과 특수문자는 쓸 수 없습니다.",
  "nick.once_warn": "닉네임은 이후 딱 한 번만 바꿀 수 있습니다.",
  "nick.confirm": "확정",
  "nick.saving": "저장 중…",
  "nick.change_once": "변경 (1회 가능)",
  "nick.last_chance": "이번이 마지막 변경입니다. 확정하면 다시 바꿀 수 없습니다.",
  "nick.used_up": "변경권을 모두 사용했습니다",
  "nick.err_length": "2~12자로 입력해 주세요.",
  "nick.err_shape": "글자·숫자·밑줄(_)만 쓸 수 있습니다.",
  "nick.err_taken": "이미 사용 중인 닉네임입니다.",
  "nick.err_reserved": "사용할 수 없는 닉네임입니다.",
  "nick.err_locked": "변경권을 모두 사용했습니다. 고객센터로 문의해 주세요.",
  "nick.err_failed": "저장에 실패했습니다. 잠시 후 다시 시도해 주세요.",
  // 레벨테스트 인증서(/test/certificate) — 무료, 누르면 바로 발급
  "lcert.issue_btn": "인증서 발급",
  "lcert.print": "📄 PDF로 저장 / 인쇄",
  "lcert.no_name": "이름 없음",
  "lcert.empty": "아직 발급할 인증서가 없습니다. 레벨테스트에서 한 단계를 통과하면 여정의 첫 별이 켜집니다.",
  "lcert.load_failed": "인증서를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.",
  "lcert.go_test": "레벨테스트 하러 가기",
  // 문항 수는 레벨 구간별(10/20/30)이고 제한시간(분)이 그 수와 같다. 승급은 개수가 아니라 정답률. 강등은 없다.
  "lv.rule_up": "Lv.1~3은 {p1}%, Lv.4~7은 {p2}% 이상 맞히면 승급",
  "lv.rule_nodown": "점수가 낮아도 등급은 내려가지 않아요",
  "lv.rule_daily": "하루 {n}회 응시할 수 있고, 승급하면 1회가 추가돼요",
  // 레벨 선택(D안) — '지금 도전' 카드
  "lv.prev_level": "이전 레벨",
  "lv.next_level": "다음 레벨",
  "lv.start_now": "응시 시작 →",
  "lv.fact_q": "{n}문항",
  "lv.fact_min": "{n}분",
  "lv.fact_cut": "{n}개 맞히면 승급",
  "lv.left_today": "오늘 {n}회 남음 · 승급하면 1회 추가",
  "lv.daily_limit": "오늘 응시 횟수를 다 썼어요. 내일 다시 도전하거나, 승급하면 1회가 추가돼요.",
  "lv.rule_note": "Lv.{max}은 최고 등급",
  "lv.login_to_save": "테스트 결과를 저장하려면 로그인이 필요합니다",
  "lv.sub_tail": "선택한 난이도로 20문항 · 로그인 유저는 {d}일에 1회",
  "lv.rec_firsttime": "처음이라면 Lv.3부터 가볍게 시작해보세요",
  "lv.rec_for_user": "현재 실력 기준 Lv.{c} 추천",
  "lv.rec_challenge": " · Lv.{n}로 도전해도 좋아요",
  "lv.tag_rec": "추천",
  "lv.tag_challenge": "도전",
  "lv.locked": "잠김",
  "lv.locked_hint": "한 단계씩 승급하면 해제돼요",

  "lv.select": "선택 →",
  "lv.preparing": "준비 중…",
  // 문제은행이 아직 없는 레벨(COMING_SOON_LEVELS)의 카드 문구
  "lv.coming_soon": "오픈 예정",
  "lv.start_failed": "시작에 실패했습니다.",
  "lv.1.name": "입문",
  // Lv.1 = 3축(다른 레벨은 6축) — AI 프롬프트 활용 · AI 도구 이해 · AI를 활용한 문제해결
  "lv.1.desc": "AI 도구 이해·프롬프트 활용과 AI를 활용한 문제해결 입문",
  "lv.2.name": "기초",
  "lv.2.desc": "AI(생성형 AI 리터러시·AI 윤리), 프롬프트 엔지니어링 기초",
  "lv.3.name": "중급",
  "lv.3.desc": "생성형 AI 중급, 파이썬으로 AI와 하드웨어를 소프트웨어적으로 연결",
  "lv.4.name": "고급",
  "lv.4.desc": "생성형 AI 고급(LLM·RAG·앱개발), 기초 비전 AI(객체인식), C/C++ 기초",
  "lv.5.name": "심화",
  "lv.5.desc": "STM32 정밀제어, ROS2 시스템 통합, PLC 프로그래밍, 공정 시뮬레이션",
  "lv.6.name": "응용",
  "lv.6.desc": "지능형 시스템 고도화",
  "lv.7.name": "마스터",
  "lv.7.desc": "Digital Twin과 군집로봇을 아우르는 최종 마스터",

  "test.nodata": "진행 중인 레벨테스트 데이터를 찾을 수 없습니다. 새로고침 시 응시가 무효가 됩니다.",
  "test.restart": "다시 시작하기",
  // 응시 화면(레벨테스트·CBT 공용) 키보드 단축키 안내. 마우스 있는 기기에서만 노출.
  //   hint_nav = 보기가 없는 주관식 문항용(숫자키 안 먹음).
  "kbd.hint": "1–{n} 선택 · ←→ 이동",
  "kbd.hint_nav": "←→ 문항 이동",
  // 응시 화면 상단 이탈 카운터. '전체화면 유지' 안내 문구는 뺐다 — 시작 전 경고 게이트에서 이미 말하고,
  // 응시 중 상단바는 숫자(문항·시간·이탈) 셋만 크게 보이는 게 목적.
  "test.guard": "이탈 {v}/3",
  "test.quit": "✕ 나가기",
  "test.quit_confirm": "테스트를 그만두시겠어요?\n진행 중인 답안은 저장되지 않고, 이번 응시는 무효 처리됩니다.",
  "test.solved": "푼 문제 {a}/{t}",

  // 시작 전 경고 게이트 (TestRunner)
  "intro.title": "시작 전 꼭 읽어주세요",
  "intro.meta": "Lv.{lv} · 총 {q}문항 · 제한시간 {min}분",
  // 응시 전 경고 화면의 시험 정보 줄(규칙 목록과 같은 행 모양으로 위에 붙는다)
  "intro.fact_q": "총 {q}문항",
  "intro.fact_min": "제한시간 {min}분",
  "intro.anticheat": "🛡️ 부정행위 방지 시스템 구동 중 🛡️",
  "intro.fullscreen": "전체화면 모드 필수",
  "intro.rule_exit": "탭 전환 · 창 이동 · 전체화면 해제 시 경고 발생",
  "intro.rule_void": "경고 {m}회 누적 시 자동 무효 처리",
  "intro.rule_block": "복사 · 우클릭 · 드래그 기능 제한",
  "intro.start": "전체화면으로 시작 →",
  "intro.cancel": "취소",
  // 이동 한 쌍은 화살표를 같이 단다 — 한쪽만 달면 짝으로 안 읽힌다. 상단 키보드 안내(←→)와도 맞는다.
  "test.prev": "← 이전",
  "test.next": "다음 →",
  "test.submit": "제출하기",
  "test.submitting": "제출 중…",
  "test.submit_confirm_unanswered": "아직 답하지 않은 문항이 {n}개 있습니다.\n그래도 제출하시겠습니까?",
  "test.submit_confirm": "답안을 최종 제출하시겠습니까?\n제출 후에는 수정할 수 없습니다.",
  "test.submit_failed": "제출에 실패했습니다.",
  "void.title": "레벨테스트가 무효 처리되었습니다",
  "void.body": "화면 이탈이 3회 누적되어 부정행위로 간주됐어요. 이번 응시는 ",
  "void.body_strong": "저장되지 않으며 레이팅에 반영되지 않습니다.",
  "void.restart": "다시 시작",
  "void.home": "홈으로",
  "warn.left": "화면 이탈이 감지되었습니다 ({n}/{m}). {r}",
  "warn.tab": "탭을 전환했습니다.",
  "warn.blur": "창 포커스를 벗어났습니다.",
  "warn.fs": "전체화면을 벗어났습니다.",

  "result.loading": "결과를 불러오는 중…",
  "result.notfound": "결과를 찾을 수 없습니다.",
  "result.load_failed": "결과를 불러오지 못했습니다.",
  "result.level_result": "레벨 {n} 결과",
  "result.accuracy": "정답률 {p}%",
  // ⚠️ 여기 적는 건 **로그인하면 실제로 열리는 것**이어야 한다(= UnlockedPanel 이 그리는 것).
  //    옛 문구 '티어 · 6축 누적 분석 · 오답 해설' 은 없는 기능 두 개를 미끼로 걸고 있었다 —
  //    티어는 2026-08-04 제거, 오답노트는 결과창에서 제거됐다(Result.tsx 의 UnlockedPanel 끝 주석).
  //    UnlockedPanel 구성이 바뀌면 이 줄도 같이 고칠 것.
  "locked.title": "승급 판정 · 6축 누적 분석 · 학습 처방",
  "locked.peek": "거의 다 왔어요 — 잠금 해제까지 1초",
  "locked.desc": "로그인하면 이 결과가 내 누적 레이팅에 반영되고, 방금 본 점수 그대로 상세가 열립니다.",
  "locked.blocked": "최근 3일 내 응시 기록이 있어 이 결과는 계정에 연결되지 않았어요. 3일 후 다시 응시하면 누적 레이팅에 반영됩니다.",
  "locked.cta": "구글로 로그인하고 분석 보기",
  "result.overall": "누적 종합 레이팅 {o} / 100",
  "result.placing": " · 배치 진행 중",
  "result.promoted": "승급!",
  // 승급했을 때만 뜨는 결과창 CTA — 누르면 다음 레벨 응시를 바로 시작한다(응시 전 경고 화면으로 이동).
  "result.next_level": "Lv.{n} 도전하기 →",
  "rank.cur_level": "현재 등급 · 레벨 {n}",
  "db.points": "랭킹 점수 {p}",
  "db.skill_score": "실력 점수",
  "db.activity_score": "활동 점수",
  "db.season_total": "시즌 총점",
  // 랭킹 점수 = 레벨 + 맞힌 개수 (히어로 옆 인라인 분해). 수치는 scoring.ts 와 일치 — 규칙 바뀌면 같이 갱신.
  "db.score_break_h": "점수는 이렇게 정해져요",
  "db.eq_level": "레벨",
  "db.eq_correct": "맞힌 개수",
  "db.eq_points": "점수",
  "db.howto_up": "16개 이상 맞혀 레벨이 오르면 점수가 크게 올라요",
  "db.howto_within": "같은 레벨에선 많이 맞힐수록 점수가 조금씩 올라요",
  "result.radar_title": "영역별 레벨테스트 결과",
  "result.legend_thistest": "이번 회차",
  "result.legend_prevtest": "지난 동레벨",
  "result.legend_me": "나",
  "result.legend_avg": "티어 평균",
  "result.legend_prev": "지난 결과",
  "result.delta_title": "이번 테스트 변동",
  "result.delta_legend": "▲ 상승 / ▼ 하락",
  "result.answers_title": "문제 해설 · 오답노트",
  // 결과창 하단 이북 추천 칸(eBook Store 로 연결)
  // ⚠️ 'E-BOOK'·'Learning Library' 는 카탈로그 이름처럼 **6개국어 모두 같은 영문**이다 — 번역하지 말 것.
  "result.books_title": "추천 E-BOOK",
  "result.books_more": "Learning Library",
  "result.books_read": "바로 학습하기",
  "result.correct": "정답",
  "result.wrong": "오답",
  "result.mychoice": "(내 선택)",

  "rx.title": "테스트 분석 및 다음 단계",
  "rx.promote": "{tier}까지 {p}점 남았어요",
  "rx.master": "최고 티어 달성! 🎉",
  "rx.focus": "집중 보완 포인트: [{axis}] 영역",
  "rx.focus_peer": " (또래 평균보다 {gap}↓)",
  "rx.weak": "{axis}이(가) {tier} 평균보다 {gap} 낮아요",
  "rx.next_up": "잘했어요! Lv.{n} 도전을 위해 Learning Library로 학습해 보세요.",
  "rx.next_same": "Lv.{n} 한 번 더 다지기",
  "rx.next_down": "Lv.{n}로 기초 다지기",
  // 승급 못 했을 때(유지) 처방 둘째 줄 — 약점 영역을 짚고 교재로 유도한다.
  //   ⚠️ 이북에 레벨·영역 메타데이터가 없어 '이 축을 다루는 책'을 특정하지 못한다. 문구로만 연결하고
  //      실제 목록은 결과창 아래 추천 이북 칸(스토어 노출순)이다. 메타데이터가 생기면 여기서 매칭할 것.
  // ⚠️ 고정문이다 — 남은 동적 값은 약점 영역({axis})과 레벨({n}) 둘뿐이다(2026-08-26 지시).
  "rx.study_weak": "이 영역을 보완하면 전체 실력 향상에 큰 도움이 됩니다.",
  "rx.study_pass": "Lv.{n} 통과를 위해 Learning Library로 학습해 보세요.",
  "rx.study_cta": "👉 추천 E-BOOK 보기",
  "tip.prompt": "원하는 출력 형식·예시를 넣고 작업을 단계로 나눠 지시하는 연습을 해보세요.",
  "tip.model": "작업마다 어떤 AI가 적합한지, 각 모델이 잘 못하는 건 뭔지 학습해 보세요.",
  "tip.verify": "AI 답을 그대로 믿지 말고 출처·사실을 직접 확인하는 습관을 들여보세요.",
  "tip.automation": "반복 작업을 AI와 도구로 자동화하는 방법을 익혀보세요.",
  "tip.data": "표·데이터를 AI로 정리하고 분석하는 연습을 해보세요.",
  "tip.ethics": "개인정보·저작권·보안을 지키며 AI를 안전하게 쓰는 법을 익혀보세요.",
  "resnav.top": "↑ 맨 위로",
  "resnav.label": "문항 (정답·오답)",

  "rank.unplaced": "미배치",
  "rank.guest_bar": "로그인하면 내 순위가 표시돼요",
  "rank.guest_login": "로그인",
  "rank.skill_sub": "누적 레이팅 {o} · 응시 {n}회",
  "rank.no_record": "아직 응시 기록이 없어요 — 테스트로 배치를 받으세요",
  "rank.login_hint": "로그인하면 내 누적 티어가 여기 표시돼요",
  "rank.top": "상위 {p}%",
  "rank.top_label": "상위",
  "rank.among": "전체 응시자 중",
  "rank.me_pct": "나 · {v}%",
  "rank.league": "{tier} 리그",
  "rank.league_pop": "리그 인원",
  "rank.tier_total": "참가자 {n}명",
  "rank.my_rank": "내 순위",
  "rank.hall": "명예의 전당",
  "rank.loading_more": "불러오는 중…",
  "rank.hall_sub": "전체 TOP 10",
  "rank.global_rank": "전체 순위",
  "rank.global_top": "전체 상위",
  "rank.to_promote": "승급까지",
  "rank.to_promote_pt": "{p}점",
  "rank.promotion_zone": "승급 구간",
  "rank.top_tier": "최고 티어",
  "rank.pt": "{n}점",
  "rank.nth": "{n}위",
  "rank.trend_title": "순위 추이",
  "rank.trend_empty": "이 기간엔 기록이 없어요.",
  "rank.trend_help": "선이 올라가면 순위가 오른 거예요. 그래프를 짚으면 그날 점수가 보여요.",
  "rank.you": "나",
  "rank.cta_test": "테스트로 랭킹에 배치받기",
  // 집계 리더보드(지역·국가·학교) — 협력 서사(하락/꼴찌 없음). /arena 지도 전용(랭킹 탭에서는 제거됨)
  "rank.coop_header": "우리가 함께 올라갑니다",
  // 랭킹 탭 = World / 내 국가 / 내 지역. 국가·지역 탭 라벨은 실제 이름(대한민국·서울)으로 치환되고,
  // 아래 tab_region·tab_country 는 코드가 없을 때(비로그인·온보딩 전) 폴백이다.
  // ⚠️ 'World' 는 WORLD ARENA 와 같은 **브랜드 영문 고정**이다(2026-08-11) — 6개국어 모두 같은 글자.
  "rank.tab_world": "World",
  "rank.tab_region": "내 지역",
  "rank.tab_country": "내 국가",
  "rank.tab_school": "학교",
  "rank.scope_sub": "{name} TOP 10",
  "rank.scope_guest": "로그인하면 내 국가·지역 랭킹이 열려요",
  "rank.scope_no_region": "국가·지역을 설정하면 이 랭킹이 열려요",
  "rank.scope_set_region": "지역 설정하기",
  "rank.next_gap": "다음까지 {n}점",
  "hub.today_todo": "오늘 할 일",
  "hub.todo_attendance": "출석",
  "hub.todo_problem": "오늘의 문제",
  "hub.todo_learn": "오늘의 학습",
  "hub.todo_game": "미니게임",
  "rank.win_daily": "오늘",
  "rank.win_season": "시즌",
  "rank.aggregating": "집계중",
  "rank.avg": "평균",
  "rank.active_today": "오늘 참여율",
  "country.KR": "대한민국",

  "db.title": "내 기록",
  "db.empty": "아직 제출한 시험이 없어요.",
  "db.start": "테스트 시작하기",
  "db.stat_maxlevel": "최고 레벨",
  "db.stat_maxlevel_d": "가장 높이 도전",
  "db.stat_attempts": "누적 응시",
  "db.unit_times": "회",
  "db.placed_before": "배치 전",
  "db.recent": "최근 {d}",
  "db.stat_avgacc": "평균 정답률",
  "db.recent_n": "최근 {n}회",
  "db.stat_lastchange": "최근 변동",
  "db.last_lp": "지난 응시 LP",
  "db.trend_title": "랭킹 추이",
  // 랭킹 추이 기간 선택 — 시즌 = 6개월
  "db.trend_1w": "1주일",
  "db.trend_3m": "3개월",
  "db.trend_season": "시즌",
  "db.trend_season_hint": "시즌 = 6개월",
  "db.trend_empty": "이 기간엔 응시 기록이 없어요.",
  "db.radar_title": "영역 밸런스",
  "db.radar_me": "내 점수",
  "db.radar_avg": "레벨 평균",
  "db.vs_avg": "평균 대비",
  "db.cum_rating": "누적 레이팅",
  "db.growth_title": "영역별 성장",
  // 대시보드 하단 = 승급 기록(옛 '응시 기록'은 삭제). 승급한 응시만 보여준다.
  "db.promo_title": "승급 기록",
  "db.promo_total_n": "총 {n}회 승급",
  "db.promo_empty": "아직 승급한 기록이 없어요. 승급하면 여기에 남습니다.",
  "db.hist_correct": "정답 {a}/{t}",

  "cal.summary": "최근 6개월 · {n}일 활동",
  "cal.active": "활동한 날",
  "cal.days_active": "이 달 {n}일 활동",
  // 활동 기록 달력은 출석만 표시한다 → 문구도 '활동'이 아니라 '출석'
  "cal.days_attended": "이 달 {n}일 출석",
  "cal.weekdays": "일,월,화,수,목,금,토",
  "cal.did": "활동함",
  "cal.none": "활동 없음",
  "cal.dominant_attendance": "출석",
  "cal.dominant_learn": "학습",
  "cal.dominant_minigame": "게임",
  "cal.dominant_leveltest": "응시",
  "cal.full_combo": "풀콤보!",

  "auth.processing": "로그인 처리 중…",

  "tier.iron": "아이언",
  "tier.bronze": "브론즈",
  "tier.silver": "실버",
  "tier.gold": "골드",
  "tier.platinum": "플래티넘",
  "tier.diamond": "다이아",
  "tier.master": "마스터",

  "cat.prompt": "프롬프트 설계",
  "cat.prompt.short": "프롬프트",
  "cat.model": "모델·도구 이해",
  "cat.model.short": "모델·도구",
  "cat.verify": "검증·비판적 사고",
  "cat.verify.short": "검증·비판",
  "cat.automation": "자동화·워크플로우",
  "cat.automation.short": "자동화",
  "cat.data": "데이터 활용",
  "cat.data.short": "데이터",
  "cat.ethics": "윤리·보안",
  "cat.ethics.short": "윤리·보안",
  "gate.seb_not_ready": "보안 브라우저 설정이 준비되지 않았습니다. 잠시 후 다시 시도하거나 관리자에게 문의해 주세요.",
  "gate.seb_opened_q": "보안 브라우저가 열렸나요?",
  "gate.seb_opened_desc": "잠시 후 자동으로 열립니다. 안 열리면 아래에서 설치 후 다시 실행하세요.",
  "gate.seb_install_new": "📥 SEB 설치 (새 창)",
  "gate.title": "CARIS",
  "gate.fullname": "AI·로봇 융합역량 자격검정\nCertification for AI & Robotics Integrated Skills (CARIS)",
  "gate.sub": "글로벌 AI·로봇 협회 공인 CARIS (CBT)",
  "gate.meta_questions": "문항",
  "gate.meta_minutes": "분",
  "gate.meta_choices": "지선다",
  "gate.note_release": "• 응시 후 {d}일 뒤 채점 결과가 공개됩니다.",
  "gate.note_block": "• 시험 중 화면 캡처·복사·이탈은 차단되며 기록됩니다.",
  "gate.note_pc": "• 모바일·태블릿에서는 응시할 수 없으며, PC(데스크톱·노트북)에서만 응시할 수 있습니다.",
  "gate.btn_seb": "보안 브라우저로 응시 시작",
  "gate.btn_start": "CARIS 응시하기",
  "gate.my_tickets": "내 응시권",
  "gate.no_ticket": "지금 응시할 수 있는 시험이 없습니다. 원서접수를 하면 여기에 나옵니다.",
  "gate.btn_login": "로그인 후 응시하기",
  "gate.login_hint": "CARIS는 본인 확인을 위해 구글 로그인 후 응시합니다.",
  "gate.check_link": "🧪 처음이신가요? 시험환경 테스트(사전 점검) →",
  "gate.instr_title": "중요 안내사항",
  "gate.login_modal_title": "로그인이 필요합니다",
  "gate.login_modal_desc": "로그인이 되어 있지 않습니다. 로그인 후 응시할 수 있어요.",
  "prep.step_exam": "검정 안내",
  "prep.exam_lead": "이 시험은 {exam} 검정입니다. 아래 과목·시험 구성·합격 기준을 확인하세요.",
  "prep.exam_unknown": "이 응시권의 급수 정보를 찾지 못해 검정 안내를 표시할 수 없습니다. 아래 준비 단계는 그대로 진행하시면 됩니다.",
  "prep.step_guide": "안내사항",
  "prep.step_notice": "유의사항",
  "prep.step_seb": "보안 프로그램",
  // 유의사항 스텝 — SEB 부정행위 방지 기능 안내(12개)
  "prep.af_lead": "이 시험은 보안 브라우저(SEB)로 진행되며, 다음 부정행위 방지 기능이 적용됩니다.",
  "prep.af1": "전체화면 강제 잠금",
  "prep.af2": "앱·창 전환 차단",
  "prep.af3": "화면 캡처·녹화 차단",
  "prep.af4": "클립보드 차단(복사·붙여넣기)",
  "prep.af5": "우클릭·드래그 차단",
  "prep.af6": "새로고침·뒤로가기 차단",
  "prep.af7": "주소창 제거",
  "prep.af8": "제출 시 자동종료",
  "prep.af9": "보조 모니터 차단",
  "prep.af10": "가상머신(VM) 실행 차단",
  "prep.af11": "SEB(Safe Exam Browser) 위장 검증",
  "prep.af13": "개발자도구 차단",
  "prep.af12": "기타 협회가 부정행위방지시스템으로 인정하는 방법",
  "prep.step_menu": "메뉴 설명",
  "prep.step_practice": "문제풀이 연습",
  "prep.step_ready": "시험 준비 완료",
  "prep.chk_pc": "PC(데스크톱) 환경",
  "prep.chk_screen": "화면 크기 (가로 1024px 이상)",
  "prep.chk_fs": "전체화면 지원",
  "prep.chk_net": "인터넷 연결",
  "prep.err_seb_not_ready": "보안 브라우저 설정이 아직 준비되지 않았습니다. 관리자에게 문의해 주세요",
  "prep.err_start": "시험을 시작할 수 없습니다",
  "prep.guide_lead": "CARIS(CBT) 응시 화면입니다. 아래 안내를 끝까지 확인해 주세요",
  "prep.guide_li1": "총 {q}문항, 제한시간 {min}분, 4지선다 객관식입니다",
  "prep.guide_li2": "제한시간이 끝나면 자동으로 제출됩니다",
  "prep.guide_li3": "채점 결과는 제출 {d}일 후 공개됩니다",
  "prep.guide_li4": "본 시험은 PC(데스크톱/노트북) 전용입니다",
  "prep.resume_title": "시험 중단 시 재접속·자동 제출 규정",
  "prep.resume_li1": "정전·네트워크 오류 등으로 접속이 끊기면 해당 응시는 일시적으로 잠깁니다. 1:1 문의로 알려주시면 중단 기록을 확인해 복구해 드리며, 확인에는 영업일 기준 시간이 걸릴 수 있습니다",
  "prep.resume_li2": "복구되면 중단 시점의 답안과 잔여 시간 그대로 이어서 응시합니다",
  "prep.resume_li3": "재응시는 반드시 전체 시험 운영 기간 내에만 가능합니다",
  "prep.resume_li4": "시험 운영 기간과 마감 시각은 모두 한국 표준시(UTC+9) 기준입니다",
  "prep.notice_lead": "다음 유의사항을 반드시 지켜주세요. 위반 시 채점에서 불이익을 받을 수 있습니다",
  "prep.notice_li3": "미응답 문항이 있으면 제출되지 않으며, 미응답 문항으로 이동합니다",
  "prep.notice_li4": "모니터는 1대만 권장하며, 보안 브라우저가 추가 화면을 가립니다",
  "prep.notice_li5": "부정행위가 확인되면 응시가 무효 처리될 수 있습니다",
  "prep.seb_running": "✅ 보안 브라우저로 실행 중입니다. 다음으로 진행하세요",
  "prep.seb_install_btn": "보안 프로그램(SEB) 설치하기",
  "prep.seb_li1": "설치 시 Windows에 “게시자: ETH Zürich” 로 표시되면 정상입니다",
  "prep.seb_li2": "“Windows가 PC를 보호했습니다” → 추가 정보 → 실행 (정상 과정)",
  "prep.seb_li3": "설치 후 마지막 단계의 「시험 시작」을 누르면 보안 브라우저로 열립니다",
  "prep.menu_lead": "시험 화면 구성은 다음과 같습니다",
  "prep.menu_li1": "왼쪽: 문제와 보기, 상단에 잔여시간(남은 시간) 표시",
  "prep.menu_li2": "오른쪽: 답안지(번호별 1~4 선택)",
  "prep.menu_li3": "답은 보기를 클릭하거나 답안지의 번호를 클릭해 선택합니다",
  "prep.menu_li4": "스크랩한 문항은 현황에서 ★로 표시됩니다",
  "prep.menu_li5": "아래쪽 이전 / 다음 / 제출로 이동·제출합니다",
  "prep.menu_li_choose": "답은 보기를 클릭하거나 답안지의 번호를 클릭해 선택합니다",
  "prep.check_title": "응시 환경 자동 점검",
  "prep.check_ok": "정상",
  "prep.check_no": "확인 필요",
  "prep.chk_seb": "보안 브라우저(SEB)",
  "prep.chk_seb_running": "실행 중",
  "prep.chk_seb_info": "실제 시험은 보안 브라우저로 시작됩니다",
  "prep.sample_title": "모의 문제",
  "prep.sample_note": "아래 보기를 클릭해 답 선택을 연습해 보세요 (채점되지 않습니다)",
  "prep.sample_eg": "예시",
  "prep.sample_q": "다음 중 CARIS 응시 방법으로 올바른 것은?",
  "prep.sample_opt1": "보기를 클릭하거나 답안지 번호를 눌러 답을 고른다",
  "prep.sample_opt2": "휴대폰으로 응시한다",
  "prep.sample_opt3": "화면을 캡처해 저장한다",
  "prep.sample_opt4": "다른 탭을 열어 검색한다",
  "prep.sample_fb_ok": "정답입니다! 실제 시험도 이렇게 답을 선택합니다",
  "prep.sample_fb_no": "연습이니 괜찮아요. 1번이 올바른 방법입니다",
  "prep.sample_practice_btn": "보안 브라우저로 모의 1문제 풀어보기 →",
  "prep.ready_lead": "모든 안내를 확인했습니다. 준비가 되면 시험을 시작하세요",
  "prep.ready_li1": "「시험 시작」을 누르면 곧바로 시험이 시작됩니다",
  "prep.ready_li2": "시작 후에는 제한시간이 즉시 시작되며, 처음부터 다시 시작할 수 없습니다",
  "prep.agree": "위 안내와 유의사항을 모두 확인했으며, 시험에 응시합니다",
  "prep.prev": "이전",
  "prep.next": "다음",
  "prep.starting": "시험 준비 중…",
  "prep.start": "시험 시작",
  "check.title": "시험환경 테스트 (사전 점검)",
  "check.eyebrow": "사전 점검",
  "check.sub": "실제 시험 전에 이 PC에서 보안 브라우저가 제대로 열리는지, 응시 환경이 준비됐는지 미리 확인하세요.",
  "check.sec1_title": "보안 프로그램(Safe Exam Browser) 설치",
  "check.sec1_desc": "시험은 화면 캡처·복사·프로그램 전환을 차단하는 보안 프로그램(Safe Exam Browser) 안에서 진행됩니다.",
  "check.sec1_hint": "위 확인에서 보안 브라우저가 열리지 않았다면 여기서 설치하세요.",
  "check.install_btn": "보안 프로그램(SEB) 설치하기",
  "check.install_note1": "· 설치 시 Windows가 “게시자: ETH Zürich” 로 표시되면 정상입니다.",
  "check.install_note2": "· “Windows가 PC를 보호했습니다” 창이 뜨면 추가 정보 → 실행 을 누르세요. (정상 설치 과정)",
  "check.sec2_title": "응시 환경 점검",
  "check.sec2_desc": "보안 브라우저를 실행하면 아래 항목을 점검합니다.",
  "check.chk_pc": "PC(데스크톱) 환경",
  "check.chk_screen": "화면 크기",
  "check.chk_fs": "전체화면 지원",
  "check.chk_net": "인터넷 연결",
  "check.chk_seb": "보안 브라우저(SEB) 실행",
  "check.monitor_note": "· 모니터 수는 보안 브라우저 실행 시 자동 점검됩니다. 외부 모니터는 1대만 연결하세요.",
  "check.sebtest_btn": "보안 브라우저로 열어서 확인",
  "check.sebtest_desc": "실제 시험과 같은 방식으로 보안 브라우저를 실행해, 이 PC에서 제대로 열리는지 확인합니다.\n시험 문제는 나오지 않습니다.",
  "check.back": "내 응시권으로 돌아가기",
  "done.title": "제출이 완료되었습니다",
  "done.sub1": "응시가 정상적으로 접수되었습니다. 보안 브라우저는 자동으로 종료됩니다.",
  "done.sub2": "채점 결과는 발표일 이후 마이페이지에서 확인할 수 있습니다.",
  "done.home": "홈으로",
  "complete.title": "제출이 완료되었습니다",
  "complete.sub": "응시가 정상적으로 접수되었습니다.\n채점 결과는 발표일 이후 마이페이지에서 확인할 수 있습니다.",
  "complete.voided_title": "응시를 종료했습니다",
  "complete.voided_sub": "이번 응시는 무효 처리되어 채점되지 않습니다.\n다시 응시하려면 처음부터 시작해 주세요.",
  "complete.practice_title": "모의 응시가 끝났습니다",
  "complete.practice_sub": "실제 시험도 이와 동일하게 진행됩니다.\n준비되면 실제 검정에 응시해 보세요.",
  "complete.close_seb": "시험 종료하기",
  "complete.auto_close": "{n}초 후 자동으로 종료됩니다.",
  "complete.to_check": "응시 현황 보기",
  "complete.home": "홈으로",
  "seb.title": "보안 브라우저로 응시하세요",
  "seb.sub": "이 시험은 화면 캡처·복사·다른 프로그램 전환을 차단하는 Safe Exam Browser(SEB)에서만 응시할 수 있습니다.",
  "seb.reqs_title": "✅ 응시 전 확인사항",
  "seb.req_monitor": "모니터는 1대만 연결하세요. 노트북에 외부 모니터를 꽂았다면 분리해야 합니다.",
  "seb.req_install": "Safe Exam Browser가 설치되어 있어야 합니다. (아래 「SEB 설치」)",
  "seb.req_vm": "가상머신(VM)·원격제어(TeamViewer·AnyDesk 등)에서는 응시할 수 없습니다.",
  "seb.req_record": "화면 녹화·캡처 프로그램과 불필요한 앱을 모두 종료하세요.",
  "seb.install": "SEB 설치",
  "seb.start": "보안 브라우저로 시작",
  "seb.start_unset": "보안 브라우저로 시작 (설정 전)",
  "seb.trouble_summary": "시작이 안 되고 영어 오류창이 떠요",
  "seb.err_display": "모니터가 2대 이상 연결되어 있습니다. 하나만 남기고 나머지를 분리한 뒤 다시 시작하세요.",
  "seb.err_vm": "가상머신(VM)에서는 응시할 수 없습니다. 실제 PC에서 실행하세요.",
  "seb.err_process": "차단된 프로그램(원격제어·화면녹화·메신저 등)이 실행 중입니다. 모두 종료한 뒤 다시 시작하세요.",
  "seb.trouble_foot": "그 외 오류가 계속되면 오류창을 캡처해 관리자에게 문의해 주세요.",
  "run.lost_title": "시험 정보를 불러올 수 없습니다",
  "run.lost_sub": "새로고침했거나 잘못된 접근입니다. CARIS 페이지에서 다시 시작해 주세요.",
  "run.to_exam": "CARIS로",
  "run.practice_done": "모의 문제 풀이가 끝났습니다. 실제 시험도 이와 동일하게 작동합니다.",
  "run.submit_fail": "제출에 실패했습니다. 다시 시도해 주세요.",
  "run.unanswered_warn": "아직 답하지 않은 문항이 {n}개 있습니다.\n첫 미응답 문항({first}번)으로 이동합니다.",
  "run.submit_confirm": "답안을 최종 제출하시겠습니까?\n제출 후에는 수정할 수 없습니다.",
  "run.short_placeholder": "여기에 답을 작성하세요.",
  "run.short_hint": "주관식 · 관리자가 검토해 채점합니다",
  "run.short_chars": "자",
  "run.short_label": "주관식",
  "run.short_done": "작성함",
  "run.short_todo": "미작성",
  "run.time_up": "시험 시간이 종료되어 자동 제출됩니다.",
  "run.mask_title": "화면 이탈이 감지되었습니다",
  "run.mask_sub": "시험 화면으로 돌아오세요. 캡처·이탈은 기록됩니다.",
  "run.submit": "제출",
  "run.top_title": "{title} 문제풀이",
  "run.q_badge": "객",
  "run.timer_title": "남은 시간",
  "run.progress_title": "진행 상황 (푼 문항/전체)",
  "run.minutes": "{m}분",
  "run.font_size": "글자 크기",
  "run.tab_canvas": "캔버스",
  "run.tab_sheet": "답안지",
  "run.tab_status": "문제풀이 현황",
  "run.completed": "작성 완료",
  "run.written": "작성",
  "run.legend_done": "완료",
  "run.legend_undone": "미완료",
  "run.legend_current": "현재 문항",
  "run.canvas_note": "계산·메모용 (제출되지 않음)",
  "run.canvas_placeholder": "이곳에 자유롭게 메모하세요. 제출 답안에는 포함되지 않습니다.",
  "run.prev": "이전",
  "run.next": "다음",
  "run.submitting": "제출 중…",
  "run.quit": "종료",
  "run.quit_title": "시험을 포기하시겠습니까?",
  "run.quit_confirm": "지금 종료하면 이번 응시는 무효 처리되어 채점되지 않습니다.\n다시 응시하려면 처음부터 시작해야 합니다.",
  "run.quit_yes": "포기하고 종료",
  "run.quit_no": "계속 응시",
  "result.voided_title": "응시가 무효 처리되었습니다",
  "result.voided_sub": "관리자에게 문의해 주세요.",
  "result.home": "홈으로",
  "result.load_failed_title": "결과를 불러올 수 없습니다",
  "result.submitted_title": "제출이 완료되었습니다",
  "result.submitted_sub": "총 {n}문항 응시 답안이 정상 접수되었습니다.",
  "result.submitted_at": "제출 일시",
  "result.release_at": "채점 결과 공개",
  "result.release_note_pre": "채점 결과는 ",
  "result.release_days": "{d}일 후",
  "result.release_note_post": " 이 화면에서 확인할 수 있습니다.",
  "result.graded_title": "채점 결과",
  "result.submitted_prefix": "제출",
  "result.pass": "합 격",
  "result.fail": "불합격",
  "result.pass_criteria": "합격 기준 — 전체 문항의 60% 이상 정답",
  "result.issue_cert": "📜 인증서 발급 (PDF)",
  "result.back": "← 뒤로",
  "exresult.pass_badge": "축하합니다! 합격입니다",
  "exresult.fail_badge": "아쉽지만 이번엔 불합격입니다",
  "exresult.score_unit": "취득 점수",
  "exresult.earned_grade": "취득 자격",
  "exresult.correct_count": "정답 문항",
  "exresult.cert_fallback": "CARIS",
  "exresult.info_pass": "해당 자격이 인증하는 역량을 취득했습니다",
  "exresult.info_fail": "합격 기준은 60점 이상입니다",
  "exresult.subject_title": "검정 과목별 성취도",
  "exresult.subject_n": "과목 {n}",
  "exresult.correct_suffix": "정답",
  // 누르면 바로 PDF 가 나오는 게 아니라 결제 유도 화면으로 간다 → '(PDF)' 대신 '발급 신청'
  "exresult.issue_cert": "인증서 발급 신청",
  "exresult.to_attempts": "← 내 응시 현황",
  "my.status.in_progress": "응시 중",
  "my.status.submitted": "제출 완료",
  "my.status.voided": "무효",
  "my.status.expired": "만료",
  "my.tab.attempts": "시험 응시 현황",
  "my.tab.earned": "자격 취득 현황",
  "my.tab.issuance": "인증서 발급 현황",
  "my.load_failed": "내역을 불러올 수 없습니다.",
  "my.login_required": "로그인이 필요합니다",
  "my.login_required_sub": "마이페이지는 로그인 후 이용할 수 있습니다.",
  "my.title": "마이페이지",
  "my.eyebrow": "내 CARIS",
  "my.greeting": "{name} 님",
  "my.empty_attempts": "아직 응시 내역이 없습니다.",
  "my.take_exam": "CARIS 응시하기",
  "my.submitted_prefix": "제출",
  "my.not_submitted": "제출되지 않은 응시입니다.",
  "my.grading_pre": "채점 중 · ",
  "my.grading_days": "{d}일 후",
  "my.grading_post": "({date}) 발표",
  "my.released": "결과가 발표되었습니다. 성적을 확인하세요.",
  "my.view_score": "성적 확인",
  "my.empty_earned": "취득한 자격이 없습니다.",
  "my.earned_badge": "취득",
  "my.earned_meta": "취득일 {date} · 자격번호 {no} · 점수 {correct}/{total}",
  "my.empty_issuance": "발급 가능한 인증서가 없습니다.",
  "my.cert_no": "자격번호 {no}",
  "my.issued": "발급 완료",
  "my.not_issued": "미발급",
  "my.reissue": "다시 발급",
  "my.issue": "인증서 발급",
  "cert.alt": "인증서",
  "cert.print": "📄 PDF로 저장 / 인쇄",
  "cert.back": "← 뒤로",
  // 발급(결제) 전 = 결제 유도 화면. 증서는 이 화면에서 일절 노출하지 않는다.
  // ⚠️ 한국어 표기는 화면 전체가 '인증서'로 통일됐다(2026-08-04). '자격증'으로 되돌리지 말 것.
  //    단 '자격번호'(cert_no)는 법정 서식 명칭이라 그대로 둔다 — 인증번호로 바꾸지 말 것.
  //    en/zh/hi/vi 는 원래 중립어(certificate)라 그대로, ja(資格証)도 지시 범위 밖이라 손대지 않았다.
  "cert.gate_title": "{grade} 인증서",
  "cert.gate_lead": "합격이 확인되었습니다. 인증서는 발급(결제)을 완료한 뒤 열람할 수 있습니다.",
  "cert.gate_acquired": "취득일",
  "cert.gate_perk_pdf": "인증서 원본 열람 · PDF 저장 · 인쇄",
  "cert.gate_perk_qr": "QR 진위확인 활성화 — 제3자가 온라인으로 검증",
  "cert.gate_perk_no": "자격번호 전체 공개 · 발급 기록 등록",
  "cert.gate_paid_note": "인증서 발급은 유료 서비스입니다.",
  // 디자인 견본(/certificate/sample) — 더미 인물 + 진한 워터마크
  "cert.sample_badge": "견본",
  "cert.sample_note": "인증서 디자인 견본입니다. 기재된 이름·자격번호는 예시이며, 발급하면 본인 정보와 진위확인 QR 이 들어간 원본을 받습니다.",
  "cert.sample_wm": "견본 · SAMPLE",
  "cert.sample_wm_sub": "발급 전 · 무단사용 금지",
  "cert.sample_cta": "인증서 발급 신청",
  "cert.qr_locked": "발급 후 활성화",
  // 영문 성명 — 신규 시안이 영문 서식이라 증서에 각인되는 유일한 이름. 발급 신청 때 받는다.
  // ⚠️ 입력은 성·이름 두 칸(화면 순서 = 성 → 이름)인데 증서 각인은 "이름 성" 순이다.
  //    두 순서가 다르므로 hint 가 각인 순서를 반드시 말해줘야 한다.
  "cert.roman_last_label": "영문 성 (Family name)",
  "cert.roman_first_label": "영문 이름 (Given name)",
  "cert.roman_last_ph": "예: Ahn",
  "cert.roman_first_ph": "예: Hyeongjun",
  "cert.roman_hint": "여권 표기와 동일하게 입력해 주세요. 인증서에는 «이름 성» 순서로 새겨지며, 발급 후에는 수정할 수 없습니다.",
  // 각인 확인 단계 — 이름은 발급 후 수정 불가라 결제 버튼과 실제 발급 사이에 한 번 보여준다.
  "cert.confirm_title": "이 이름으로 새겨집니다",
  "cert.confirm_note": "발급 후에는 수정할 수 없습니다. 여권 표기와 같은지, 성과 이름을 바꿔 적지는 않았는지 확인해 주세요.",
  "cert.confirm_ok": "이 이름으로 발급",
  "cert.confirm_edit": "수정하기",
  "cert.roman_invalid": "영문 성명을 로마자로 입력해 주세요(영문·공백·하이픈만).",
  // ⚠️ 증서 안에 각인되는 글자는 **6개국어 모두 영문 고정**이다(2026-08-26 지시).
  //    자격증 서식(cert-template-v2.webp)이 영문 한 벌뿐이라 화면 언어를 따라가면 영문 증서에
  //    한글·중국어 캡션만 섞여 박힌다. 번역하지 말 것.
  "cert.qr_caption": "Verify authenticity",
  "cert.gate_pay": "결제하고 발급받기",
  "cert.gate_later": "나중에 하기",
  "cert.issuing": "발급 중…",
  "cert.issue_failed": "발급에 실패했습니다. 잠시 후 다시 시도해 주세요.",
  "cert.issue_no_attempt": "발급할 응시 기록이 없습니다. 마이페이지에서 다시 시도해 주세요.",
  "verify.title": "인증서 진위확인",
  "verify.loading": "확인 중…",
  "verify.valid_badge": "유효한 인증서",
  "verify.expired_badge": "유효기간 만료",
  "verify.invalid_badge": "확인되지 않음",
  "verify.invalid_desc": "해당 인증서의 발급 기록을 찾을 수 없습니다. QR 코드 또는 링크를 다시 확인해 주세요.",
  "verify.name": "성명",
  "verify.grade": "자격명",
  "verify.cert_no": "자격번호",
  "verify.issued_at": "발급일",
  "verify.expires_at": "유효기간",
  "verify.no_expiry": "무기한",
  "verify.status": "상태",
  "verify.status_valid": "유효",
  "verify.status_expired": "만료",
  "verify.system_sub": "자격 진위확인 시스템",
  "verify.official_body": "공인 AI·로봇 자격 검정기관",
  "verify.headline_valid": "유효한 인증서입니다",
  "verify.headline_expired": "유효기간이 만료된 인증서입니다",
  "verify.headline_invalid": "확인되지 않는 인증서입니다",
  "verify.status_invalid": "무효",
  "verify.record_title": "자격 정보",
  "verify.trust": "본 결과는 글로벌 AI·로봇 협회 공식 자격 데이터베이스를 실시간 조회한 것입니다.",
  "verify.checked_at": "조회 시각",
  "guide.title": "CARIS 안내",
  "guide.lead": "글로벌 AI·로봇 협회가 시행하는 공인 CBT 시험 CARIS입니다. AI 활용 능력을 객관적으로 평가합니다.",
  "guide.areas.title": "평가 영역",
  "guide.areas.1.h": "AI 활용 · 기초",
  "guide.areas.1.d": "AI 개념과 활용 전반",
  "guide.areas.2.h": "데이터 · 전처리",
  "guide.areas.2.d": "데이터 이해와 가공",
  "guide.areas.3.h": "모델 · 학습",
  "guide.areas.3.d": "모델 원리와 학습 과정",
  "guide.areas.4.h": "윤리 · 보안",
  "guide.areas.4.d": "AI 윤리와 데이터 보안",
  "guide.areas.5.h": "실무 · 적용",
  "guide.areas.5.d": "현업 적용 사례",
  "guide.exam.title": "시험 구성",
  "guide.exam.count.label": "문항 수:",
  "guide.exam.count.value": "{n}문항",
  "guide.exam.count.note": "(4지선다 객관식)",
  "guide.exam.time.label": "시험 시간:",
  "guide.exam.time.value": "{n}분",
  "guide.exam.pass.label": "합격 기준:",
  "guide.exam.pass.value": "전체 문항의 60% 이상",
  "guide.exam.pass.note": "정답",
  "guide.exam.result.label": "결과 발표:",
  "guide.exam.result.pre": "제출",
  "guide.exam.result.value": "{n}일 후",
  "guide.exam.result.note": "마이페이지에서 확인",
  "guide.how.title": "응시 방법",
  "guide.how.1.h": "PC(데스크톱·노트북) 전용",
  "guide.how.1.d": "모바일·태블릿 불가",
  "guide.how.2.pre": "화면 캡처·복사·이탈을 차단하는",
  "guide.how.2.h": "보안 브라우저(SEB)",
  "guide.how.2.post": "로 응시",
  "guide.how.3.pre": "응시 전",
  "guide.how.3.h": "시험환경 테스트",
  "guide.how.3.post": "로 설치·환경을 미리 점검할 수 있습니다",
  "guide.cta.take": "CARIS 응시하기 →",
  "guide.cta.check": "시험환경 테스트",
  "guide.eyebrow.intro": "한눈에 보기",
  "guide.eyebrow.exam": "시험 개요",
  "guide.eyebrow.areas": "평가 기준",
  "guide.eyebrow.how": "응시 안내",
  "guide.eyebrow.next": "다음 안내",
  "guide.next.title": "다음 단계",
  "guide.next.score.d": "응시 후 결과와 합격 여부를 마이페이지에서 확인하세요.",
  "guide.next.notice.d": "시험 운영과 응시 환경에 대한 최신 공지를 확인하세요.",
  "guide.next.about.d": "CARIS를 시행하는 협회와 그 활동을 알아보세요.",
  "guide.callout.eyebrow": "왜 GARA인가",
  "guide.callout.title": "누구나, 무료로, 6개국어로 증명합니다",
  "guide.callout.desc": "별도 비용과 일정 없이, PC 보안 환경에서 공정하게 AI 활용 능력을 검증합니다.",
  "guide.callout.v1": "상시 응시",
  "guide.callout.v1d": "정해진 회차 없이 원하는 때 응시",
  "guide.callout.v2": "무료 응시",
  "guide.callout.v2d": "응시·채점·인증서 발급까지 무료",
  "guide.callout.v3": "6개국어 지원",
  "guide.callout.v3d": "한국어·영어·일본어·중국어·힌디어·베트남어",
  "guide.callout.v4": "PC 보안 응시",
  "guide.callout.v4d": "보안 브라우저(SEB)로 공정하게 응시",
  "header.exam": "시험 응시",
  "header.score": "성적 확인",
  "header.support": "고객지원",
  "header.nav": "주요 메뉴",
  "footer.quick": "바로가기",
  "footer.blurb": "CARIS로 AI·로봇 실력을 객관적으로 증명하세요. 상시·무료·6개국어로 제공됩니다.",
  "footer.rights": "© 2026 GARA. All rights reserved.",
  "login.welcome": "환영합니다",
  "login.subtitle": "GARA 서비스를 이용하려면 로그인하세요.",
  "login.google_title": "구글로 계속하기",
  "login.kakao_title": "카카오로 계속하기",
  "fab.login_cta": "로그인",
  "about.hero_line1": "글로벌 AI 로봇협회",
  "about.hero_line2": "AI & Robot 시대 인류가 변화에 적응하고 성장하도록 돕는 기관입니다.",
  "about.subtitle": "초격차 기술 시대를 선도할 글로벌 표준 자격\nGARA와 함께 당신의 전문성을 증명하고 미래 산업의 핵심 인재로 도약하세요",
  "about.cta_exam": "CARIS 응시하기",
  "about.cta_brochure": "협회 소개서 다운로드",
  // 히어로 로고 락업의 부제(큰 글씨 'CARIS' 는 브랜드명이라 번역하지 않는다).
  //   hero_title_l1/l2 는 락업 이전의 2줄 제목 — 현재 미사용이나 되돌릴 수 있게 남겨둔다.
  "guide.hero_lockup_sub": "AI・Robot 융합역량 자격시험",
  "guide.hero_title_l1": "전세계 AI·Robot",
  "guide.hero_title_l2": "융합역량 자격시험",
  "guide.hero_subtitle": "GARA는 실무 중심의 생성형 AI 활용 능력을 객관적인 지표로 평가하는 국제 표준 자격입니다. 5가지 핵심 영역을 통해 당신의 완벽한 AI 경쟁력을 증명하세요.",
  "guide.btn_apply": "시험 접수하기",
  "guide.btn_mock": "모의 테스트",
  // 브랜드 고유명 — 티어 이름처럼 전 언어 동일 표기.
  "guide.schedule_title": "CARIS Plan",
  "guide.status_open": "접수중",
  "guide.status_upcoming": "예정",
  "guide.status_closed": "마감",
  "sched.rolling_badge": "상시 접수",
  "sched.prev": "이전",
  "sched.next": "다음",
  "guide.areas_title": "5대 평가 영역",
  "guide.areas_subtitle": "GARA는 AI 기술의 단순 이해를 넘어, 실제 업무 환경에서의 활용 능력을 종합적이고 체계적으로 평가합니다.",
  "guide.area1_title": "AI 활용·기초",
  "guide.area1_desc": "프롬프트 엔지니어링의 기본 원리와 생성형 AI 도구의 특성 이해 및 기본 조작 능력을 평가합니다.",
  "guide.area2_title": "데이터·전처리",
  "guide.area2_desc": "AI 모델 학습 및 결과물 도출을 위한 데이터 수집, 정제, 가공 등 전처리 과정의 이해도를 평가합니다.",
  "guide.area3_title": "모델·학습",
  "guide.area3_desc": "다양한 AI 모델의 특성을 파악하고, 목적에 맞는 모델 선택 및 미세조정(Fine-tuning) 개념을 평가합니다.",
  "guide.area4_title": "윤리·보안",
  "guide.area4_desc": "AI 활용 시 발생할 수 있는 저작권, 개인정보보호, 편향성 문제 등 윤리적 가이드라인 준수 여부를 평가합니다.",
  "guide.area5_title": "실무·적용",
  "guide.area5_desc": "텍스트, 이미지, 코딩 등 다양한 비즈니스 상황에서 AI 도구를 활용하여 실제 결과물을 효율적으로 도출하는 종합 문제 해결 능력을 중점적으로 평가합니다.",
  "guide.methods_title": "응시 방법",
  "guide.methods_subtitle": "CARIS는 공정하고 확실한 환경에서 진행됩니다.",
  "guide.method1_title": "PC(데스크톱·노트북) 전용",
  "guide.method1_desc": "안정적인 검정을 위해 모바일·태블릿 기기에서는 응시가 불가능합니다.",
  "guide.method2_title": "보안 브라우저(SEB)",
  "guide.method2_desc": "화면 캡처 및 이탈을 원천 차단하는 전용 보안 브라우저를 통해 평가의 신뢰도를 보장합니다.",
  "guide.method3_title": "시험환경 테스트",
  "guide.method3_desc": "응시 전 반드시 환경 테스트를 거쳐 최적의 시스템 상태를 점검하시기 바랍니다.",
  "notice.hero_sub": "CARIS의 최신 소식, 시험 안내 및 중요 공지를 확인하세요.",
  "notice.filter_all": "전체",
  "notice.tag_notice": "공지",
  "notice.tag_guide": "안내",
  "notice.tag_required": "필독",
  "notice.empty": "‘{filter}’ 카테고리의 공지가 없습니다.",
  "notice.more": "더보기",
  "notice.read_more": "자세히 보기",
  "notice.back_list": "목록으로",
  "notice.not_found": "공지를 찾을 수 없습니다.",
  "faq.eyebrow2": "고객센터",
  "faq.hero_title": "무엇을",
  "faq.hero_title_em": "도와드릴까요?",
  "faq.hero_sub": "글로벌 AI 및 로봇 공학 인증서, 시험 일정 및 자격 검증 프로세스에 대한 포괄적인 가이드와 답변을 찾아보세요.",
  "faq.search_ph": "질문 검색...",
  "faq.search_go": "검색",
  "faq.card_schedule_title": "CARIS PLAN",
  "faq.card_schedule_desc": "다가오는 CARIS 시험 날짜 및 일정을 확인하세요.",
  "faq.card_verify_title": "자격 검증",
  "faq.card_verify_desc": "마이페이지에서 취득한 자격과 인증서를 확인하세요.",
  "faq.categories": "카테고리",
  "faq.help_title": "궁금증이 풀리지 않았나요?",
  "faq.help_body": "1:1 문의를 남기시면 확인 후 답변드려요.",
  "faq.help_link": "1:1 문의하기",
  "faq.search_results": "검색 결과",
  "faq.searching_sub": "‘{query}’ 관련 문항입니다.",
  "faq.no_results": "‘{query}’에 대한 검색 결과가 없습니다.",
  "faq.cat_empty": "이 카테고리의 문의는 준비 중입니다.",
  "faq.q1.tag": "응시 환경",
  "faq.q2.tag": "보안 브라우저",
  "faq.q3.tag": "결과",
  "faq.q4.tag": "채점",
  "faq.q5.tag": "재응시",
  "faq.q6.tag": "인증서",
  "faq.q7.tag": "응시 중",
  "mypage.tab_attempts": "시험 응시 현황",
  "mypage.tab_earned": "자격 취득 현황",
  "mypage.tab_issuance": "인증서 발급 현황",
  "mypage.tab_inquiry": "1:1 문의",
  "mypage.default_name": "응시자",
  "mypage.exam_fallback": "CARIS",
  "mypage.login_required": "로그인이 필요합니다",
  "mypage.login_desc": "마이페이지는 로그인 후 이용할 수 있습니다.",
  "mypage.login_google": "구글로 로그인",
  "mypage.login_kakao": "카카오로 로그인",
  "mypage.title": "마이페이지",
  "mypage.greeting_hello": "안녕하세요, ",
  "mypage.greeting_name": "{name} 님",
  "mypage.greeting_tail": ". CARIS 현황을 확인하세요.",
  "mypage.empty_attempts": "아직 응시 내역이 없습니다.",
  "mypage.go_exam": "CARIS 응시하기",
  "mypage.cta_sub": "CARIS 공식 응시 페이지로 이동합니다.",
  "mypage.online": "온라인",
  "mypage.grading": "채점 중입니다. 결과는 약 {days}일 후 발표됩니다.",
  "mypage.expired": "응시 기간 만료",
  "mypage.view_score": "성적 확인",
  "mypage.empty_earned": "아직 취득한 자격이 없습니다.",
  "mypage.passed": "합격",
  // WORLD ARENA 레벨 인증서 — 레벨테스트에서 승급할 때마다 한 장씩 쌓인다(자격 취득 현황 탭)
  "mypage.cert_no": "인증번호",
  "mypage.empty_issuance": "발급 가능한 인증서가 없습니다.",
  // ⚠️ 이 탭에는 이제 **강의도 들어간다**(2026-08-25) — 'E-BOOK 서재' 라고 부르면 강의가 없는 것처럼 읽힌다.
  //    URL(/mypage/ebooks)은 그대로다(북마크·링크가 이미 나가 있다).
  "mypage.tab_ebooks": "내 서재",
  "mypage.empty_ebooks": "아직 구매한 E-Book·강의가 없습니다.",
  // 메인 3번째 CTA(landing.cta_learn)와 같은 이름. 브랜드 라벨이라 6개국어 동일 표기.
  "ebook.store_title": "Learning Library",
  // 안내에 쓰는 '서재' 이름은 실제 마이페이지 탭 라벨(mypage.tab_ebooks = 내 서재)과 같아야 한다.
  "ebook.store_sub": "구매한 책은 마이페이지 › 내 서재에서 읽을 수 있습니다.",
  "ebook.empty_store": "등록된 이북이 없습니다.",
  "ebook.buy": "구매하기",
  "ebook.get_free": "무료로 담기",
  "ebook.free": "무료",
  "ebook.owned": "보유 중",
  "ebook.read": "읽기",
  "ebook.view": "보러가기",
  "ebook.cover_zoom": "표지 크게 보기",
  "ebook.processing": "처리 중…",
  "ebook.bought": "구매 완료 — 내 서재에 담겼습니다.",
  "ebook.login_to_buy": "로그인 후 구매할 수 있습니다.",
  // 비로그인이 구매 버튼을 눌렀을 때 뜨는 로그인 모달(제목 한 줄 + 버튼만 — 책 정보·설명은 넣지 않는다)
  "ebook.login_modal_title": "로그인이 필요합니다",
  "ebook.go_store": "Learning Library 가기",
  "ebook.go_library": "내 서재에서 보기",
  "ebook.load_failed": "이북을 불러올 수 없습니다.",

  // ---- 결제(/checkout · /pay/success · /pay/fail) ----
  // ⚠️ 통화는 화면 언어와 무관하게 **원(KRW)** 이다. 금액 문자열은 여기 넣지 말고 lib/money.ts 의 krw() 로 찍을 것.
  "pay.title": "결제",
  "pay.back": "돌아가기",
  // 비로그인으로 결제 화면에 들어왔을 때. ⚠️ 조용히 /login 으로 튕기지 말 것 — 로그인해야 한다는 걸
  //    화면에서 말해줘야 한다(2026-08-24 지시). 설명문(`pay.login_sub`)은 2026-08-26 지시로 삭제.
  "pay.login_title": "로그인이 필요해요",
  "pay.order": "주문 내역",
  "pay.preparing": "결제창을 준비하고 있어요…",
  "pay.pay_button": "결제하기",
  "pay.moving": "결제창으로 이동 중…",
  "pay.reopen": "결제창 다시 열기",
  "pay.reopen_hint": "결제창을 닫으셨나요? 아직 결제되지 않았어요 — 위 버튼으로 다시 열 수 있습니다.",
  // 테스트 키로 붙어 있을 때만 뜬다 — 실키와 헷갈리면 안 되므로 문구를 부드럽게 쓰지 않는다.
  "pay.test_mode": "테스트 결제 환경입니다 — 실제로 결제되지 않습니다.",
  "pay.not_configured": "결제가 아직 준비되지 않았습니다. 잠시 후 다시 시도해주세요.",
  "pay.bad_request": "결제 정보가 올바르지 않습니다.",
  "pay.error_generic": "결제를 진행할 수 없습니다.",
  "pay.confirming": "결제를 확인하고 있어요",
  "pay.confirming_body": "창을 닫지 말고 잠시만 기다려주세요.",
  "pay.success_title": "결제가 완료됐어요",
  "pay.free_title": "담았어요",
  "pay.free_body": "무료 자료라 바로 서재에 담겼어요.",
  "pay.free_title_exam": "응시권이 발급됐어요",
  "pay.free_body_exam": "무료 급수라 결제 없이 바로 발급됐어요.",
  // 가상계좌 — 계좌만 발급된 상태다. 여기서 '완료'라고 하면 안 된다(입금 전이라 지급도 안 됐다).
  "pay.waiting_title": "입금을 기다리고 있어요",
  // 결제는 성공했는데 지급이 보류된 상태(paid + fulfilled_at=null). **실패 문구를 쓰면 안 된다** — 돈은 이미 빠졌다.
  // 실패로 읽히면 사용자가 다시 결제하려다 '이미 결제 완료'를 보고 두 화면이 정반대로 말하게 된다.
  "pay.hold_title": "결제는 완료됐어요",
  "pay.hold_body": "다만 지급 처리가 보류됐어요. 운영팀이 확인 후 처리해 드립니다 — 다시 결제하지 마세요.",
  "pay.waiting_body": "발급된 가상계좌로 입금하면 자동으로 지급됩니다.",
  "pay.fail_title": "결제하지 못했어요",
  "pay.fail_body": "결제가 취소되었거나 승인되지 않았습니다.",
  "pay.retry": "다시 시도",
  "ebook.reader_back": "내 서재",
  "ebook.reader_lang": "읽을 언어",
  "ebook.reader_fs": "전체화면",
  // 러닝 라이브러리(/ebooks) — 레벨 | 교재 | 강의 3열. 레벨 이름·설명은 lv.N.name / lv.N.desc 를 그대로 쓴다.
  //   ⚠️ "레벨을 고르면 교재와 강의가 나타납니다" 같은 사용법 설명문은 넣지 않는다 — 화면을 보면 아는 것이다(2026-08-06 삭제).
  //   카탈로그 이름(LEVELTEST / CARIS)은 여기 없다 — 급수 이름(Beginner…)처럼 브랜드
  //   고유명이라 언어 무관 영문 고정이고, 단일 출처는 Ebooks.tsx 의 CATALOG_LABEL 이다.
  "ll.catalog": "교재 종류",
  "ll.level_col": "레벨",
  "ll.tier_col": "급수",
  // ⚠️ 'E-Book' 은 카탈로그 이름(LEVELTEST·CARIS)과 같은 **브랜드 표기라 6개국어 모두 같은 글자**다
  //    (2026-08-25 지시로 '교재' 에서 바뀌었다). 언어별로 번역하면 화면마다 다른 이름이 된다.
  "ll.books": "E-Book",
  "ll.lectures": "강의",
  "ll.no_books": "이 레벨의 E-Book 은 준비 중입니다.",
  "ll.no_lectures": "이 레벨의 강의는 준비 중입니다.",
  "ll.no_books_tier": "이 급수의 E-Book 은 준비 중입니다.",
  "ll.no_lectures_tier": "이 급수의 강의는 준비 중입니다.",
  "ll.any_level": "레벨 무관",
  "ll.any_level_desc": "레벨과 상관없이 볼 수 있는 자료입니다.",
  "ll.any_tier": "급수 무관",
  "ll.any_tier_desc": "급수와 상관없이 볼 수 있는 자료입니다.",
  "ll.play": "재생",
  // 페이지 넘김(한 페이지에 한 개). 화면엔 ‹ 1 / 3 › 만 보이고 이 문구는 읽어주는 이름표다.
  "ll.prev": "이전",
  "ll.next": "다음",
  // 강의 시청(2026-08-25 유료화) — 산 사람에게만 보인다. 옛 'll.watch_yt'(유튜브에서 보기)와
  //   'll.demo_note'(데모 안내)는 삭제됐다: 돈 받고 파는 물건 옆에 무료로 가는 길을 둘 수 없다.
  "ll.watch": "시청하기",
  "ll.playing": "재생 중",
  "ll.empty_owned": "이 칸에는 구매한 자료가 없습니다.",
  // 전체구매(2026-08-19) — 왼쪽 열 맨 위 칸. {n} = 할인율(BUNDLE_OFF_PCT).
  "ll.bundle": "전체구매",
  "ll.bundle_desc": "E-Book 과 강의를 골라 한 번에 담을 수 있습니다.",
  "ll.bundle_hint": "{c}개 전부 담으면 {n}% 할인",
  "ll.bundle_on": "{c}개 전부 · {n}% 할인 적용",
  "ll.pick": "선택",
  "ll.picked": "선택됨",
  "ll.pick_all": "전체 선택",
  "ll.pick_none": "선택 해제",
  "ll.pick_count": "{n}개 선택",
  "ll.pick_of": "{a} / {b}개 선택",
  "ll.total": "합계",
  "ll.bundle_buy": "선택 항목 구매",
  "ll.bundle_empty": "담을 수 있는 항목이 아직 없습니다.",
  "mypage.reissue": "재발급",
  "mypage.issue": "발급 신청",
  "mypage.view_sample": "견본 보기",
  "mypage.sample_title": "인증서 견본",
  "mypage.sample_desc": "발급되는 인증서가 어떻게 생겼는지 미리 확인하세요.",
  "gate.btn_check": "시험환경 테스트",
  "gate.login_required": "응시하려면 구글 로그인이 필요합니다. (비로그인 시 자동 안내)",
  "gate.format_value": "지선다형 객관식",
  "gate.instr_result_h": "결과 발표 ({d}일 후)",
  "gate.instr_result_d": "시험 종료 후 {d}일 이내에 개별 통보됩니다.",
  "gate.instr_security_h": "보안 규정 (캡처 금지)",
  "gate.instr_security_d": "시험 중 화면 캡처 및 외부 기기 사용이 엄격히 금지됩니다.",
  "gate.instr_pc_h": "환경 요구사항 (PC 전용)",
  "gate.instr_pc_d": "원활한 진행을 위해 반드시 데스크톱 환경에서 응시해 주십시오.",
  "mobile.title": "PC에서만 응시할 수 있습니다",
  "mobile.desc": "CARIS는 보안·화면 구성을 위해 데스크톱/노트북에서만 응시할 수 있습니다. 모바일·태블릿에서는 시험을 시작할 수 없습니다.",
  "mobile.home": "홈으로",
  "run.question": "문항",
  "notice.title": "공지사항",
  "notice.eyebrow": "공지 · 안내",
  "notice.lead": "CARIS의 최신 소식과 중요 공지를 확인하세요.",
  "notice.cat.notice": "공지",
  "notice.cat.guide": "안내",
  "notice.cat.required": "필독",
  "notice.item1.title": "CARIS 정식 오픈 안내",
  "notice.item1.body": "AI 활용 능력을 평가하는 CARIS가 정식 오픈되었습니다. PC에서 보안 브라우저(SEB)로 응시할 수 있습니다.",
  "notice.item2.title": "보안 브라우저(SEB) 응시 안내",
  "notice.item2.body": "본 시험은 화면 캡처·복사·이탈을 차단하는 Safe Exam Browser에서만 응시할 수 있습니다. 응시 전 「시험환경 테스트」에서 설치·환경을 미리 점검해 주세요.",
  "notice.item3.title": "부정행위 예방 안내",
  "notice.item3.body": "시험 중 화면 캡처·복사·다른 창 이탈은 차단·기록됩니다. 부정행위가 확인되면 응시가 무효 처리될 수 있으니 유의해 주세요.",
  "faq.title": "자주 하는 질문",
  "faq.eyebrow": "도움말 · FAQ",
  "faq.lead": "응시 전 자주 묻는 질문을 모았습니다. 찾는 답이 없으면 공지사항을 확인해 주세요.",
  "faq.q1.q": "모바일이나 태블릿으로 응시할 수 있나요?",
  "faq.q1.a": "아니요. CARIS는 PC(데스크톱·노트북) 전용입니다. 모바일·태블릿에서는 응시할 수 없습니다.",
  "faq.q2.q": "보안 브라우저(SEB)가 무엇인가요?",
  "faq.q2.a": "시험 중 화면 캡처·복사·다른 프로그램 전환을 차단하는 공식 시험 보안 프로그램입니다. 응시 시작 시 안내에 따라 한 번 설치하면 됩니다.",
  "faq.q3.q": "시험 결과는 언제 나오나요?",
  "faq.q3.a": "제출 후 1주일 뒤 마이페이지 「성적 확인」에서 합격 여부와 점수를 확인할 수 있습니다.",
  "faq.q4.q": "합격 기준은 어떻게 되나요?",
  "faq.q4.a": "전체 문항의 60% 이상을 맞히면 합격입니다.",
  "faq.q5.q": "재응시할 수 있나요?",
  "faq.q5.a": "CARIS는 한 회차에 1회만 응시할 수 있으며, 제출한 뒤에는 같은 회차를 다시 응시할 수 없습니다. 다음 회차에는 다시 응시하실 수 있습니다.",
  "faq.q6.q": "인증서는 어떻게 받나요?",
  "faq.q6.a": "합격하면 마이페이지 「인증서 발급 현황」 또는 성적 확인 화면에서 인증서를 PDF로 발급·출력할 수 있습니다.",
  "faq.q7.q": "시험 중 안 푼 문항이 있으면 어떻게 되나요?",
  "faq.q7.a": "안 푼 문항이 있으면 제출되지 않으며, 경고 후 미응답 문항으로 이동합니다. 제한시간이 끝나면 자동으로 제출됩니다.",
  "nav.exam": "CARIS",
  "nav.guide": "CARIS 안내",
  "nav.caris": "CARIS",
  // FAB 네비 전용 라벨 — 옆의 WORLD ARENA·CARIS 와 맞춰 전 언어 영문 대문자 고정.
  //   (본문에서 쓰는 common.home · ebook.store_title 은 현지화 그대로 둔다)
  "fab.home": "HOME",
  "nav.apply": "CARIS 접수",
  "nav.mypage": "마이페이지",
  "nav.certpreview": "인증서 미리보기",
  "nav.certgatepreview": "인증서 결제 유도 화면",
  "nav.notice": "공지사항",
  "nav.faq": "자주 하는 질문",
  "nav.support": "고객센터",
  "fab.dark": "다크 모드",
  "fab.light": "라이트 모드",
  "nav.assoc": "협회 소개",
  "fab.login": "구글로 로그인",
  "fab.loginhint": "로그인하면 응시할 수 있어요",
  "fab.morebtn": "더보기",
  "fab.changeChar": "캐릭터 변경",
  "fab.editName": "이름 변경",
  "fab.logout": "로그아웃",
  "fab.uploadImg": "이미지 업로드",
  "fab.uploadFail": "업로드에 실패했습니다.",
  "fab.toTop": "맨 위로",
  // FAB 의 빨간 점(1:1 문의 새 답변) 안내 — 점 자체는 aria-hidden 이라 이 문구가 유일한 설명이다.
  "fab.newanswer": "문의에 새 답변이 있습니다",
  // ── 의견함(/feedback) — FAB 패널의 빨간 항목. 1:1 문의와 달리 답변이 없다(수집 전용). ──
  "fab.feedback": "의견 보내기",
  "feedback.title": "의견 보내기",
  "feedback.sub": "홈페이지 오픈을 앞두고 구성원 여러분의 소중한 의견을 듣고자 합니다.\n이용하시면서 불편했던 점, 또는 추가되었으면 하는 아이디어를 자유롭게 남겨주세요.\n보내주신 모든 피드백에 개별 답변을 드리기는 어렵지만, 담당 팀에서 빠짐없이 검토하여 더 나은 서비스를 만드는 데 적극 반영하겠습니다.",
  "feedback.f_org": "소속",
  "feedback.f_name": "이름",
  "feedback.f_path": "경로",
  "feedback.f_body": "내용",
  "feedback.ph_org": "예: 전략기획실",
  "feedback.ph_name": "예: 최원석",
  "feedback.ph_path": "예: https://gara-cbt.airobotassn.workers.dev/hub",
  "feedback.ph_body": "예: 배경 색상이 좀더 진했으면 좋겠습니다.",
  "feedback.hint_path": "의견이 해당하는 화면이나 메뉴를 적어주세요.",
  "feedback.f_files": "파일 첨부 (선택)",
  "feedback.files_drop": "여기로 파일을 끌어다 놓거나, 캡처를 붙여넣기(Ctrl+V) 하세요.",
  "feedback.files_pick": "파일 선택",
  "feedback.files_hint": "최대 3개 · 파일당 20MB. 이미지 · PDF · PPT · 워드 · 엑셀 · 한글 · 화면 녹화 · ZIP 을 올릴 수 있습니다.",
  "feedback.files_up": "올리는 중…",
  "feedback.files_remove": "첨부 빼기",
  "feedback.err_file_type": "이 형식은 올릴 수 없습니다.",
  "feedback.err_file_size": "파일 하나가 20MB를 넘습니다.",
  "feedback.err_file_many": "파일은 3개까지 붙일 수 있습니다.",
  "feedback.err_file_quota": "짧은 시간에 너무 많이 올렸습니다. 잠시 후 다시 시도해 주세요.",
  "feedback.err_file_fail": "파일을 올리지 못했습니다. 잠시 후 다시 시도해 주세요.",
  "feedback.submit": "보내기",
  "feedback.again": "하나 더 쓰기",
  "feedback.done_title": "보냈습니다",
  "feedback.done_body": "보내주신 의견은 관리자에게 전달됐습니다. 읽고 반영하겠습니다.",
  "feedback.err_fail": "보내지 못했습니다. 잠시 후 다시 시도해 주세요.",
  "feedback.err_too_long": "내용이 너무 깁니다. 줄여서 다시 보내주세요.",
  "feedback.err_too_many": "짧은 시간에 너무 많이 보냈습니다. 잠시 후 다시 시도해 주세요.",
  "landing.hero_pre": "피지컬 AI 시대,",
  "landing.hero_em": "당신의 능력을",
  "landing.hero_post": "CARIS로 확인하세요",
  "landing.hero_cta": "CARIS 응시하기",
  // 메인 버튼 3개는 영문 브랜드명 + 괄호 안 한글 이름이다(2026-08-18).
  // 시니어 응시자가 영문 브랜드명만으로는 어디로 가는 버튼인지 못 읽는다는 지적에서 나왔다.
  // ⚠️ 한국어 사전에만 붙인다 — 나머지 5개 언어는 브랜드명 그대로다(임의 번역어를 화면에 올리지 않기로 했다).
  "landing.cta_diagnose": "WORLD ARENA (글로벌 랭킹)",
  "landing.cta_exam": "CARIS (자격검정)",
  // WORLD ARENA·CARIS 와 나란한 3번째 버튼. 목적지 = /ebooks.
  // ⚠️ 이 키는 좌측 FAB 메뉴의 '러닝 라이브러리' 항목도 같이 쓴다 — 여기를 고치면 그쪽 라벨도 바뀐다.
  "landing.cta_learn": "Learning Library",
  "landing.cta_learn_main": "Learning Library(학습센터)",
  "landing.card.guide.d": "시험 구성·평가 영역·응시 방법을 한눈에 확인하세요.",
  "landing.card.check.d": "응시 전 보안 프로그램과 환경을 미리 점검하세요.",
  "landing.card.notice.d": "오픈 소식과 응시 전 꼭 확인할 공지를 모았습니다.",
  "nav.exampreview": "응시 화면 미리보기",
  "nav.resultpasspreview": "합격 화면 미리보기",
  "nav.resultfailpreview": "불합격 화면 미리보기",

  // ── CARIS 자격 데이터(caris.ts) 다국어 — getTracks/getRolling 이 tr() 로 참조 ──
  // 공용 스펙 라벨(Guide·ExamApply 공유)
  "caris.lbl.subjects": "검정 과목",
  "caris.lbl.format": "시험 구성",
  "caris.lbl.duration": "시험 시간",
  "caris.lbl.method": "검정 방법",
  "caris.lbl.practical": "실기",
  "caris.lbl.pass": "합격 기준",
  "caris.lbl.eligibility": "응시 자격",
  "caris.lbl.target": "대상",

  // ── CARIS-Ⅰ (전국민 AI·로봇 리터러시): Beginner / Pro / Elite — 티어별 독립 시험, 고정 60% 합격 ──
  // 트랙 표기는 브랜드 하나로 통일 — 화면에서 'CARIS-Ⅰ/Ⅱ' 숫자는 쓰지 않는다(내부 키 t1/t2 는 유지).
  "caris.t1.name": "CARIS",
  "caris.t1.tagline": "전국민 AI·로봇 리터러시",
  "caris.t1.eligibility": "응시 자격 제한 없음",
  "caris.t1.caption": "Beginner·Pro·Elite 세 단계로, 일상 교양부터 전문가 진입까지 각 단계를 개별 시험으로 취득합니다.",
  "caris.t1.beginner.target": "누구나 취득하는 기본 교양",
  "caris.t1.beginner.format": "객관식 4지선다 40문항 · 40분",
  "caris.t1.beginner.pass": "60점(24문항) 이상",
  "caris.t1.beginner.subj.0": "생성형 AI의 일상 활용",
  "caris.t1.beginner.subj.1": "일상 속 로봇 기술과 피지컬 AI의 이해",
  "caris.t1.beginner.subj.2": "인공지능·로봇 윤리 및 디지털 안전 리터러시",
  "caris.t1.pro.target": "중·고등학생 및 직장인 기초",
  "caris.t1.pro.format": "객관식 4지선다 50문항 · 50분",
  "caris.t1.pro.pass": "60점(30문항) 이상",
  "caris.t1.pro.subj.0": "생성형 AI 도구 활용 및 프롬프트 엔지니어링 기초",
  "caris.t1.pro.subj.1": "AI·로봇 자동화 기술의 이해와 활용",
  "caris.t1.pro.subj.2": "피지컬 AI 블록코딩 및 로봇 제어 기초",
  "caris.t1.elite.target": "관리자 강사 및 전문가 진입 과정",
  "caris.t1.elite.format": "객관식 50문항 + 단답형 10문항 · 60분",
  "caris.t1.elite.pass": "60점(36문항) 이상",
  "caris.t1.elite.subj.0": "엣지 AI 디바이스와 센서 데이터 처리",
  "caris.t1.elite.subj.1": "AI·로봇 시스템 설계 및 서비스 기획",
  "caris.t1.elite.subj.2": "파이썬과 API 기반 AI·로봇 연동 프로그래밍",

  // ── CARIS-Ⅱ (피지컬 AI 전문가): Master / Grand Master / Zenith — 기존 Master 내용 유지, 이름만 교체 ──
  "caris.t2.name": "CARIS",
  "caris.t2.tagline": "피지컬 AI 전문가 과정",
  "caris.t2.eligibility": "하위 티어 순차 취득 원칙",
  "caris.t2.caption": "CARIS-Ⅰ Elite 취득 후, Master부터 상위 티어로 순차 응시하는 전문가 과정입니다.",
  "caris.t2.master.prereq": "Elite 취득자",
  // ⚠️ method·pass 는 ' · ' 로 잘라 줄바꿈한다(ExamApply). 구분자를 다른 문자로 바꾸면 한 줄로 뭉친다.
  //    문항 수·시간은 caris.ts 의 TIER_EXAM_SPEC 과 한 쌍이다 — 한쪽만 고치면 문항 관리 화면과 어긋난다.
  "caris.t2.master.method": "필기 객관식 50 + 주관식 10(총 60문항) / 60분 · 실기 PC작업형 / 120분",
  "caris.t2.master.subj.0": "AI·로봇 하드웨어 및 모델 최적화",
  "caris.t2.master.subj.1": "ROS 2 로봇 소프트웨어 개발",
  "caris.t2.master.subj.2": "기초 AI API 연동, Python/C++ 기반 단일 로봇 제어 및 LLM 연동",
  "caris.t2.master.practical": "기초 AI API 연동, Python/C++ 기반 단일 로봇 제어 및 LLM 연동",
  "caris.t2.master.pass": "필기 과목별 40점↑, 평균 60점↑ · 실기 70점↑",
  "caris.t2.grandmaster.prereq": "Master 취득자",
  "caris.t2.grandmaster.method": "필기 객관식 50 + 주관식 10(총 60문항) / 60분 · 실기 복합작업형 / 120분",
  "caris.t2.grandmaster.subj.0": "디지털 트윈 설계 및 AI 기반 시뮬레이션 검증",
  "caris.t2.grandmaster.subj.1": "AI·로봇 융합 시스템 아키텍처 설계 및 지능형 제어 적용",
  "caris.t2.grandmaster.subj.2": "Isaac Sim·Gazebo 기반 자율주행·비전 파이프라인 구축 및 가상-물리 최적화",
  "caris.t2.grandmaster.practical": "Isaac Sim·Gazebo 기반 자율주행·비전 파이프라인 구축 및 가상-물리 최적화",
  "caris.t2.grandmaster.pass": "필기 과목별 40점↑, 평균 60점↑ · 실기 70점↑",
  "caris.t2.zenith.prereq": "Grand Master 취득자",
  // ⚠️ Zenith 는 **필기 서술·논술형 하나**다(2026-08-13). 옛 값은 '포트폴리오 제출 + 심층 면접 30분'
  //    이었는데 성격이 통째로 바뀌었다. 실기가 없으므로 caris.t2.zenith.practical 키는 계속 안 쓴다.
  "caris.t2.zenith.method": "필기 서술·논술형 / 120분",
  "caris.t2.zenith.subj.0": "대규모 AI·로봇 시스템 통합(SI) 및 End-to-End 프로젝트 관리",
  // ⚠️ Zenith 는 **3과목**이다(2026-08-13). 예전엔 기능안전과 거버넌스·윤리가 subj.1 한 과목에 묶여 2과목이었는데,
  //    둘을 갈라 각각 과목으로 세우고 '보안'·'DX 전략'을 넣었다. 표준 3종은 각자 해당 과목을 따라갔다
  //    (ISO 10218=기능안전 · IEC 62443=보안 → subj.1 / ISO/IEC 42001=AI 거버넌스 → subj.2).
  //    과목 수는 caris.ts 의 T2_TIERS(subj)가 정한다 — 키만 늘리면 화면에 안 나온다.
  "caris.t2.zenith.subj.1": "국제 표준(ISO 10218, IEC 62443) 기반의 기능안전 및 보안 적용",
  "caris.t2.zenith.subj.2": "AI 거버넌스(ISO/IEC 42001), 윤리 및 DX 전략",
  "caris.t2.zenith.pass": "루브릭 심사 · 심사위원 3인 평균 80점 이상",
  // 상시(Rolling) 항목
  "caris.rolling.pro_cbt.name": "CARIS 상시 검정 (CBT)",
  "caris.rolling.pro_cbt.badge": "상시 접수",
  "caris.rolling.pro_cbt.date": "연중 상시 · 예약일 응시",
  "caris.rolling.pro_cbt.desc": "원하는 날짜를 예약해 온라인(CBT)으로 응시하는 상시 검정입니다.",

  // ── Guide 히어로 (2026-07 개편: 로고 락업 + 일정 패널 → 카피 + CARIS PLAN 버튼 + 로봇 이미지) ──
  // h1 은 2줄. 1줄은 브랜드 표기라 전 언어 'AI·Robot' 고정, 2줄만 번역 + 끝의 'CARIS' 는 컴포넌트가 파란색으로 붙인다.
  "guide.hero_h1_l2": "융합역량",
  // 소개 문단 — '|' 로 줄바꿈(2줄). 1줄=지향점, 2줄=CARIS 가 하는 일.
  "guide.hero_lead": "AI와 로봇 기술을 이해하고 활용하는 미래형 인재로|CARIS가 당신의 융합역량을 검증하고 인증합니다.",
  "guide.plan_cta": "CARIS PLAN",

  // ── Guide '무엇인가요' 섹션 — 제목 + 영문 정식명 + 한 줄 정의 + 특징 카드 8장 ──
  "guide.what_title": "는 무엇인가요?",
  "guide.what_def": "CARIS는 AI·Robot 융합역량 자격검정입니다.",
  "guide.f1.t": "AI·Robot 융합역량 인증",
  "guide.f1.d": "체계적인 역량 검증 시스템",
  "guide.f2.t": "체계적인 자격 등급",
  "guide.f2.d": "단계별 성장 로드맵 제공",
  "guide.f3.t": "누구나 응시 가능",
  "guide.f3.d": "연령·전공·경력 제한 없음",
  "guide.f4.t": "글로벌 활용 가능",
  "guide.f4.d": "국제적 표준 기반",
  "guide.f5.t": "기술 이해",
  "guide.f5.d": "AI·로봇 기술의 기본 원리 이해",
  "guide.f6.t": "실무 활용",
  "guide.f6.d": "업무·일상에 쓰는 실무 능력",
  "guide.f7.t": "창의적 융합",
  "guide.f7.d": "AI·로봇 융합으로 새 가치 창출",
  "guide.f8.t": "미래 역량",
  "guide.f8.d": "미래 사회의 핵심 역량 확보",

  // ── Guide '자격 체계' 섹션 제목/부제 ──
  "guide.ladder_title": "자격 체계",
  "guide.ladder_sub": "단계별로 차근차근, 당신의 꿈을 향해 나아가세요!",

  // ── Plan(/plan · 시험 일정) ──
  "plan.title": "CARIS PLAN",
  "plan.sub": "CARIS 자격 검정 매월 정기 운영 일정 안내",
  "plan.back": "CARIS",
  // ── /plan 접수중 회차 일정표(2026-08-20) — 줄 이름 4개. 날짜는 그 회차 값에서 온다. ──
  "plan.step_apply": "원서 접수",
  "plan.step_exam": "응시 기간",
  "plan.step_grade": "채점 기간",
  "plan.step_result": "합격자 조회",

  // ── Guide(자격검정 안내) 하드코딩 라벨 ──
  "guide.cert_intro_title": "AI·Robot 융합역량 자격시험",
  // 피라미드 우측 그룹 라벨 — '|' 로 줄바꿈(브레이스 옆 2줄 세로 배치). 위 3티어=피지컬 AI, 아래 3티어=AI·로봇 리터러시
  "guide.group_physical": "피지컬 AI|전문가",
  "guide.group_literacy": "AI·로봇|리터러시",
  // CARIS-Ⅱ(피지컬 AI) 카드 배너 문구 — 응시화면의 prereq(응시자격)과 별개로 Guide 배너 전용. Master=초급/GM=중급/Zenith=고급
  "guide.ptrack.master": "피지컬 AI 초급 전문가",
  "guide.ptrack.grandmaster": "피지컬 AI 중급 전문가",
  "guide.ptrack.zenith": "피지컬 AI 고급 전문가",
  "guide.ladder_hint": "급수를 눌러 검정과목 보기",
  "guide.aria_prev_track": "이전 자격",
  "guide.aria_next_track": "다음 자격",
  "guide.aria_prev_grade": "이전 급수",
  "guide.aria_next_grade": "다음 급수",

  // ── ExamSchedule(자격검정 접수) 하드코딩 라벨 ──
  "sched.badge": "시험 일정",
  "sched.title": "CARIS 접수",
  "sched.desc": "접수할 시험을 선택하세요. 접수중인 일정만 신청할 수 있습니다.",
  "sched.regular": "정기시험 일정",
  "sched.rolling": "상시시험",
  "sched.exam_date": "시험일",
  "sched.exam_period": "응시 기간",
  "sched.apply_period": "접수기간",
  "sched.apply": "접수하기",
  "sched.empty": "등록된 시험 일정이 없습니다.",

  // ── ExamApply(원서접수) 하드코딩 라벨 ──
  "apply.back": "CARIS PLAN",
  "apply.title": "원서접수",
  "apply.select_cert": "자격 선택",
  "apply.track": "트랙",
  "apply.tier": "등급",
  "apply.pay_summary": "결제 요약",
  "apply.sel_cert": "선택 자격",
  "apply.round": "회차",
  "apply.fee": "응시료",
  // exam_fees 에 그 티어의 행이 없을 때 — 금액 자리에 숫자를 지어내지 않고 이걸 띄우고 결제를 막는다.
  // (현재 CARIS-Ⅱ Master·Grand Master·Zenith 가 여기 해당)
  "apply.fee_tbd": "준비 중",
  "apply.fee_free": "무료",
  "apply.free_btn": "무료로 신청하기",
  "apply.total": "총 결제금액",
  // 추천 교재(원서접수 가운데 열) — 응시료와 **함께** 결제되는 곁다리다.
  "apply.book_col": "추천 교재 구매",
  "apply.book_add": "구매하기",
  "apply.book_added": "담김",
  "apply.book_row": "교재 ({name})",
  "apply.book_note": "원서 접수 시 교재를 함께 구매하면 더욱 편리합니다.",
  "apply.book_owned": "이미 구매하신 교재예요. 이 책으로 함께 준비해 보세요.",
  "apply.book_owned_cta": "내 서재에서 보기",
  "apply.pay_btn": "결제하기",
  "apply.pay_note": "결제 시 본인인증이 필요합니다. 응시료·본인인증·결제는 추후 연결(미리보기).",
  "apply.modal_title": "결제 기능 준비 중",
  "apply.modal_body": "현재는 접수 화면 미리보기입니다. 본인인증·결제(PG)는 곧 연결됩니다.",
  "apply.confirm": "확인",
  "apply.closed_title": "지금은 접수기간이 아닙니다",
  "apply.closed_body": "마감되었거나 아직 열리지 않은 회차입니다. 시험 일정에서 접수 중인 회차를 확인해 주세요.",
  "apply.closed_cta": "시험 일정 보기",

  // ── SEB 설치 안내(SebInstall 컴포넌트) — ExamGate 모달 · ExamCheck Step1 공유 ──
  "seb.download": "보안 프로그램(SEB) 다운로드",
  "seb.dl_meta": "약 {size} · 1회만 설치하면 됩니다 · 게시자 ETH Zürich(정상)",
  "seb.steps_title": "설치 방법 (약 2분)",
  "seb.step1_t": "다운로드",
  "seb.step1_d": "위 버튼을 누르면 설치 파일이 받아집니다.",
  "seb.step2_t": "실행 (경고는 정상)",
  "seb.step2_d_mac": ".dmg 파일을 열고 SEB를 응용 프로그램 폴더로 옮긴 뒤, 처음 실행은 우클릭 → 열기 로 하세요.",
  "seb.step3_t": "시험 열기",
  "seb.step3_d": "설치가 끝나면 이 화면으로 돌아와 아래 버튼으로 SEB에서 시험을 엽니다.",
  "seb.launch_btn": "SEB로 시험 열기",
  "seb.dialog_title": "Windows가 PC를 보호했습니다",
  "seb.dialog_more": "추가 정보",
  "seb.dialog_run": "실행",
  "seb.chip_once": "1회만 설치",
  "seb.chip_publisher": "ETH Zürich 서명",
  "seb.chip_size": "약 {size}",
  "seb.warn_title": "설치 중 경고가 떠도 정상입니다",
  "seb.warn_title_win": "설치 중 “{dialog}” 창이 떠도 정상입니다",
  "seb.warn_body_pre": "정식 프로그램이므로",
  "seb.warn_body_post": "순서로 누르면 설치가 계속됩니다.",
  "seb.fact_program": "프로그램",
  "seb.fact_maker": "만든 곳",
  "seb.fact_maker_v": "스위스 취리히공대(ETH) 공식 오픈소스 — 전 세계 대학·시험기관이 사용",
  "seb.fact_install": "설치",
  "seb.entry_loading": "시험을 준비하고 있어요…",
  "seb.entry_retry": "다시 시도",
  // SEB 탈출 버튼. '취소'·'닫기' 처럼 모호하게 쓰지 말 것 — 갇힌 사람이 한눈에 알아봐야 하는 문구다.
  // SEB 환경 점검 도착 화면(/exam/envcheck) — **모의 문제를 풀리지 않는다.**
  // 확인하려는 건 "이 PC 에서 SEB 가 실제로 떴는가" 하나뿐이고, 이 화면이 보이면 그게 증명된다.
  "envcheck.saving": "점검 결과를 저장하는 중…",
  "envcheck.save_failed": "점검 기록을 저장하지 못했습니다. 보안 브라우저를 닫고 다시 시도해 주세요.",
  "envcheck.ok_title": "환경 점검 완료",
  "envcheck.ok_desc": "이 컴퓨터에서 시험을 볼 수 있습니다. 아래 버튼으로 보안 브라우저를 닫아주세요.",
  "envcheck.warn_title": "확인이 필요한 항목이 있어요",
  "envcheck.warn_desc": "아래에서 ✕ 표시된 항목을 해결한 뒤 다시 점검해 주세요.",
  "envcheck.row_seb": "보안 브라우저로 열림",
  "envcheck.row_fs": "전체화면 전환",
  "envcheck.row_net": "인터넷 연결",
  "envcheck.row_screen": "화면 크기",
  "seb.exit": "보안 브라우저 종료",
  // SEB 로 로그인을 넘기는 인계표가 주소에 없을 때. 옛 .seb 파일로 들어왔거나 설정에서
  // startURLAppendQueryParameter 가 빠진 경우다 — SEB 안에서는 로그인할 방법이 없으므로 나가서 다시 시작해야 한다.
  // 재진입 무효 안내 — 사유와 다음 행동(문의)까지 말해줘야 한다. 무감독이라 옆에서 설명해 줄 사람이 없다.
  // ⚠️ "도와드립니다" 로 끝내면 안 된다 — 응시자는 (1) 남은 시간이 사라졌는지 (2) 응시 기간이 끝나면
  //    끝인지 (3) 언제 처리되는지를 모른 채 기다리게 된다. 세 가지를 다 말해준다.
  //    24시간 상주 운영이 아니므로 "바로 처리"를 약속하지 않는다.
  "seb.voided_how": "기기 고장·정전·네트워크 끊김으로 중단되셨다면 1:1 문의로 알려주세요. 중단 기록을 확인해 드리며, 복구되면 끊긴 시점의 답안과 남은 시간 그대로 이어서 응시하실 수 있습니다. 다만 재응시는 응시 기간 안에서만 가능하고, 확인에는 영업일 기준 시간이 걸릴 수 있습니다.",
  "seb.err_no_handoff": "응시 정보를 확인하지 못했습니다.",
  "seb.err_no_handoff_how": "보안 브라우저를 닫고, 원래 브라우저의 응시 준비 화면에서 다시 시작해 주세요.",

  // ── 월드 아레나(/arena) — 지도·랭킹 패널·하단 런처 ──
  //   arena.b* = 하단 이동 버튼(Hub · 레벨테스트 · 오늘의 문제 · 미니게임)
  "arena.low": "낮음",
  "arena.high": "높음",
  // ⚠️ arena.avgLevel 은 레벨테스트 시절 문구다. 지도 지표가 레벨 → 랭킹점수(season_total 평균, 베이지안 보정)로
  //    바뀌면서 arena.regionScore 로 대체했다. 다른 곳에서 안 쓰면 avgLevel 은 지워도 된다.
  "arena.avgLevel": "평균 레벨",
  "arena.regionScore": "지역 점수",
  "arena.part": "참여 인원",
  "arena.rankL": "순위",
  "arena.ourRank": "우리 순위",
  "arena.topRegion": "최고 지역",
  "arena.totalPart": "총 참여",
  "arena.search": "지역 검색…",
  "arena.world": "세계",
  "arena.worldLeague": "World League",
  "arena.league": " 리그",
  "arena.ppl": "명",
  "arena.unit": "위",
  "arena.avg": "평균",
  "arena.drillHint": "‘{n}’ 선택됨 · 한 번 더 누르면 시·군·구로 들어가요",
  "arena.our0": "· 세계",
  "arena.our1": "· 우리 지역",
  "arena.our2": "· 우리 동네",
  "arena.bLevel": "레벨 테스트",
  "arena.bLevelS": "내 실력 측정 · 진화",
  "arena.bHub": "마이 홈",
  "arena.bHubS": "캐릭터 허브",
  "arena.bDaily": "오늘의 학습",
  "arena.bDailyS": "데일리 콘텐츠",
  // 아레나 화면 제목 — 제품명은 6개국어 영문 유지(ko 만 기존 표기 보존)
  "arena.title": "WORLD ARENA",
  "arena.bGame": "미니게임",
  // 용어 퀴즈 게임 3종 + 로봇 조작/코딩 퍼즐 2종이라 '용어'로 못 묶는다 → AI·로봇 전체로 넓힌 문구.
  "arena.bGameS": "AI · 로봇을 게임으로 한 판",
  "arena.loading": "지도를 불러오는 중…",
  "arena.zoom_in": "확대",
  "arena.zoom_out": "축소",
  "arena.zoom_reset": "원래대로",
  "arena.numbers_hide": "순위 숫자 끄기",
  "arena.numbers_show": "순위 숫자 켜기",
  "arena.tabLeague": "World League",
  "arena.tabChat": "채팅",
  "arena.panelToggle": "패널 전환",
  "arena.dokdo": "독도",
  // 유사채팅(pseudo-chat) 보드
  "chat.title": "채팅",
  "chat.placeholder": "메시지를 입력하세요…",
  "chat.send": "보내기",
  "chat.sending": "전송 중…",
  "chat.empty": "아직 메시지가 없어요. 첫 메시지를 남겨보세요!",
  "chat.report": "신고",
  // 아바타 탭 → 그 사람 카드. 실패(랭킹 기록 없음·익명·탈퇴)는 조용히 삼키지 않고 한 줄로 알려준다.
  "chat.cardOf": "{name} 카드",
  "chat.noCard": "아직 랭킹 기록이 없는 사용자예요",
  "chat.reported": "신고했습니다",
  // 삭제 안내문은 남긴다 — 관리자 가림(chatHide)으로 여전히 이 상태가 나온다.
  //  ⚠️ 사용자 수정·삭제는 2026-08-13 제거됐다(chat.edit/delete/editedMark/editWindow/confirmDelete 키도 같이 삭제).
  //     수정이 있으면 욕설을 쓰고 신고당한 뒤 10분 안에 본문을 고쳐 증거를 지울 수 있었다.
  "chat.deleted": "삭제된 메시지입니다",
  // 번역 토글(2026-08-13). 대상 언어는 국가에서 정해지므로 문구에 언어 이름을 넣지 않는다
  //  — 넣으려면 전 세계 언어 이름을 6개국어로 들고 있어야 하고, 그건 사전이 아니라 Intl.DisplayNames 의 일이다.
  "chat.trOff": "번역",
  "chat.trOn": "원문 보기",
  "chat.trLoading": "번역 중…",
  "chat.trMark": "번역됨",
  "chat.trFailed": "번역에 실패했어요. 잠시 후 다시 시도해주세요",
  "chat.blockedLocal": "부적절한 표현이 포함되어 있어요",
  "chat.blockedLink": "링크는 보낼 수 없어요",
  "chat.justNow": "방금 전",
  "chat.minutesAgo": "{n}분 전",
  "chat.blockedMod": "정책 위반으로 게시할 수 없어요",
  "chat.modUnavailable": "검수 시스템 점검 중이에요. 잠시 후 다시 시도해주세요",
  "chat.tooFast": "너무 빨리 보내고 있어요. 잠시 후 다시 시도해주세요",
  "chat.duplicate": "방금 같은 내용을 보냈어요",
  "chat.rateLimited": "요청이 너무 많아요. 잠시 후 다시 시도해주세요",
  "chat.loginToJoin": "채팅에 참여하려면 로그인해주세요",
  "chat.scamNotice": "CARIS 운영자는 계정정보·인증번호·금품을 요구하지 않으며, 사칭 및 개인 간 거래로 인한 피해에 대해서는 책임지지 않습니다.",
  // 방(room) — World 1개 + 나라별 1개. 어느 방인지는 지도 선택이 정한다(/arena).
  // ⚠️ 'World' 는 브랜드 영문 고정(2026-08-11) — 6개국어 모두 같은 글자. 돌아가기 버튼도 같은 글자다
  //    (나라 방에 있을 때만 보이므로 '어디로 가는지'가 이름만으로 읽힌다).
  "chat.roomGlobal": "World",
  "chat.roomBack": "World",
  "chat.anonBadge": "익명",
  "chat.reportTitle": "신고 사유를 선택해주세요",
  "chat.reportSpam": "스팸·광고",
  "chat.reportAbuse": "욕설·혐오 표현",
  "chat.reportSexual": "음란·선정성",
  "chat.reportFlood": "도배",
  "chat.reportPrivacy": "개인정보 노출",
  "chat.reportOther": "기타",
  "chat.reportDetail": "자세한 내용 (선택)",
  "chat.reportSubmit": "신고하기",

  // ══════════════════════════════════════════════════════════════════════════
  //  응시권(exam_tickets) · 응시료 결제 — 2026-08 추가
  //  한 기능이 여러 화면(원서접수 · 결제 · 마이페이지 · 응시 게이트)에 걸쳐 있어서
  //  네임스페이스별로 흩지 않고 여기 한 덩어리로 모았다. 위쪽 apply.* / pay.* / gate.* /
  //  prep.* / mypage.* 블록에도 같은 접두사의 옛 키가 있으니 검색으로 찾을 것.
  // ══════════════════════════════════════════════════════════════════════════

  // ── 응시권 상태·라벨 (ticket.*) — 마이페이지 '보유 응시권' 블록이 주 사용처 ──
  "ticket.section_title": "보유 응시권",
  "ticket.section_sub": "결제한 시험이 여기 쌓여요. 응시 기간이 되면 바로 응시할 수 있어요.",
  "ticket.empty": "아직 보유한 응시권이 없습니다.",
  "ticket.empty_cta": "접수하러 가기",
  "ticket.count": "보유 {n}장",
  // status_issued 를 '발급됨' 이 아니라 '미사용' 으로 쓰는 이유: 목록에 서는 모든 응시권은 이미 발급된 것이라
  // '발급됨' 은 정보가 0이다. 사용자가 알아야 하는 건 "아직 안 썼다" 는 사실이다.
  "ticket.status_issued": "미사용",
  // consumed 는 '응시 완료' 가 아니다 — 응시를 시작한 순간 소진되므로 진행 중일 수도 있다.
  "ticket.status_consumed": "사용됨",
  "ticket.status_void": "무효",
  "ticket.status_expired": "기간 만료",
  // 서버(my-attempts)가 내려주는 usableReason 코드 5종과 1:1 로 대응한다.
  //   before_exam_day · window_closed · already_taken · in_progress · expired
  // 서버는 코드만 주고 문구는 여기가 정한다 — 새 코드가 생기면 여기에도 키를 추가할 것.
  "ticket.usable": "지금 응시할 수 있어요",
  "ticket.reason_before_exam_day": "{date}부터 응시할 수 있어요",
  "ticket.reason_window_closed": "응시 기간이 지났어요",
  "ticket.reason_already_taken": "이미 응시했어요",
  "ticket.reason_in_progress": "응시가 진행 중이에요",
  "ticket.reason_expired": "응시권이 만료됐어요",
  "ticket.go_exam": "응시하러 가기",
  // 시험환경 점검 게이트 — 점검을 마쳐야 응시 버튼이 열린다(2026-08-11).
  //   잠금 브라우저가 안 켜지는 PC 라는 걸 시험 당일에 알면 손쓸 방법이 없어서 미리 걸러낸다.
  "ticket.env_do": "시험환경 테스트",
  "ticket.env_done": "환경 테스트 완료",
  "ticket.env_required": "시험환경 테스트를 마쳐야 응시할 수 있어요.",
  "ticket.open_now": "지금 응시할 수 있는 시험 {n}개",
  "ticket.open_now_sub": "보유 응시권에서 시험환경 테스트 후 응시하세요.",
  // 필드 라벨 — 회차·등급은 원서접수 화면(apply.round / apply.tier)과 같은 말을 써야 한다.
  "ticket.round": "회차",
  "ticket.tier": "등급",
  "ticket.issued_at": "발급일",
  "ticket.exam_period": "응시 기간",
  "ticket.price_paid": "결제금액",
  // 발급 출처(exam_tickets.source) — pg 는 평상시 굳이 안 띄우지만, 관리자/무료 발급과 구분이 필요할 때 쓴다.
  "ticket.source_pg": "결제로 발급",
  "ticket.source_admin": "관리자 발급",
  "ticket.source_free": "무료 응시권",

  // ── 원서접수(/exam/apply) 추가분 ──
  // 회차가 연 급수(exam_rounds.open_tiers)에 없는 티어는 숨기지 않고 비활성 + 이 배지로 보여준다
  // — 어떤 급수가 존재하는지 알리는 값이 있어서다.
  "apply.tier_not_open": "이 회차 미개설",
  "apply.owned": "구매 완료",
  "apply.owned_cta": "내 응시권 보기",
  "apply.already_applied": "이미 접수한 급수입니다",
  "apply.login_required": "로그인 후 접수할 수 있어요.",
  // 짧은 인라인 배지용. 전체 화면 안내는 기존 apply.closed_title / apply.closed_body 를 쓴다.
  "apply.period_closed": "접수기간이 아닙니다",
  "apply.pay_go": "결제하러 가기",
  // ⚠️ 기존 apply.pay_note 는 '결제는 추후 연결(미리보기)' 라고 적혀 있어 결제가 실동작하면 거짓말이 된다.
  //    실결제 연결 후에는 이 키로 갈아끼울 것(옛 키는 지우지 않고 남겨둔다).
  //    문구 안의 '마이페이지 › 시험 응시 현황' 은 mypage.tab_attempts 와 같은 말이어야 한다.
  "apply.pay_note_live": "결제하면 마이페이지 › 시험 응시 현황에서 응시권을 확인할 수 있어요.",

  // ── 결제(/checkout · /pay/success) 추가분 ──
  "pay.go_tickets": "내 응시권 보기",
  "pay.go_plan": "시험 일정 보기",
  "pay.exam_success_title": "응시권이 발급됐어요",
  "pay.exam_success_body": "마이페이지 › 시험 응시 현황에서 확인하고, 응시 기간이 되면 응시하세요.",
  // 응시료는 카드·간편결제만 판다(가상계좌 제외). 그래도 가상계좌 결제가 들어오면 응시권을 발급하지 않으므로
  // 이북과 같은 '입금하면 자동 지급' 문구(pay.waiting_body)를 쓰면 안 된다.
  "pay.exam_waiting_body": "응시료는 카드·간편결제만 지원해요. 가상계좌로 입금해도 응시권이 자동 발급되지 않으니 문의해 주세요.",
  // 자격증 발급비 — 결제로 끝나는 게 아니라 **발급이 한 걸음 남아 있다**. '결제 완료'로만 닫으면
  // 사용자는 자격증이 어디 있는지 못 찾는다(지급물이 따로 없는 유일한 상품이라 더 그렇다).
  "pay.go_cert": "자격증 발급받기",
  "pay.go_attempts": "응시 내역 보기",
  "pay.cert_success_title": "발급비 결제가 완료됐어요",
  "pay.cert_success_body": "이어서 자격증을 발급합니다. 아래 버튼을 눌러주세요.",
  "pay.cert_waiting_body": "발급된 가상계좌로 입금하면 자격증을 발급할 수 있어요.",
  // 통화 고지 — 화면 가격은 달러인데 토스 결제창은 원화로 뜬다. 이 문구가 없으면 사용자는 금액이 다르다고 느낀다.
  //   {krw} = lib/money.ts 의 krw() 로 찍은 실제 청구액 문자열.
  // ⚠️ 문장 안의 '1,500' 은 하드코딩이다 — lib/money.ts 의 KRW_PER_USD 를 바꾸면 6개국어를 전부 같이 고칠 것.
  // ⚠️ '○월○일 기준 환율' 이라고 쓰지 마라. 시장 환율이 아니라 우리가 정한 고정 환산값이다.
  "pay.currency_note": "실제 청구 금액 {krw} · 오늘 환율로 계산된 금액입니다.",
  // 해외 결제(엑심베이)는 **달러로 청구**된다 — 원화 고지문을 그대로 쓰면 화면과 결제창이 다른 돈을 말한다.
  //   {usd} = 실제 청구되는 달러 금액(서버가 정한 값 그대로).
  "pay.currency_note_usd": "해외 결제는 미국 달러로 청구됩니다 · 실제 청구 금액 {usd}",
  // 엑심베이 결제창은 우리 페이지에 아무것도 그리지 않는다 — 안내가 없으면 화면이 빈 것으로 읽힌다.
  "pay.cert_fee_note": "합격 후 자격증을 발급할 때 별도 비용이 청구됩니다.",
  "pay.pg_eximbay_note": "결제하기를 누르면 Eximbay 결제창이 열리고, 결제수단은 그 창에서 고릅니다.",
  // ── 결제 전 취소·환불 규정 동의(2026-08-20) ──
  //    표 4줄은 응시료·자격증 발급비용, terms_ebook 은 이북·묶음용(디지털 콘텐츠라 기준이 다르다).
  //    ⚠️ 법적 고지라 임의로 줄이거나 의역하지 말 것 — 문구를 바꾸려면 규정 자체를 먼저 고쳐야 한다.
  "pay.terms_title": "취소 및 환불 규정",
  "pay.terms_col_when": "취소 시점 (해당일 24:00 기준)",
  "pay.terms_col_rate": "환불율",
  "pay.terms_col_note": "비고",
  "pay.terms_none": "불가",
  "pay.terms_r1_when": "응시일 7일 전까지",
  "pay.terms_r1_note": "전액 환불",
  "pay.terms_r2_when": "응시일 6일 전 ~ 3일 전까지",
  "pay.terms_r2_note": "반액 환불",
  "pay.terms_r3_when": "응시일 2일 전 ~ 당일 응시 시작 전",
  "pay.terms_r3_note": "원칙적 불가",
  "pay.terms_r3_note2": "예외 전액 환불 — 직계가족 사망·입원, 감염병 격리 등 불가피한 사유 증빙 시",
  "pay.terms_r4_when": "응시 시작 이후",
  "pay.terms_r4_note": "취소 및 환불 절대 불가 (미응시 포함)",
  "pay.terms_ebook": "전자책·강의는 디지털 콘텐츠입니다. 결제 후 열람을 시작하면 청약철회가 제한되며, 한 번도 열람하지 않은 상품만 결제일로부터 7일 이내 환불할 수 있습니다.",
  "pay.terms_agree": "위 취소 및 환불 규정을 확인했으며 이에 동의합니다. (필수)",
  "pay.terms_required": "환불 규정에 동의해야 결제할 수 있습니다.",
  // 위 고지문의 짧은 버전 — 가격만 달러로 보여주는 목록(/ebooks · /exam/apply)용. 청구액 보간이 없다.
  "pay.currency_hint": "국내 결제는 결제 시점 환율로 원화 청구됩니다.",

  // ── 응시 게이트(/exam) 거절 안내 ──
  // 여기서 막는 건 보안이 아니라 UX 다(준비 7단계를 다 밟고 마지막에 403 을 받지 않게 하는 것).
  // 실제 차단은 start-exam 이 응시권으로 한다.
  "gate.no_ticket_title": "응시권이 없어요",
  "gate.no_ticket_body": "응시하려면 먼저 원서접수와 응시료 결제가 필요해요.",
  "gate.no_ticket_cta": "접수하러 가기",
  "gate.pick_ticket_title": "응시할 시험을 고르세요",
  "gate.pick_ticket_body": "보유한 응시권이 여러 장이에요. 응시할 시험을 선택해 주세요.",
  "gate.not_exam_period_title": "지금은 응시 기간이 아니에요",
  "gate.not_exam_period_body": "응시 기간은 {from} ~ {to} 예요.",
  // 익명(게스트) 세션에는 응시권이 붙을 수 없다 — 결제 자체가 로그인 계정에만 열려 있기 때문이다.
  "gate.login_paid_title": "결제한 계정으로 로그인해 주세요",
  "gate.login_paid_body": "응시권은 결제한 계정에 발급돼요. 게스트(비로그인)로는 응시할 수 없어요.",

  // ── 응시 준비(/exam/prepare) — start-exam 이 돌려주는 에러 코드를 사람이 읽을 문구로 ──
  //   no_ticket · pick_ticket · attempt_exists · (응시창 밖) · (익명)
  "prep.err_no_ticket": "응시권이 없어 시험을 시작할 수 없습니다.",
  "prep.err_pick_ticket": "응시할 시험을 선택해 주세요.",
  "prep.err_exam_closed": "지금은 응시 기간이 아닙니다.",
  "prep.err_login_paid": "결제한 계정으로 로그인해야 응시할 수 있습니다.",
  "prep.err_attempt_exists": "이미 응시한 시험입니다.",

  // ── SEB 진입로(/exam/seb) — 익명 세션으로는 응시권을 가질 수 없어 로그인으로 돌린다 ──
  "seb.login_required": "응시하려면 결제한 계정으로 로그인해 주세요.",

  // ── 마이페이지 '시험 응시 현황' 빈 상태 분기 (응시권 없음 → 접수 / 응시권 있음 → 기존 mypage.go_exam) ──
  "mypage.empty_no_ticket": "아직 접수한 시험이 없습니다.",
  "mypage.go_apply": "시험 접수하기",

  // ── 오늘의 학습(/daily) · 미니게임(/games) ────────────────────────────────
  // ⚠️ 여기 있는 건 **화면 문구뿐**이다. 문제 자체(용어·설명·보기)는 src/lib/terms.ts 와
  //    public/games/*.html 의 POOL 에 한국어로 들어 있고 아직 다국어가 아니다.
  //    레벨테스트(questions 다국어 JSONB + translate-questions)처럼 콘텐츠 파이프라인을 붙이면
  //    그때 문항도 언어를 따라간다 — 그 전까지는 틀만 번역되고 문제는 한국어로 나온다.
  "daily.title": "오늘의 학습",
  "daily.login_note": "로그인해야 학습 완료가 기록돼요",
  "daily.term_label": "오늘의 용어",
  "daily.correct": "정답이에요! 🎉 오늘 학습 완료.",
  "daily.wrong": "아쉬워요 — 정답은 {answer} 예요. 시도했으니 완료!",
  "daily.already": "오늘 학습은 이미 완료했어요. 정답은 {answer} 예요.",
  "daily.theory": "이론",
  "daily.hint_lead": "헷갈리면",
  "daily.reward_head": "완료하면",
  "daily.done_note": "오늘 학습 완료 ✓ 내일 새 문제가 열려요. 오늘 것은 다시 볼 수 있어요(보상은 하루 1회).",
  "daily.saving": "기록하는 중…",
  "daily.pick_note": "정답을 고르면 오늘 학습이 완료돼요. 맞히지 않아도 시도하면 적립돼요.",
  "daily.pop_title": "오늘 학습 완료!",
  "daily.pop_bonus": "7일 완주 +{b}P",
  "daily.pop_grew": "캐릭터가 오늘도 한 뼘 자랐어요.",
  "daily.pop_already": "오늘 출석으로 코인은 이미 받았어요. 학습 기록은 남았습니다.",

  "mg.title": "미니게임",
  "mg.preparing": "준비 중인 미니게임이에요.",
  "mg.to_list": "미니게임 목록으로",
  "mg.guest_hint": "기록이 안 남아요 · 로그인",
  "mg.locked_hint": "로그인하면 플레이할 수 있어요",
  "mg.locked_title": "로그인하면 열려요",
  "mg.locked_body": "비로그인은 ‘{game}’ 만 해볼 수 있어요. 로그인하면 나머지 게임이 전부 열리고, 최고 기록과 랭킹도 남습니다.",
  "mg.not_saved": "이 기록은 저장되지 않았어요",
  "mg.not_saved_body": "로그인하면 최고 기록이 남고 게임 랭킹에 올라가요. 지금은 구경만 할 수 있어요.",
  "mg.keep_playing": "그냥 계속 할래요",
  "mg.rank_title": "{title} 랭킹",
  "mg.rank_fail": "랭킹을 불러오지 못했어요.",
  "mg.rank_rule_level": "도달 레벨이 높은 순 · 같으면 걸린 시간이 짧은 순",
  "mg.rank_rule_score": "점수가 높은 순 · 같으면 먼저 도달한 순",
  "mg.rank_players": " · 참가 {n}명",
  "mg.rank_empty": "아직 기록이 없어요. 첫 기록의 주인이 되어보세요!",
  "mg.rank_need_login": "로그인하면 내 순위가 표시돼요.",
  "mg.rank_no_mine": "아직 내 기록이 없어요 — 한 판 하고 오면 등록됩니다.",
  "mg.sec": "{n}초",
  "mg.min_sec": "{m}분 {s}초",

  // 미니게임 카드(제목·소개·뱃지) — 'CARI' 는 캐릭터 이름이라 번역하지 않는다.
  "mg.beat-cari.title": "버텨라 CARI",
  "mg.beat-cari.tagline": "쏟아지는 돌, 문제로 버텨라!",
  "mg.beat-cari.badge": "AI · 로봇 용어 서바이벌",
  "mg.shoot-cari.title": "쏴라 CARI",
  "mg.shoot-cari.tagline": "쏟아지는 운석을 정답으로 격추!",
  "mg.shoot-cari.badge": "AI · 로봇 용어 슈팅",
  "mg.pick-cari.title": "골라라 CARI",
  "mg.pick-cari.tagline": "발판이 무너지기 전에 O·X 를 골라라!",
  "mg.pick-cari.badge": "AI · 로봇 용어 OX 서바이벌",
  "mg.reach-cari.title": "닿아라 CARI",
  "mg.reach-cari.tagline": "관절을 움직여 목표에 닿아라",
  "mg.reach-cari.badge": "로봇팔 · 기구학 퍼즐",
  "mg.program-cari.title": "프로그램해라 CARI",
  "mg.program-cari.tagline": "명령을 짜서 CARI를 움직여라",
  "mg.program-cari.badge": "로봇 · 블록 코딩 퍼즐",
  "mg.build-cari.title": "지어라 CARI",
  "mg.build-cari.tagline": "라인을 깔면 공장이 알아서 돌아가요!",
  "mg.build-cari.badge": "스마트팩토리 · 라인 설계 퍼즐",
  "mg.block-cari.title": "막아라 CARI",
  "mg.block-cari.tagline": "규정에 걸리는 곳을 가리고 넘겨라!",
  "mg.block-cari.badge": "AI 입력 전 정보 가리기",
  "mg.order-cari.title": "시켜라 CARI",
  "mg.order-cari.tagline": "도면대로 나오게 지시를 골라라!",
  "mg.order-cari.badge": "AI 지시문 설계 퍼즐",
  "mg.feel-cari.title": "더듬어라 CARI",
  "mg.feel-cari.tagline": "앞이 안 보인다. 센서만 믿고 가라!",
  "mg.feel-cari.badge": "센서 · 에지 AI 탐사",

  // ── 공유 카드(ShareCardModal + lib/shareCard.ts) ──────────────────────────
  // ⚠️ 카드 안 글자는 캔버스에 그려진다 — 훅을 못 쓰므로 renderShareCard 가 lang 을 받아 tr() 로 뽑는다.
  //    카드는 이미지로 밖으로 나가는 물건이라, 만든 사람의 화면 언어를 그대로 따라가는 게 맞다.
  "share.modal_title": "내 카드 공유",
  "share.making": "카드 만드는 중…",
  "share.make_fail": "카드를 만들지 못했어요",
  "share.img_fail": "이미지를 만들지 못했어요",
  "share.saved": "이미지를 저장했어요",
  "share.copied": "클립보드에 복사했어요",
  "share.copy_unsupported": "복사를 지원하지 않는 브라우저예요",
  "share.do_share": "공유하기",
  "share.do_save": "이미지 저장",
  "share.do_copy": "이미지 복사",
  "share.note": "지금 순위·티어 기준으로 만든 카드예요.",
  "share.note_retry": "카드는 지금 순위·티어 기준이에요. 응시하면 다시 만들어서 공유할 수 있어요.",
  // 카드 안(캔버스)에 그려지는 글자
  "share.card.title": "시즌 기록",
  "share.card.rank_n": "{n}위",
  // ⚠️ 'World' 는 브랜드 영문 고정(2026-08-11) — 6개국어 모두 같은 글자.
  "share.card.world": "World",
  "share.card.country": "국가",
  "share.card.region": "지역",
  "share.card.season_score": "시즌 점수",
  "share.card.joined": "가입일",
  "share.card.friend_code": "친구 코드",

  // ── 캐릭터 허브(/hub) ─────────────────────────────────────────────────────
  // Hub.tsx 는 오래 한국어 하드코딩이었다(2026-08-07 일괄 이관). 문구를 새로 넣을 때 6개국어를 다 채울 것.
  // ⚠️ 토스트 아이콘은 예전에 문구를 정규식(/부족|필요|오류/)으로 검사해 골랐다 — 번역하면 그대로 깨져서
  //    Hub.tsx 가 종류(kind)를 들고 다니도록 바꿨다. 여기 문구를 고쳐도 아이콘은 영향받지 않는다.
  "hub.err.insufficient_points": "코인이 부족해요",
  "hub.err.already_owned": "이미 보유한 한정템이에요",
  "hub.err.unauthorized": "로그인이 필요해요",
  "hub.err.generic": "오류가 발생했어요. 잠시 후 다시 시도해주세요",
  // 방 저장 거절 사유(room 함수). 정상적으로 쓰면 안 뜬다 — 화면이 면 안 맞는 가구를 후보에서 이미 거른다.
  "hub.err.not_owned": "가지고 있지 않은 가구예요",

  // ── 방 꾸미기(미니룸) ──

  // 가구 이름 — 상점·방 고르기가 같이 쓴다.

  // ── 남의 방(/room/:handle) ──
  "room.visit": "방 보기",
  "room.copy": "링크 복사",
  "room.copied": "복사했어요",
  "room.someone": "이름 없음",
  "room.season_pt": "시즌 {n}점",
  "room.not_found": "방을 찾을 수 없어요.",
  "room.my_room": "내 방으로",
  "room.my_room_edit": "내 방 꾸미기",

  // 꾸미기 파츠 이름 — 상점·토스트가 같이 쓴다.
  // ⚠️ 파츠 6종은 2026-08-14 에 상점에서 내려갔다(방 가구로 일원화). 이미 산 사람의 목록에는 남아 있어
  //    이름은 계속 필요하다 — 지우면 그 사람 화면에 키가 그대로 뜬다.
  "hub.part.hat_common_01": "새싹 모자",
  "hub.part.hat_common_02": "비니",
  "hub.part.shoe_common_01": "포근 양말",
  "hub.part.glasses_common_01": "동글 안경",
  "hub.part.wing_rare_01": "빛나는 날개",
  "hub.part.crown_rare_01": "작은 왕관",

  // 상단·공통
  "hub.gate_title": "로그인이 필요해요",
  "hub.gate_sub": "로그인하고 출석·상점을 이용해보세요",
  "hub.banner_login": "로그인해야 출석·상점이 작동해요",
  "hub.share": "내 랭킹 자랑",
  "hub.gift_btn": "선물",
  "hub.help_aria": "점수 획득 방법",
  "hub.coin_tip": "보유한 CARI 코인",
  "hub.mission_title": "오늘의 미션",
  "hub.confirm": "확인",

  // 오른쪽 레일
  "hub.rail.closet": "꾸미기",
  "hub.rail.title": "칭호",
  "hub.rail.invite": "초대보상",

  // 오늘의 미션 칩
  "hub.mission.attendance": "출석",
  "hub.mission.daily_learn": "오늘의 학습",
  "hub.mission.minigame": "미니게임",

  // 도크(출석 보상)
  "hub.reward_head": "출석 보상",
  "hub.attend.title": "출석 기록",
  "hub.attend.help": "사이트에 들어오면 그날 출석이 자동으로 찍혀요.",
  "hub.daily.claim": "오늘 출석하기",
  "hub.daily.done": "오늘 출석 완료",
  "hub.day_n": "{n}일",

  // 토스트
  "hub.toast.no_points_item": "코인이 부족해요: {name} ({price}코인)",

  // 구매/교환 완료 팝업
  "hub.buy.purchased": "구매 완료!",


  // 상점 모달
  "hub.shop.balance": "보유 CARI 코인",
  "hub.shop.owned": "보유중",
  "hub.shop.buy": "구매",
  "hub.shop.empty": "상점에 물건이 없어요.",
  "hub.shop.login": "로그인하면 상점을 이용할 수 있어요.",
  // ── 꾸미기(상점 + 보관함) · 캐릭터 고르기 · 튜토리얼 (2026-08-20) ──────────
  "hub.shop.free": "무료",
  "hub.closet.title": "꾸미기",
  "hub.closet.tab_shop": "상점",
  "hub.closet.tryon_on": "미리보기 중",
  "hub.closet.tryon_back": "되돌리기",
  "hub.closet.tryon_buy": "{n}코인으로 구매",
  "hub.score_line": "시즌 {n}점",
  "hub.score_top": "상위 {n}%",
  "hub.closet.preview": "미리보기",
  "hub.closet.tab_items": "보관함",
  "hub.closet.g_character": "캐릭터",
  "hub.closet.g_skin": "배경 · UI 스킨",
  "hub.closet.g_part": "아이템",
  "hub.closet.worn": "착용 중",
  "hub.closet.wear": "적용하기",
  "hub.closet.empty_character": "아직 가진 캐릭터가 없어요. 상점 탭에서 만나볼 수 있어요.",
  "hub.closet.skin_help": "스킨을 바꾸면 배경뿐 아니라 출석판·게이지·도장까지 함께 바뀌어요.",
  "hub.charpick.title": "함께할 캐릭터를 골라주세요",
  "hub.charpick.sub": "한 명만 고를 수 있어요. 고른 캐릭터는 Lv.1부터 함께 자라요.",
  "hub.charpick.g_m": "남성",
  "hub.charpick.g_f": "여성",
  "hub.charpick.go": "{name}(으)로 시작하기",
  "hub.charpick.pick_first": "캐릭터를 먼저 골라주세요",
  "hub.charpick.note": "나중에 상점에서 다른 캐릭터를 얻으면 보관함에서 언제든 바꿀 수 있어요.",
  "hub.tut.welcome_t": "CARI 허브에 오신 걸 환영해요",
  "hub.tut.welcome_b": "여기는 캐릭터와 함께 지내는 공간이에요. 어디에 뭐가 있는지 잠깐만 살펴볼게요.",
  "hub.tut.mission_t": "오늘의 미션",
  "hub.tut.mission_b": "하루에 세 가지를 하면 시즌 점수가 쌓여요. 점수는 랭킹을 매기는 값이에요.",
  "hub.tut.closet_t": "꾸미기",
  "hub.tut.closet_b": "모은 코인으로 캐릭터와 배경 스킨을 사고, 보관함에서 갈아입을 수 있어요.",
  "hub.tut.stamp_t": "출석 도장",
  "hub.tut.stamp_b": "사이트에 들어오면 출석이 저절로 찍혀요. 며칠째 왔는지 여기서 보고, 7일을 채우면 보너스 CARI 코인을 받아요.",
  "hub.tut.prev": "이전",
  "hub.tut.next": "다음",
  "hub.tut.done": "시작하기",
  "hub.tut.skip": "건너뛰기",
  // 레벨업 축하(2026-08-26). title 은 6개국어 모두 같은 영문이다 — 게임에서 'LEVEL UP' 은
  // 이름에 가깝고, 언어마다 다르게 옮기면 같은 연출이 화면마다 다른 이름으로 불린다.
  // ⚠️ next = 여러 레벨을 뛰어 축하가 이어질 때의 버튼. 마지막 한 번만 ok('확인')다.
  "hub.lvup.title": "LEVEL UP",
  "hub.lvup.before": "이전",
  "hub.lvup.now": "지금",
  "hub.lvup.ok": "확인",
  "hub.lvup.next": "다음",
  "hub.err.invalid_character": "선택할 수 없는 캐릭터예요",
  "hub.err.invalid_kind": "적용할 수 없는 종류예요",
  "hub.err.invalid_part": "적용할 수 없는 아이템이에요",
  // ⚠️ 캐릭터 이름은 **임시값**이다 — 그림이 아직 없어서 계열을 A·B·C 로만 부른다.
  //    그림이 도착하면 여기 이름만 갈면 된다(키는 절대 바꾸지 말 것 — 소유·장착이 키로 돌아간다).
  "hub.part.char_a_m": "한국풍 캐릭터(남)",
  "hub.part.char_a_f": "한국풍 캐릭터(여)",
  "hub.part.char_b_m": "캐릭터 B · 남",
  "hub.part.char_b_f": "캐릭터 B · 여",
  "hub.part.char_c_m": "캐릭터 C · 남",
  "hub.part.char_c_f": "캐릭터 C · 여",
  "hub.part.skin_meadow": "초원",
  "hub.part.skin_palace_day": "고궁 · 낮",
  "hub.part.skin_palace_night": "고궁 · 밤",

  // 쿠폰함
  "hub.coupon.title": "쿠폰함",
  "hub.coupon.discount": "{n}% 할인",
  "hub.coupon.sub": "Lv.{n} 달성 보상",
  "hub.coupon.used": "사용함",
  "hub.coupon.have": "보유",
  "hub.coupon.empty": "아직 모은 쿠폰이 없어요. 레벨업하면 할인 쿠폰을 받아요!",
  "hub.coupon.login": "로그인하면 쿠폰함이 보여요.",

  // 칭호
  "hub.title.title": "칭호",
  "hub.title.empty": "아직 획득한 칭호가 없어요 — 인증서에 합격하면 채워져요",
  "hub.title.login": "로그인하면 칭호 보관소가 보여요.",

  // 점수 획득 방법
  "hub.earn.title": "점수 · 코인 획득 방법",
  "hub.earn.lead": "다양한 활동에 참여하고 점수를 모아 랭킹에 도전하세요!",
  "hub.earn.col_act": "활동 항목",
  "hub.earn.col_pt": "획득 점수",
  "hub.earn.pt": "+{n}점",
  "hub.earn.limit": "일 {n}회 · 시즌 최대 {max}점",
  "hub.earn.lv_head": "레벨테스트",
  "hub.earn.lv_sub": "레벨 클리어 시",
  "hub.earn.foot": "7단계를 모두 통과하면 {a}점 · 활동까지 더한 시즌 만점은 {b}점이에요.",
  "hub.earn.row.attendance": "출석하기",
  "hub.earn.row.daily_learn": "오늘의 학습 완료",
  "hub.earn.row.minigame": "미니게임 플레이",
  "hub.earn.sec_score": "시즌 점수",
  "hub.earn.sec_coin": "CARI 코인",
  "hub.earn.coin_lead": "상점에서 캐릭터와 방을 꾸미는 데 쓰는 재화예요. 랭킹 점수와는 다른 지갑입니다.",
  "hub.earn.col_coin": "획득 코인",
  "hub.earn.coin_pt": "+{n}코인",
  "hub.earn.coin_any": "받은 만큼",
  "hub.earn.coin.daily": "출석 또는 오늘의 학습",
  "hub.earn.coin.stamp": "7일 출석 도장 완성",
  "hub.earn.coin.referral": "친구 초대 · 초대코드 등록",
  "hub.earn.coin.gift": "친구에게 선물 받기",
  "hub.earn.coin_note.daily": "하루 1회 · 둘 중 먼저 한 쪽",
  "hub.earn.coin_note.stamp": "도장 7칸을 채운 날",
  "hub.earn.coin_note.referral": "초대한 쪽·쓴 쪽 양쪽 다",
  "hub.earn.coin_note.gift": "보낸 사람이 정한 금액",

  // 친구 초대 모달
  "hub.invite.title": "친구 초대",
  "hub.invite.lead": "친구와 함께 CARIS 하세요!",
  "hub.invite.help": "내 초대코드를 친구가 입력하면 둘 다 {n} CARI 코인 증정",
  "hub.invite.my_code": "내 초대코드",
  "hub.invite.copied": "복사됨",
  "hub.invite.copy": "복사",
  "hub.invite.issuing": "초대코드를 발급하는 중이에요.",
  "hub.invite.login": "로그인하면 초대코드가 발급돼요.",
  "hub.invite.redeem_head": "친구 초대코드 입력",
  "hub.invite.redeem_done": "✓ 초대코드를 등록했어요 (한 번만 가능해요)",
  "hub.invite.checking": "확인 중",
  "hub.invite.register": "등록",
  "hub.invite.hint": "친구가 알려준 초대코드를 입력하면 둘 다 {n} CARI 코인 증정",
  "hub.invite.err_not_found": "없는 초대코드예요. 다시 확인해주세요",
  "hub.invite.err_self": "내 초대코드는 쓸 수 없어요",
  "hub.invite.err_already": "이미 초대코드를 등록했어요",
  "hub.invite.ok": "등록 완료! 나와 초대해준 친구 둘 다 {n}코인을 받았어요",
  "hub.invite.fail": "등록하지 못했어요",

  // 코인 선물 모달
  "hub.gift.title": "코인 선물",
  "hub.gift.balance": "보유 코인",
  "hub.gift.received": "받은 선물",
  "hub.gift.count_n": "{n}건",
  "hub.gift.older": "이전에 받은 선물 {n}건",
  "hub.gift.send_head": "코인 보내기",
  "hub.gift.nick_label": "받는 사람 닉네임",
  "hub.gift.nick_ph": "닉네임",
  "hub.gift.amount_label": "보낼 코인",
  "hub.gift.send": "보내기",
  "hub.gift.sending": "보내는 중",
  "hub.gift.confirm_q": "{name}님에게 {n}코인을 보낼까요?",
  "hub.gift.confirm_warn": "보내고 나면 되돌릴 수 없어요.",
  "hub.gift.history": "선물 내역",
  "hub.gift.empty": "아직 주고받은 선물이 없어요.",
  "hub.gift.dir_in": "받음",
  "hub.gift.dir_out": "보냄",
  "hub.gift.sent_ok": "{name}님에게 {n}코인을 보냈어요",
  "hub.gift.err_not_found": "그런 닉네임이 없어요",
  "hub.gift.err_self_code": "내 닉네임이에요",
  "hub.gift.err_too_many": "조회가 너무 많아요. 잠시 후 다시 시도해주세요",
  "hub.gift.err_lookup": "확인할 수 없어요",
  "hub.gift.err_amount_required": "보낼 금액을 입력해주세요",
  "hub.gift.err_insufficient": "코인이 부족해요",
  "hub.gift.err_self": "나에게는 보낼 수 없어요",
  "hub.gift.err_invalid_amount": "보낼 금액이 올바르지 않아요",
  "hub.gift.err_too_fast": "같은 친구에게 너무 자주 보내고 있어요. 잠시 후 다시 시도해주세요",
  "hub.gift.err_send_fail": "보내지 못했어요",

  // 1:1 문의(마이페이지 › 문의 탭). 분류 라벨은 `inq.cat.<코드>` 로 키를 조립한다 — DB 에 든 건 코드뿐이다.
  "inq.intro": "문의하시면 확인 후 답변드립니다.",
  "inq.private": "작성자 본인과 운영자만 볼 수 있습니다.",
  "inq.write": "문의하기",
  "inq.cat.exam": "응시·시험",
  "inq.cat.payment": "결제·환불",
  "inq.cat.account": "계정",
  "inq.cat.arena": "WORLD ARENA",
  "inq.cat.etc": "기타",
  "inq.ph_title": "제목",
  "inq.ph_body": "문의 내용을 적어주세요. 응시·결제 문의는 회차와 급수를 같이 적어주시면 빠릅니다.",
  "inq.submit": "문의 등록",
  "inq.sending": "보내는 중…",
  "inq.err_fields": "제목과 내용을 모두 입력해 주세요.",
  "inq.err_login": "로그인이 필요합니다.",
  "inq.login_required": "로그인 후 이용할 수 있습니다.",
  "inq.empty": "아직 문의가 없습니다.",
  "inq.status_open": "답변 대기",
  "inq.status_answered": "답변 완료",
  "inq.new_answer": "새 답변",
  "inq.answer_at": "답변 · {d}",
  "inq.no_answer": "아직 답변이 등록되지 않았습니다.",
}

export default KO
