// ⚠️ 자동 생성 아님 — 손으로 고쳐도 된다. 다만 **6개 언어 파일의 키 집합은 같아야 한다**.
//    (없는 키는 tr() 이 한국어로 폴백하고, 한국어에도 없으면 키 문자열이 그대로 화면에 뜬다.)
//
// 언어별로 파일을 쪼갠 이유 (2026-08-14):
//   예전엔 i18n.tsx 한 파일에 키 × 6개국어가 전부 있었다(490KB). 이 파일은 최상위 프로바이더라
//   **모든 화면이 무조건** 6개국어를 통째로 받아 파싱했고, 첫 진입 JS 의 절반 가까이가 이거였다.
//   지금은 한국어만 정적으로 싣고(기본 언어 + 폴백) 나머지는 그 언어를 고른 사람만 받는다.
//
// ⚠️ 이 파일을 다른 데서 직접 import 하지 말 것 — 조회는 i18n.tsx 의 tr()/useT() 하나로만.
const ZH: Record<string, string> = {
  "common.home": "主页",
  "common.close": "关闭",
  "common.cancel": "取消",
  "common.ranking": "排行榜",
  "common.hub": "角色中心",
  "common.my_home": "My Home",
  "common.leveltest": "WORLD ARENA",
  "common.login_google": "使用 Google 登录",
  // 로그인 수단이 여럿(구글·카카오)이라 특정 수단이 아니라 로그인 페이지로 보낼 때 쓰는 라벨
  "common.login": "登录",
  "common.logout": "退出登录",
  "common.retry_test": "重新参加测试",
  "common.loading": "加载中…",

  "fab.guest": "访客",
  "fab.account": "我的账户",
  "fab.loggedin": "已登录 · 段位已保存",
  "fab.savehint": "登录后即可保存段位",
  "fab.login_needed": "需要登录",
  "fab.brand": "GARA · WORLD ARENA",
  "fab.language": "语言",
  "fab.admin": "管理员页面",
  "fab.edit_name": "修改昵称",
  "fab.save": "保存",
  "fab.change_avatar": "更换角色",
  "fab.upload_image": "上传图片",
  "fab.upload_fail": "上传失败",

  // 온보딩/지역 (ISO 3166-2:KR 17 시도)
  "region.KR-11": "首尔特别市",
  "region.KR-26": "釜山广域市",
  "region.KR-27": "大邱广域市",
  "region.KR-28": "仁川广域市",
  "region.KR-29": "光州广域市",
  "region.KR-30": "大田广域市",
  "region.KR-31": "蔚山广域市",
  "region.KR-41": "京畿道",
  "region.KR-42": "江原特别自治道",
  "region.KR-43": "忠清北道",
  "region.KR-44": "忠清南道",
  "region.KR-45": "全北特别自治道",
  "region.KR-46": "全罗南道",
  "region.KR-47": "庆尚北道",
  "region.KR-48": "庆尚南道",
  "region.KR-49": "济州特别自治道",
  "region.KR-50": "世宗特别自治市",
  "onboarding.title": "您想从哪个地区加入？",
  // 지역 목록이 없는 나라용 제목 — 화면에 지역 칸이 없는데 "어느 지역에서" 라고 물으면 없는 걸 묻는 말이 된다.
  "onboarding.title_country": "您想从哪个国家加入？",
  // 1단계(설명) — 왜 지역을 받는지. 짧게, 크게.
  "onboarding.intro_title": "按地区进行排名",
  "onboarding.intro_body": "您将与同地区、同国家的人一同排名。",
  "onboarding.intro_next": "开始",
  "onboarding.country": "国家",
  "onboarding.region": "地区",
  // 연령대 — 밴드만(정확한 나이는 안 받는다). '공개 안 함' 도 하나의 답으로 저장한다.
  "onboarding.age": "年龄段",
  // 지역을 이미 확정한 회원이 연령대만 받으러 들어왔을 때의 제목(지역 질문이 없는 화면)
  "onboarding.age_title": "请告诉我们您的年龄段",
  "onboarding.age_hint": "仅用于统计，不会询问具体年龄。",
  "onboarding.age_10s": "20岁以下",
  "onboarding.age_20s": "20–29岁",
  "onboarding.age_30s": "30–39岁",
  "onboarding.age_40s": "40–49岁",
  "onboarding.age_50s": "50–59岁",
  "onboarding.age_60s": "60岁以上",
  "onboarding.age_private": "不愿透露",
  // ⚠️ 2026-08-12: '영영 못 바꾼다' 가 아니다 — 마이페이지에서 딱 한 번 바꿀 수 있다. 문구가 규칙보다
  //    무섭게 남아 있으면 사용자가 이 화면에서 얼어붙는다(실제 규칙 = set-region 의 change 경로).
  "onboarding.lock_warn": "之后只能在“我的页面”更改一次。",
  "onboarding.start": "就此开始",
  "onboarding.region_prefill_hint": "根据 IP 估算，请确认或修改。",
  "mypage.region_locked": "地区和国家无法更改。如有误分配请联系我们。",
  // 국가·지역 1회 변경(2026-08-12). 닉네임 1회 변경과 같은 성격이라 문구 결도 맞춘다.
  "mypage.region_change_once": "更改国家和地区（1 次）",
  "mypage.region_change_warn": "保存后将无法再更改，机会仅有一次。",
  "mypage.region_change_used": "您已用完唯一一次更改机会。",
  "mypage.region_none": "该国家暂不划分地区。",
  "mypage.profile_title": "我的信息",

  "landing.lead": "立即查看你的实力。",
  "landing.cta": "参加 CARIS",
  // 레벨 추천(무료 진단 검색창) — /test/* 모듈용
  "reco.heading": "用一句话描述你的 AI 使用水平",
  "reco.placeholder": "你的 AI 实力有多强？",
  "reco.button": "推荐等级",
  "reco.loading": "分析中…",
  // 홈 검색 라우터(route-query) — 의미 기반 페이지 이동
  // 뒤에 붙던 예시(WORLD ARENA·시험안내·문의…)는 뺐다 — 메인 검색창은 질문 한 줄만 둔다.
  "route.placeholder": "您在找什么？",
  "route.notfound": "无效的搜索词，请重新输入。",
  // CARIS ARENA 이식 잔여 키 (gara-cbt에 없던 7개)
  "rank.title": "排行榜",
  "report.btn": "🚩 报告问题",
  "report.placeholder": "请告诉我们此题的错别字或错误",
  "report.send": "发送",
  "report.cancel": "取消",
  "report.sent": "✅ 已收到反馈，谢谢！",
  "report.fail": "发送失败",
  "reco.result": "根据描述，推荐 Lv.{n} {name}",
  "reco.pct_range": "根据描述，你大约处于世界前 {lo}~{hi}%",
  "reco.result_alt": " · 也可挑战 Lv.{n}",
  "reco.error": "推荐失败，请稍后再试。",
  "reco.start_lv": "从 Lv.{n} 开始",
  "reco.unclear": "没看懂。请用一句话描述你的水平。(例如：完全新手 / 我很会自动化)",
  "nav.about": "全球 AI 机器人协会",
  "nav.privacy": "隐私政策",
  "nav.more": "了解更多",
  "nav.lecture": "课程",
  "nav.terms": "服务条款",
  "terms.title": "服务条款",
  "terms.todo": "内容准备中。",
  "withdraw.title": "注销账户",
  "withdraw.desc": "注销后账户将被停用，保留 {d} 天后销毁会员信息。在此之前可重新登录并恢复。",
  "withdraw.button": "注销账户",
  "withdraw.confirm": "确定要注销吗？账户将被停用，{d} 天后销毁会员信息。在此之前可重新登录并恢复。",
  "withdraw.done": "已完成注销。感谢您的使用。",
  "withdraw.failed": "处理出错，请稍后重试。",
  "withdraw.gate_title": "该账户已申请注销",
  "withdraw.gate_body": "该账户已申请注销。在 {d} 天保留期内恢复，等级、记录和已购教材都会原样回来。若不恢复，会员信息将被销毁，此账户将无法再次登录。",
  "withdraw.gate_left": "还剩 {n} 天可以恢复",
  "withdraw.gate_purge_on": "将于 {date} 销毁",
  "withdraw.gate_restore": "恢复我的账户",
  "withdraw.gate_logout": "不恢复，直接退出登录",
  "withdraw.restoring": "正在恢复…",
  "withdraw.restore_failed": "恢复失败，请稍后重试。",
  "lecture.title": "课程页面",
  "lecture.sub": "课程内容正在准备中。",

  "about.title": "全球 AI 机器人协会",
  "about.eyebrow": "Global AI & Robotics Association",
  "about.tag": "在 AI 与机器人时代，帮助人类适应变化、持续成长的机构。",
  "about.desc": "引领人工智能与机器人技术融合新标准的全球性协会。",
  "about.note": "协会会员及会员单位招募、活动资讯等详情将陆续公布。",

  // 레벨선택 페이지 제목 — 아레나 지도(WORLD ARENA)와 겹치지 않게 런처 버튼과 같은 '레벨 테스트'로.
  "lv.title": "等级测试",
  "lv.rule_btn": "等级规则",
  // 북두칠성 별자리(레벨 선택) 아래 한 줄 안내 — 인증서와 같은 별 순서라는 걸 알려준다
  "lv.dipper_hint": "点击星星选择等级 — 已达成的等级会亮起金色",
  // 닉네임 — 최초 1회 설정(/onboarding/nickname) + 마이페이지에서 1회 변경
  "nick.title": "请设置昵称",
  "nick.body": "该名称会显示在排行榜、聊天和认证书上。请设置一个用来代替谷歌账号实名的名称。",
  "nick.label": "昵称",
  "nick.placeholder": "2~12 个字符",
  "nick.rule": "{min}~{max} 个字符 · 仅限文字、数字和下划线(_) · 不可使用空格与符号。",
  "nick.once_warn": "之后昵称只能修改一次。",
  "nick.confirm": "确定",
  "nick.saving": "保存中…",
  "nick.change_once": "修改（剩 1 次）",
  "nick.last_chance": "这是唯一一次修改机会，确定后无法再改。",
  "nick.used_up": "修改次数已用完",
  "nick.err_length": "请输入 2~12 个字符。",
  "nick.err_shape": "仅可使用文字、数字和下划线(_)。",
  "nick.err_taken": "该昵称已被使用。",
  "nick.err_reserved": "该昵称不可使用。",
  "nick.err_locked": "修改次数已用完，请联系客服。",
  "nick.err_failed": "保存失败，请稍后再试。",
  // 레벨테스트 인증서(/test/certificate) — 무료, 누르면 바로 발급
  "lcert.issue_btn": "领取认证书",
  "lcert.print": "📄 保存为 PDF / 打印",
  "lcert.no_name": "未设置昵称",
  "lcert.empty": "尚无可领取的认证书。在等级测试中通过一个等级，旅程的第一颗星就会点亮。",
  "lcert.load_failed": "无法加载认证书，请稍后再试。",
  "lcert.go_test": "去参加等级测试",
  // 문항 수는 레벨 구간별(10/20/30)이고 제한시간(분)이 그 수와 같다. 승급은 개수가 아니라 정답률. 강등은 없다.
  "lv.rule_up": "Lv.1~4 正确率 {p1}% 以上、Lv.5~7 {p2}% 以上升级",
  "lv.rule_nodown": "即使分数很低，等级也不会下降",
  "lv.rule_daily": "每天可应试 {n} 次，升级可再加 1 次",
  // 레벨 선택(D안) — '지금 도전' 카드
  "lv.prev_level": "上一等级",
  "lv.next_level": "下一等级",
  "lv.start_now": "开始应试 →",
  "lv.fact_q": "{n} 题",
  "lv.fact_min": "{n} 分钟",
  "lv.fact_cut": "答对 {n} 题升级",
  "lv.left_today": "今日剩 {n} 次 · 升级再加 1 次",
  "lv.daily_limit": "今天的应试次数已用完。明天再来，或升级可再获得 1 次。",
  "lv.rule_note": "Lv.{max} 为最高级",
  "lv.login_to_save": "登录后才能保存测试结果",
  "lv.sub_tail": "按所选难度出题 · 登录用户每 {d} 天 1 次",
  "lv.rec_firsttime": "第一次的话，从 Lv.3 轻松开始吧",
  "lv.rec_for_user": "按当前实力推荐 Lv.{c}",
  "lv.rec_challenge": " · 也可以挑战 Lv.{n}",
  "lv.tag_rec": "推荐",
  "lv.tag_challenge": "挑战",
  "lv.locked": "已锁定",
  "lv.locked_hint": "升级后解锁",

  "lv.select": "选择 →",
  "lv.preparing": "准备中…",
  // 문제은행이 아직 없는 레벨(COMING_SOON_LEVELS)의 카드 문구
  "lv.coming_soon": "即将开放",
  "lv.start_failed": "启动失败。",
  "lv.1.name": "入门 I",
  // Lv.1 = 3축(다른 레벨은 6축) — AI 프롬프트 활용 · AI 도구 이해 · AI를 활용한 문제해결
  "lv.1.desc": "AI 工具理解、提示词运用与运用 AI 解决问题入门",
  "lv.2.name": "入门 II",
  "lv.2.desc": "商务与日常提示词、提示词技巧、AI 工具运用与生产力协作",
  "lv.3.name": "基础",
  "lv.3.desc": "生成式 AI 素养与伦理，提示工程基础",
  "lv.4.name": "中级",
  "lv.4.desc": "生成式 AI 进阶，用 Python 将 AI 与硬件软件化连接",
  "lv.5.name": "高级",
  "lv.5.desc": "生成式 AI 高级（LLM·RAG·应用开发）、基础视觉 AI（目标识别）、C/C++ 基础",
  "lv.6.name": "进阶",
  "lv.6.desc": "STM32 精密控制、ROS2 系统集成、PLC 编程、工艺仿真",
  "lv.7.name": "大师",
  "lv.7.desc": "贯通数字孪生与集群机器人的终极掌握",

  "test.nodata": "找不到进行中的测试数据。刷新将使本次测试作废。",
  "test.restart": "重新开始",
  // 응시 화면(레벨테스트·CBT 공용) 키보드 단축키 안내. 마우스 있는 기기에서만 노출.
  //   hint_nav = 보기가 없는 주관식 문항용(숫자키 안 먹음).
  "kbd.hint": "1–{n} 选择 · ←→ 切换",
  "kbd.hint_nav": "←→ 切换题目",
  // 응시 화면 상단 이탈 카운터. '전체화면 유지' 안내 문구는 뺐다 — 시작 전 경고 게이트에서 이미 말하고,
  // 응시 중 상단바는 숫자(문항·시간·이탈) 셋만 크게 보이는 게 목적.
  "test.guard": "离开 {v}/3",
  "test.quit": "✕ 退出",
  "test.quit_confirm": "要退出测试吗？\n当前作答不会保存，本次应试将作废。",
  "test.solved": "已答 {a}/{t}",

  // 시작 전 경고 게이트 (TestRunner)
  "intro.title": "开始前请务必阅读",
  "intro.meta": "Lv.{lv} · 共 {q} 题 · 限时 {min} 分钟",
  // 응시 전 경고 화면의 시험 정보 줄(규칙 목록과 같은 행 모양으로 위에 붙는다)
  "intro.fact_q": "共 {q} 题",
  "intro.fact_min": "限时 {min} 分钟",
  "intro.anticheat": "🛡️ 防作弊系统运行中 🛡️",
  "intro.fullscreen": "必须全屏模式",
  "intro.rule_exit": "切换标签、移动窗口或退出全屏将触发警告",
  "intro.rule_void": "累计 {m} 次警告将自动作废",
  "intro.rule_block": "限制复制、右键和拖拽功能",
  "intro.start": "全屏开始 →",
  "intro.cancel": "取消",
  // 이동 한 쌍은 화살표를 같이 단다 — 한쪽만 달면 짝으로 안 읽힌다. 상단 키보드 안내(←→)와도 맞는다.
  "test.prev": "← 上一题",
  "test.next": "下一题 →",
  "test.submit": "提交",
  "test.submitting": "提交中…",
  "test.submit_confirm_unanswered": "还有 {n} 道题未作答。\n仍要提交吗？",
  "test.submit_confirm": "确定要最终提交答案吗？\n提交后将无法修改。",
  "test.submit_failed": "提交失败。",
  "void.title": "测试已作废",
  "void.body": "离开屏幕累计 3 次，被判定为作弊。本次应试",
  "void.body_strong": "不会被保存，也不计入评分。",
  "void.restart": "重新开始",
  "void.home": "返回主页",
  "warn.left": "检测到离开屏幕（{n}/{m}）。{r}",
  "warn.tab": "切换了标签页。",
  "warn.blur": "窗口失去焦点。",
  "warn.fs": "退出了全屏。",

  "result.loading": "正在加载结果…",
  "result.notfound": "未找到结果。",
  "result.load_failed": "加载结果失败。",
  "result.level_result": "等级 {n} 结果",
  "result.accuracy": "正确率 {p}%",
  // ⚠️ 여기 적는 건 **로그인하면 실제로 열리는 것**이어야 한다(= UnlockedPanel 이 그리는 것).
  //    옛 문구 '티어 · 6축 누적 분석 · 오답 해설' 은 없는 기능 두 개를 미끼로 걸고 있었다 —
  //    티어는 2026-08-04 제거, 오답노트는 결과창에서 제거됐다(Result.tsx 의 UnlockedPanel 끝 주석).
  //    UnlockedPanel 구성이 바뀌면 이 줄도 같이 고칠 것.
  "locked.title": "晋级判定 · 6 维累计分析 · 学习处方",
  "locked.peek": "就快好了 — 1 秒后解锁",
  "locked.desc": "登录后此结果将计入累计评分，并解锁你刚看到的分数详情。",
  "locked.blocked": "最近 3 天内已有应试记录，因此本结果未关联账户。3 天后再考即可计入累计评分。",
  "locked.cta": "使用 Google 登录查看分析",
  "result.overall": "累计综合评分 {o} / 100",
  "result.placing": " · 定级中",
  "result.promoted": "晋级！",
  // 승급했을 때만 뜨는 결과창 CTA — 누르면 다음 레벨 응시를 바로 시작한다(응시 전 경고 화면으로 이동).
  "result.next_level": "挑战 Lv.{n} →",
  "rank.cur_level": "当前等级 · Lv.{n}",
  "db.points": "排名分数 {p}",
  "db.skill_score": "实力分数",
  "db.activity_score": "活动分数",
  "db.season_total": "赛季总分",
  // 랭킹 점수 = 레벨 + 맞힌 개수 (히어로 옆 인라인 분해). 수치는 scoring.ts 와 일치 — 규칙 바뀌면 같이 갱신.
  "db.score_break_h": "分数如何计算",
  "db.eq_level": "等级",
  "db.eq_correct": "答对数",
  "db.eq_points": "分数",
  "db.howto_up": "答对 16 题以上升级，分数会大涨",
  "db.howto_within": "同级时答对越多，分数一点点上升",
  "result.radar_title": "各领域测试结果",
  "result.legend_thistest": "本次",
  "result.legend_prevtest": "上次同等级",
  "result.legend_me": "我",
  "result.legend_avg": "段位平均",
  "result.legend_prev": "上次结果",
  "result.delta_title": "本次测试变化",
  "result.delta_legend": "▲ 上升 / ▼ 下降",
  "result.answers_title": "题目解析 · 错题本",
  // 결과창 하단 이북 추천 칸(eBook Store 로 연결)
  "result.books_title": "推荐 E-BOOK",
  "result.books_more": "Learning Library",
  "result.books_read": "立即学习",
  "result.correct": "正确",
  "result.wrong": "错误",
  "result.mychoice": "（我的选择）",

  "rx.title": "测试分析与下一步",
  "rx.promote": "距离 {tier} 还差 {p} 分",
  "rx.master": "已达最高段位！🎉",
  "rx.focus": "重点提升方向：[{axis}] 领域",
  "rx.focus_peer": "（比同伴平均低 {gap}↓）",
  "rx.weak": "{axis} 比 {tier} 平均低 {gap}",
  "rx.next_up": "做得好！为挑战 Lv.{n}，请在 Learning Library 中学习。",
  "rx.next_same": "再巩固一次 Lv.{n}",
  "rx.next_down": "在 Lv.{n} 打牢基础",
  // 승급 못 했을 때(유지) 처방 둘째 줄 — 약점 영역을 짚고 교재로 유도한다.
  //   ⚠️ 이북에 레벨·영역 메타데이터가 없어 '이 축을 다루는 책'을 특정하지 못한다. 문구로만 연결하고
  //      실제 목록은 결과창 아래 추천 이북 칸(스토어 노출순)이다. 메타데이터가 생기면 여기서 매칭할 것.
  "rx.study_weak": "补强这一领域，对整体实力提升帮助最大。",
  "rx.study_pass": "为通过 Lv.{n}，请在 Learning Library 中学习。",
  "rx.study_cta": "👉 查看推荐 E-BOOK",
  "tip.prompt": "练习在提示词中给出输出格式、示例，并把任务分步骤下达指令。",
  "tip.model": "了解每类任务适合哪种 AI，以及各模型不擅长什么。",
  "tip.verify": "养成核对 AI 来源与事实的习惯，不要盲目相信。",
  "tip.automation": "学习用 AI 和工具自动化重复性工作。",
  "tip.data": "练习用 AI 整理和分析表格/数据。",
  "tip.ethics": "学习在保护隐私、版权与安全的前提下安全使用 AI。",
  "resnav.top": "↑ 回到顶部",
  "resnav.label": "题目（正确·错误）",

  "rank.unplaced": "未定级",
  "rank.guest_bar": "登录后显示我的排名",
  "rank.guest_login": "登录",
  "rank.skill_sub": "累计评分 {o} · 应试 {n} 次",
  "rank.no_record": "还没有应试记录 — 做个测试来定级",
  "rank.login_hint": "登录后你的累计段位会显示在这里",
  "rank.top": "前 {p}%",
  "rank.top_label": "前",
  "rank.among": "在所有应试者中",
  "rank.me_pct": "我 · {v}%",
  "rank.league": "{tier} 联赛",
  "rank.league_pop": "联赛人数",
  "rank.tier_total": "{n} 名参赛者",
  "rank.my_rank": "我的排名",
  "rank.hall": "名人堂",
  "rank.loading_more": "加载中…",
  "rank.hall_sub": "总榜 TOP 10",
  "rank.global_rank": "总排名",
  "rank.global_top": "总前",
  "rank.to_promote": "距升级",
  "rank.to_promote_pt": "{p} 分",
  "rank.promotion_zone": "升级区间",
  "rank.top_tier": "最高段位",
  "rank.pt": "{n} 分",
  "rank.nth": "第 {n} 名",
  "rank.trend_title": "排名走势",
  "rank.trend_empty": "这段时间没有记录。",
  "rank.you": "我",
  "rank.cta_test": "做测试获得排名",
  // 집계 리더보드(지역·국가·학교) — 협력 서사(하락/꼴찌 없음). /arena 지도 전용(랭킹 탭에서는 제거됨)
  "rank.coop_header": "我们一起向上",
  // 랭킹 탭 = World / 내 국가 / 내 지역. 국가·지역 탭 라벨은 실제 이름(대한민국·서울)으로 치환되고,
  // 아래 tab_region·tab_country 는 코드가 없을 때(비로그인·온보딩 전) 폴백이다.
  // ⚠️ 'World' 는 WORLD ARENA 와 같은 **브랜드 영문 고정**이다(2026-08-11) — 6개국어 모두 같은 글자.
  "rank.tab_world": "World",
  "rank.tab_region": "我的地区",
  "rank.tab_country": "我的国家",
  "rank.tab_school": "学校",
  "rank.scope_sub": "{name} TOP 10",
  "rank.scope_guest": "登录后可查看所在国家·地区排名",
  "rank.scope_no_region": "设置国家·地区后即可查看此排名",
  "rank.scope_set_region": "设置地区",
  "rank.next_gap": "距下一档 {n} 分",
  "hub.today_todo": "今日待办",
  "hub.todo_attendance": "签到",
  "hub.todo_problem": "今日一题",
  "hub.todo_learn": "DAILY QUIZ",
  "hub.todo_game": "小游戏",
  "rank.win_daily": "今日",
  "rank.win_season": "赛季",
  "rank.aggregating": "统计中",
  "rank.avg": "平均",
  "rank.active_today": "今日参与率",
  "country.KR": "韩国",

  "db.title": "我的记录",
  "db.empty": "还没有提交过测试。",
  "db.start": "开始测试",
  "db.stat_maxlevel": "最高等级",
  "db.stat_maxlevel_d": "挑战的最高",
  "db.stat_attempts": "累计应试",
  "db.unit_times": "次",
  "db.placed_before": "定级前",
  "db.recent": "最近 {d}",
  "db.stat_avgacc": "平均正确率",
  "db.recent_n": "最近 {n} 次",
  "db.stat_lastchange": "最近变化",
  "db.last_lp": "上次应试 LP",
  "db.trend_title": "排名走势",
  // 랭킹 추이 기간 선택 — 시즌 = 6개월
  "db.trend_1w": "1 周",
  "db.trend_3m": "3 个月",
  "db.trend_season": "赛季",
  "db.trend_season_hint": "赛季 = 6 个月",
  "db.trend_empty": "该期间没有应试记录。",
  "db.radar_title": "领域均衡",
  "db.radar_me": "我的",
  "db.radar_avg": "等级平均",
  "db.vs_avg": "较平均",
  "db.cum_rating": "累计",
  "db.growth_title": "各领域成长",
  // 대시보드 하단 = 승급 기록(옛 '응시 기록'은 삭제). 승급한 응시만 보여준다.
  "db.promo_title": "升级记录",
  "db.promo_total_n": "共升级 {n} 次",
  "db.promo_empty": "还没有升级记录。升级后会显示在这里。",
  "db.hist_correct": "正确 {a}/{t}",

  "cal.summary": "最近 6 个月 · {n} 天活动",
  "cal.active": "活动日",
  "cal.days_active": "本月 {n} 天活动",
  // 활동 기록 달력은 출석만 표시한다 → 문구도 '활동'이 아니라 '출석'
  "cal.days_attended": "本月签到 {n} 天",
  "cal.weekdays": "日,一,二,三,四,五,六",
  "cal.did": "有活动",
  "cal.none": "无活动",
  "cal.dominant_attendance": "签到",
  "cal.dominant_learn": "学习",
  "cal.dominant_minigame": "游戏",
  "cal.dominant_leveltest": "应试",
  "cal.full_combo": "全勤!",

  "auth.processing": "正在登录…",

  "tier.iron": "黑铁",
  "tier.bronze": "青铜",
  "tier.silver": "白银",
  "tier.gold": "黄金",
  "tier.platinum": "铂金",
  "tier.diamond": "钻石",
  "tier.master": "大师",

  "cat.prompt": "提示词设计",
  "cat.prompt.short": "提示词",
  "cat.model": "模型·工具理解",
  "cat.model.short": "模型·工具",
  "cat.verify": "验证·批判性思维",
  "cat.verify.short": "验证·批判",
  "cat.automation": "自动化·工作流",
  "cat.automation.short": "自动化",
  "cat.data": "数据应用",
  "cat.data.short": "数据",
  "cat.ethics": "伦理·安全",
  "cat.ethics.short": "伦理·安全",
  "gate.seb_not_ready": "安全浏览器尚未配置完成。请稍后重试或联系管理员。",
  "gate.seb_opened_q": "安全浏览器打开了吗？",
  "gate.seb_opened_desc": "稍后会自动打开。若未打开，请在下方安装后重新启动。",
  "gate.seb_install_new": "📥 安装 SEB（新窗口）",
  "gate.title": "CARIS",
  "gate.fullname": "AI·机器人融合能力资格考试\nCertification for AI & Robotics Integrated Skills (CARIS)",
  "gate.sub": "全球 AI·机器人协会公认 CARIS（CBT）",
  "gate.meta_questions": "题",
  "gate.meta_minutes": "分钟",
  "gate.meta_choices": "选一",
  "gate.note_release": "• 应试后 {d} 天公布评分结果。",
  "gate.note_block": "• 考试期间截屏、复制和离开屏幕将被阻止并记录。",
  "gate.note_pc": "• 无法在手机或平板上应试，仅可在 PC（台式机·笔记本）上应试。",
  "gate.btn_seb": "用安全浏览器开始应试",
  "gate.btn_start": "参加 CARIS",
  "gate.my_tickets": "我的应试券",
  "gate.no_ticket": "目前没有可应试的考试。报名后会显示在这里。",
  "gate.btn_login": "登录后应试",
  "gate.login_hint": "为核实身份，CARIS 需先用 Google 登录后应试。",
  "gate.check_link": "🧪 第一次？测试考试环境（预检）→",
  "gate.instr_title": "重要须知",
  "gate.login_modal_title": "需要登录",
  "gate.login_modal_desc": "您尚未登录。登录后即可应试。",
  "prep.step_exam": "检定说明",
  "prep.exam_lead": "本次为 {exam} 检定。请确认以下科目、考试构成与合格标准。",
  "prep.exam_unknown": "未能找到该准考证的等级信息，因此无法显示检定说明。以下准备步骤可照常进行。",
  "prep.step_guide": "须知",
  "prep.step_notice": "注意事项",
  "prep.step_seb": "安全程序",
  // 유의사항 스텝 — SEB 부정행위 방지 기능 안내(12개)
  "prep.af_lead": "本次考试在安全浏览器（SEB）中进行，并应用以下防作弊措施。",
  "prep.af1": "强制全屏锁定",
  "prep.af2": "禁止切换应用/窗口",
  "prep.af3": "禁止截屏/录屏",
  "prep.af4": "禁用剪贴板（复制/粘贴）",
  "prep.af5": "禁止右键/拖拽",
  "prep.af6": "禁止刷新/后退",
  "prep.af7": "移除地址栏",
  "prep.af8": "提交后自动关闭",
  "prep.af9": "禁止副显示器",
  "prep.af10": "禁止虚拟机（VM）运行",
  "prep.af11": "SEB（Safe Exam Browser）伪装验证",
  "prep.af13": "禁用开发者工具",
  "prep.af12": "其他经协会认定为防作弊系统的方法",
  "prep.step_menu": "菜单说明",
  "prep.step_practice": "答题练习",
  "prep.step_ready": "准备就绪",
  "prep.chk_pc": "PC（台式机）环境",
  "prep.chk_screen": "屏幕尺寸（宽 1024px 以上）",
  "prep.chk_fs": "支持全屏",
  "prep.chk_net": "网络连接",
  "prep.err_seb_not_ready": "安全浏览器尚未配置完成。请联系管理员。",
  "prep.err_start": "无法开始考试。",
  "prep.guide_lead": "这是 CARIS（CBT）应试界面。请完整阅读以下须知。",
  "prep.guide_li1": "共 {q} 题，限时 {min} 分钟，四选一选择题。",
  "prep.guide_li2": "时间结束后将自动提交。",
  "prep.guide_li3": "评分结果在提交 {d} 天后公布。",
  "prep.guide_li4": "本考试仅限 PC（台式机/笔记本）。",
  "prep.resume_title": "考试中断时的重新连接与自动提交规定",
  "prep.resume_li1": "因停电、网络故障等导致断线时，该次应试将被暂时锁定。请通过 1:1 咨询告知，我们会核对中断记录后予以恢复，核实可能需要若干工作日。",
  "prep.resume_li2": "恢复后，可按中断时点的答案与剩余时间继续应试。",
  "prep.resume_li3": "重新应试必须在整个考试运营期间内进行。",
  "prep.resume_li4": "考试运营期间及截止时间均以韩国标准时间（UTC+9）为准。",
  "prep.notice_lead": "请务必遵守以下注意事项。违反可能在评分中受到不利影响。",
  "prep.notice_li3": "如有未作答的题目则无法提交，并跳转到未答题目。",
  "prep.notice_li4": "建议仅使用 1 台显示器，安全浏览器会遮挡额外屏幕。",
  "prep.notice_li5": "一经确认作弊，应试可能被作废。",
  "prep.seb_running": "✅ 正在安全浏览器中运行。请继续下一步。",
  "prep.seb_install_btn": "安装安全程序（SEB）",
  "prep.seb_li1": "安装时 Windows 显示「发布者: ETH Zürich」即为正常。",
  "prep.seb_li2": "「Windows 已保护你的电脑」→ 更多信息 → 运行（正常步骤）。",
  "prep.seb_li3": "安装后，在最后一步点击「开始考试」即可用安全浏览器打开。",
  "prep.menu_lead": "考试界面构成如下。",
  "prep.menu_li1": "左侧：题目与选项；顶部显示剩余时间。",
  "prep.menu_li2": "右侧：答题卡（按题号选 1~4）",
  "prep.menu_li3": "可点击选项或点击答题卡上的题号来作答。",
  "prep.menu_li4": "已收藏的题目在答题情况中以 ★ 标示。",
  "prep.menu_li5": "用底部的上一题／下一题／提交进行切换和提交。",
  "prep.menu_li_choose": "可点击选项或点击答题卡上的题号来作答。",
  "prep.check_title": "应试环境自动检查",
  "prep.check_ok": "正常",
  "prep.check_no": "需确认",
  "prep.chk_seb": "安全浏览器（SEB）",
  "prep.chk_seb_running": "运行中",
  "prep.chk_seb_info": "实际考试将以安全浏览器启动",
  "prep.sample_title": "模拟题",
  "prep.sample_note": "点击下方选项练习作答。（不计分）",
  "prep.sample_eg": "示例",
  "prep.sample_q": "以下哪项是参加 CARIS 的正确方式？",
  "prep.sample_opt1": "点击选项或答题卡题号来选择答案",
  "prep.sample_opt2": "用手机应试",
  "prep.sample_opt3": "截屏并保存",
  "prep.sample_opt4": "打开其他标签页搜索",
  "prep.sample_fb_ok": "答对了！实际考试也是这样选择答案。",
  "prep.sample_fb_no": "只是练习，没关系。第 1 项才是正确方式。",
  "prep.sample_practice_btn": "用安全浏览器试做 1 道模拟题 →",
  "prep.ready_lead": "已确认全部须知。准备好后即可开始考试。",
  "prep.ready_li1": "点击「开始考试」后考试立即开始。",
  "prep.ready_li2": "开始后立即开始计时，且无法从头重来。",
  "prep.agree": "我已确认上述全部须知和注意事项，并将参加考试。",
  "prep.prev": "上一步",
  "prep.next": "下一步",
  "prep.starting": "正在准备考试…",
  "prep.start": "开始考试",
  "check.title": "考试环境测试（预检）",
  "check.eyebrow": "预检",
  "check.sub": "在正式考试前，先确认安全浏览器能否在本机正常打开，以及应试环境是否就绪。",
  "check.sec1_title": "安装安全程序（Safe Exam Browser）",
  "check.sec1_desc": "考试在阻止截屏、复制和切换程序的安全程序（Safe Exam Browser）中进行。",
  "check.sec1_hint": "若上面的确认中安全浏览器未能打开，请在此安装。",
  "check.install_btn": "安装安全程序（SEB）",
  "check.install_note1": "· 安装时 Windows 显示「发布者: ETH Zürich」即为正常。",
  "check.install_note2": "· 若出现「Windows 已保护你的电脑」，请点击 更多信息 → 运行。（正常安装步骤）",
  "check.sec2_title": "应试环境检查",
  "check.sec2_desc": "启动安全浏览器后，将检查以下项目。",
  "check.chk_pc": "PC（台式机）环境",
  "check.chk_screen": "屏幕尺寸",
  "check.chk_fs": "支持全屏",
  "check.chk_net": "网络连接",
  "check.chk_seb": "安全浏览器（SEB）启动",
  "check.monitor_note": "· 显示器数量在安全浏览器运行时自动检查。外接显示器请仅连接 1 台。",
  "check.sebtest_btn": "用安全浏览器打开确认",
  "check.sebtest_desc": "以与正式考试相同的方式启动安全浏览器，确认其在本机能否正常打开。\n不会出现考题。",
  "check.back": "返回我的考试券",
  "done.title": "提交已完成",
  "done.sub1": "您的应试已正常受理。安全浏览器将自动关闭。",
  "done.sub2": "评分结果将在公布日后于「我的页面」查看。",
  "done.home": "返回主页",
  "complete.title": "提交已完成",
  "complete.sub": "您的应试已正常受理。\n评分结果将在公布日后于「我的页面」查看。",
  "complete.voided_title": "已结束应试",
  "complete.voided_sub": "本次应试已作废，不予评分。\n如需重考，请从头开始。",
  "complete.practice_title": "模拟应试已结束",
  "complete.practice_sub": "正式考试的流程完全相同。\n准备好后请参加正式检定。",
  "complete.close_seb": "结束考试",
  "complete.auto_close": "将在 {n} 秒后自动关闭。",
  "complete.to_check": "查看应试状况",
  "complete.home": "返回主页",
  "seb.title": "请用安全浏览器应试",
  "seb.sub": "本考试仅可在阻止截屏、复制和切换其他程序的 Safe Exam Browser（SEB）中应试。",
  "seb.reqs_title": "✅ 应试前确认事项",
  "seb.req_monitor": "仅连接 1 台显示器。若笔记本接了外接显示器，请断开。",
  "seb.req_install": "必须已安装 Safe Exam Browser。（见下方「安装 SEB」）",
  "seb.req_vm": "无法在虚拟机（VM）或远程控制（TeamViewer、AnyDesk 等）中应试。",
  "seb.req_record": "请关闭所有录屏/截屏程序及不必要的应用。",
  "seb.install": "安装 SEB",
  "seb.start": "用安全浏览器开始",
  "seb.start_unset": "用安全浏览器开始（未配置）",
  "seb.trouble_summary": "无法启动并弹出英文错误窗口",
  "seb.err_display": "已连接 2 台或以上显示器。仅保留 1 台，断开其余后重新开始。",
  "seb.err_vm": "无法在虚拟机（VM）中应试。请在真实 PC 上运行。",
  "seb.err_process": "正在运行被阻止的程序（远程控制、录屏、即时通讯等）。请全部关闭后重新开始。",
  "seb.trouble_foot": "若其他错误持续出现，请截图错误窗口并联系管理员。",
  "run.lost_title": "无法加载考试信息",
  "run.lost_sub": "页面已刷新或访问方式有误。请从 CARIS 页面重新开始。",
  "run.to_exam": "前往 CARIS",
  "run.practice_done": "模拟练习已结束。正式考试的操作方式完全相同。",
  "run.submit_fail": "提交失败，请重试。",
  "run.unanswered_warn": "还有 {n} 道题未作答。\n将跳转到第一道未作答题目（第 {first} 题）。",
  "run.submit_confirm": "确定要最终提交答案吗？\n提交后将无法修改。",
  "run.short_placeholder": "请在此填写答案。",
  "run.short_hint": "主观题 · 由管理员审核评分",
  "run.short_chars": " 字",
  "run.short_label": "主观题",
  "run.short_done": "已填写",
  "run.short_todo": "未填写",
  "run.time_up": "考试时间已结束，将自动提交。",
  "run.mask_title": "检测到离开了考试界面",
  "run.mask_sub": "请返回考试界面。截屏与离开均会被记录。",
  "run.submit": "提交",
  "run.top_title": "{title} 答题中",
  "run.q_badge": "选",
  "run.timer_title": "剩余时间",
  "run.progress_title": "进度（已答/总数）",
  "run.minutes": "{m}分钟",
  "run.font_size": "字体大小",
  "run.tab_canvas": "草稿区",
  "run.tab_sheet": "答题卡",
  "run.tab_status": "答题情况",
  "run.completed": "已完成",
  "run.written": "已作答",
  "run.legend_done": "已完成",
  "run.legend_undone": "未完成",
  "run.legend_current": "当前题目",
  "run.canvas_note": "用于计算和备注（不会提交）",
  "run.canvas_placeholder": "可在此自由记录，不会计入提交的答案。",
  "run.prev": "上一题",
  "run.next": "下一题",
  "run.submitting": "提交中…",
  "run.quit": "退出",
  "run.quit_title": "要放弃考试吗？",
  "run.quit_confirm": "现在退出，本次应试将作废且不予评分。\n如需重考，必须从头开始。",
  "run.quit_yes": "放弃并退出",
  "run.quit_no": "继续应试",
  "result.voided_title": "本次应试已作废",
  "result.voided_sub": "请联系管理员。",
  "result.home": "返回主页",
  "result.load_failed_title": "无法加载结果",
  "result.submitted_title": "提交完成",
  "result.submitted_sub": "全部 {n} 道题的作答已成功接收。",
  "result.submitted_at": "提交时间",
  "result.release_at": "成绩公布",
  "result.release_note_pre": "成绩将于",
  "result.release_days": "{d} 天后",
  "result.release_note_post": "在此页面公布。",
  "result.graded_title": "评分结果",
  "result.submitted_prefix": "提交",
  "result.pass": "合 格",
  "result.fail": "不合格",
  "result.pass_criteria": "合格标准 — 答对全部题目的 60% 以上",
  "result.issue_cert": "📜 颁发证书 (PDF)",
  "result.back": "← 返回",
  "exresult.pass_badge": "恭喜！您已通过",
  "exresult.fail_badge": "很遗憾，本次未通过",
  "exresult.score_unit": "取得分数",
  "exresult.earned_grade": "取得资格",
  "exresult.correct_count": "答对题数",
  "exresult.cert_fallback": "CARIS",
  "exresult.info_pass": "您已具备该资格所认证的能力",
  "exresult.info_fail": "合格标准为 60 分以上",
  "exresult.subject_title": "各科目成绩",
  "exresult.subject_n": "科目 {n}",
  "exresult.correct_suffix": "正确",
  // 누르면 바로 PDF 가 나오는 게 아니라 결제 유도 화면으로 간다 → '(PDF)' 대신 '발급 신청'
  "exresult.issue_cert": "申请发放证书",
  "exresult.to_attempts": "← 我的应试现况",
  "my.status.in_progress": "应试中",
  "my.status.submitted": "已提交",
  "my.status.voided": "作废",
  "my.status.expired": "已过期",
  "my.tab.attempts": "考试应试现况",
  "my.tab.earned": "资格取得现况",
  "my.tab.issuance": "证书发放现况",
  "my.load_failed": "无法加载记录。",
  "my.login_required": "需要登录",
  "my.login_required_sub": "登录后即可使用“我的页面”。",
  "my.title": "我的页面",
  "my.eyebrow": "我的 CARIS",
  "my.greeting": "{name}",
  "my.empty_attempts": "还没有应试记录。",
  "my.take_exam": "参加 CARIS",
  "my.submitted_prefix": "提交",
  "my.not_submitted": "本次应试未提交。",
  "my.grading_pre": "评分中 · ",
  "my.grading_days": "{d} 天后",
  "my.grading_post": "（{date}）公布",
  "my.released": "成绩已公布，请查看您的成绩。",
  "my.view_score": "查看成绩",
  "my.empty_earned": "尚未取得任何资格。",
  "my.earned_badge": "已取得",
  "my.earned_meta": "取得日期 {date} · 资格编号 {no} · 分数 {correct}/{total}",
  "my.empty_issuance": "没有可发放的证书。",
  "my.cert_no": "资格编号 {no}",
  "my.issued": "已发放",
  "my.not_issued": "未发放",
  "my.reissue": "重新发放",
  "my.issue": "颁发证书",
  "cert.alt": "证书",
  "cert.print": "📄 保存为 PDF / 打印",
  "cert.back": "← 返回",
  // 발급(결제) 전 = 결제 유도 화면. 증서는 이 화면에서 일절 노출하지 않는다.
  // ⚠️ 한국어 표기는 화면 전체가 '인증서'로 통일됐다(2026-08-04). '자격증'으로 되돌리지 말 것.
  //    단 '자격번호'(cert_no)는 법정 서식 명칭이라 그대로 둔다 — 인증번호로 바꾸지 말 것.
  //    en/zh/hi/vi 는 원래 중립어(certificate)라 그대로, ja(資格証)도 지시 범위 밖이라 손대지 않았다.
  "cert.gate_title": "{grade} 证书",
  "cert.gate_lead": "已确认合格。证书需在完成发放（付款）后方可查看。",
  "cert.gate_acquired": "取得日期",
  "cert.gate_perk_pdf": "查看证书原件、保存为 PDF 并打印",
  "cert.gate_perk_qr": "启用二维码验证 — 第三方可在线核验",
  "cert.gate_perk_no": "完整公开资格编号并登记发放记录",
  "cert.gate_paid_note": "证书发放为付费服务。",
  // 디자인 견본(/certificate/sample) — 더미 인물 + 진한 워터마크
  "cert.sample_badge": "样本",
  "cert.sample_note": "这是证书设计样本。所示姓名与资格编号均为示例，发放后您将获得含本人信息与验证二维码的原件。",
  "cert.sample_wm": "样本 · SAMPLE",
  "cert.sample_wm_sub": "未发放 · 禁止擅自使用",
  "cert.sample_cta": "申请发放证书",
  "cert.qr_locked": "发放后启用",
  // 영문 성명 — 신규 시안이 영문 서식이라 증서에 각인되는 유일한 이름. 발급 신청 때 받는다.
  // ⚠️ 입력은 성·이름 두 칸(화면 순서 = 성 → 이름)인데 증서 각인은 "이름 성" 순이다.
  //    두 순서가 다르므로 hint 가 각인 순서를 반드시 말해줘야 한다.
  "cert.roman_last_label": "英文姓 (Family name)",
  "cert.roman_first_label": "英文名 (Given name)",
  "cert.roman_last_ph": "例：Ahn",
  "cert.roman_first_ph": "例：Hyeongjun",
  "cert.roman_hint": "请与护照上的拼写一致。证书上按 «名 姓» 的顺序印制，发放后无法修改。",
  // 각인 확인 단계 — 이름은 발급 후 수정 불가라 결제 버튼과 실제 발급 사이에 한 번 보여준다.
  "cert.confirm_title": "将以此姓名印制",
  "cert.confirm_note": "发放后无法修改。请确认与护照一致，且姓与名没有写反。",
  "cert.confirm_ok": "以此姓名发放",
  "cert.confirm_edit": "返回修改",
  "cert.roman_invalid": "请用拉丁字母输入姓名（仅限字母、空格与连字符）。",
  "cert.qr_caption": "Verify authenticity",
  "cert.gate_pay": "付款并发放",
  "cert.gate_later": "稍后再说",
  "cert.issuing": "发放中…",
  "cert.issue_failed": "发放失败，请稍后再试。",
  "cert.issue_no_attempt": "没有可发放的考试记录，请从我的页面重试。",
  "verify.title": "证书真伪验证",
  "verify.loading": "验证中…",
  "verify.valid_badge": "有效证书",
  "verify.expired_badge": "已过期",
  "verify.invalid_badge": "无法验证",
  "verify.invalid_desc": "未找到该证书的发放记录。请重新核对二维码或链接。",
  "verify.name": "姓名",
  "verify.grade": "资格名称",
  "verify.cert_no": "资格编号",
  "verify.issued_at": "发放日期",
  "verify.expires_at": "有效期至",
  "verify.no_expiry": "无限期",
  "verify.status": "状态",
  "verify.status_valid": "有效",
  "verify.status_expired": "已过期",
  "verify.system_sub": "证书真伪验证系统",
  "verify.official_body": "认证 AI·机器人资格检定机构",
  "verify.headline_valid": "这是有效的证书",
  "verify.headline_expired": "该证书已过期",
  "verify.headline_invalid": "无法验证的证书",
  "verify.status_invalid": "无效",
  "verify.record_title": "证书信息",
  "verify.trust": "本结果为实时查询全球AI·机器人协会官方证书数据库所得。",
  "verify.checked_at": "查询时间",
  "guide.title": "CARIS 指南",
  "guide.lead": "CARIS 是由全球 AI·机器人协会实施的官方 CBT 考试，客观评估您的 AI 应用能力。",
  "guide.areas.title": "评估领域",
  "guide.areas.1.h": "AI 应用·基础",
  "guide.areas.1.d": "AI 概念与整体应用",
  "guide.areas.2.h": "数据·预处理",
  "guide.areas.2.d": "数据理解与处理",
  "guide.areas.3.h": "模型·训练",
  "guide.areas.3.d": "模型原理与训练过程",
  "guide.areas.4.h": "伦理·安全",
  "guide.areas.4.d": "AI 伦理与数据安全",
  "guide.areas.5.h": "实务·应用",
  "guide.areas.5.d": "实际应用案例",
  "guide.exam.title": "考试构成",
  "guide.exam.count.label": "题目数量：",
  "guide.exam.count.value": "{n} 题",
  "guide.exam.count.note": "（四选一选择题）",
  "guide.exam.time.label": "考试时间：",
  "guide.exam.time.value": "{n} 分钟",
  "guide.exam.pass.label": "合格标准：",
  "guide.exam.pass.value": "全部题目的 60% 以上",
  "guide.exam.pass.note": "答对",
  "guide.exam.result.label": "结果公布：",
  "guide.exam.result.pre": "提交后",
  "guide.exam.result.value": "{n} 天后",
  "guide.exam.result.note": "在我的页面查看",
  "guide.how.title": "应试方法",
  "guide.how.1.h": "仅限 PC（台式机·笔记本）",
  "guide.how.1.d": "不支持手机·平板",
  "guide.how.2.pre": "使用阻止屏幕截图·复制·离开的",
  "guide.how.2.h": "安全浏览器（SEB）",
  "guide.how.2.post": "应试",
  "guide.how.3.pre": "应试前可通过",
  "guide.how.3.h": "考试环境测试",
  "guide.how.3.post": "提前检查安装·环境",
  "guide.cta.take": "参加 CARIS →",
  "guide.cta.check": "考试环境测试",
  "guide.eyebrow.intro": "一目了然",
  "guide.eyebrow.exam": "考试概要",
  "guide.eyebrow.areas": "评估标准",
  "guide.eyebrow.how": "应试指南",
  "guide.eyebrow.next": "后续指引",
  "guide.next.title": "下一步",
  "guide.next.score.d": "应试后在我的页面查看结果与是否合格。",
  "guide.next.notice.d": "查看有关考试运营与应试环境的最新公告。",
  "guide.next.about.d": "了解实施 CARIS 的协会及其活动。",
  "guide.callout.eyebrow": "为什么选 GARA",
  "guide.callout.title": "人人可考、免费、六种语言",
  "guide.callout.desc": "无需额外费用与固定日程，在 PC 安全环境中公正地检验你的 AI 应用能力。",
  "guide.callout.v1": "常年开放",
  "guide.callout.v1d": "没有固定场次，随时应试",
  "guide.callout.v2": "免费应试",
  "guide.callout.v2d": "应试、评分到证书发放均免费",
  "guide.callout.v3": "支持六种语言",
  "guide.callout.v3d": "韩语·英语·日语·汉语·印地语·越南语",
  "guide.callout.v4": "PC 安全应试",
  "guide.callout.v4d": "通过安全浏览器(SEB)公正应试",
  "header.exam": "参加考试",
  "header.score": "成绩查询",
  "header.support": "客户支持",
  "header.nav": "主菜单",
  "footer.quick": "快捷链接",
  "footer.blurb": "用 CARIS 客观证明你的 AI·机器人实力。常年开放、免费、提供六种语言。",
  "footer.rights": "© 2026 GARA. 版权所有.",
  "login.welcome": "欢迎",
  "login.subtitle": "登录后即可使用 GARA 服务。",
  "login.google_title": "使用 Google 继续",
  "login.kakao_title": "使用 Kakao 继续",
  "fab.login_cta": "登录",
  "about.hero_line1": "全球人工智能机器人协会",
  "about.hero_line2": "在 AI 与机器人时代，帮助人类适应变化、持续成长的机构。",
  "about.subtitle": "引领超级技术差距时代的全球标准认证\n携手GARA证明您的专业实力，跃升为未来产业的核心人才",
  "about.cta_exam": "参加 CARIS",
  "about.cta_brochure": "下载协会介绍手册",
  // 히어로 로고 락업의 부제(큰 글씨 'CARIS' 는 브랜드명이라 번역하지 않는다).
  //   hero_title_l1/l2 는 락업 이전의 2줄 제목 — 현재 미사용이나 되돌릴 수 있게 남겨둔다.
  "guide.hero_lockup_sub": "AI・机器人 融合能力资格考试",
  "guide.hero_title_l1": "全球AI·机器人",
  "guide.hero_title_l2": "融合能力资格考试",
  "guide.hero_subtitle": "GARA是以客观指标评估实务导向生成式AI应用能力的国际标准资格认证。通过五大核心领域，证明你完整的AI竞争力。",
  "guide.btn_apply": "报名考试",
  "guide.btn_mock": "模拟测试",
  // 브랜드 고유명 — 티어 이름처럼 전 언어 동일 표기.
  "guide.schedule_title": "CARIS Plan",
  "guide.status_open": "报名中",
  "guide.status_upcoming": "即将开始",
  "guide.status_closed": "已截止",
  "sched.rolling_badge": "常年报名",
  "sched.prev": "上一页",
  "sched.next": "下一页",
  "guide.areas_title": "五大评估领域",
  "guide.areas_subtitle": "GARA超越对AI技术的简单理解，全面、系统地评估你在真实工作环境中的应用能力。",
  "guide.area1_title": "AI应用与基础",
  "guide.area1_desc": "评估对提示工程基本原理、生成式AI工具特性的理解以及基本操作能力。",
  "guide.area2_title": "数据与预处理",
  "guide.area2_desc": "评估对数据收集、清洗、加工等预处理过程的理解，以用于AI模型训练和结果产出。",
  "guide.area3_title": "模型与训练",
  "guide.area3_desc": "评估把握各类AI模型特性、根据目的选择合适模型以及理解微调（Fine-tuning）概念的能力。",
  "guide.area4_title": "伦理与安全",
  "guide.area4_desc": "评估在使用AI时是否遵守版权、个人信息保护、偏见等问题相关的伦理准则。",
  "guide.area5_title": "实务与应用",
  "guide.area5_desc": "重点评估在文本、图像、编程等各种业务场景中运用AI工具，高效产出实际成果的综合问题解决能力。",
  "guide.methods_title": "应试方法",
  "guide.methods_subtitle": "CARIS 在公正、可靠的环境中进行。",
  "guide.method1_title": "仅限PC（台式机/笔记本）",
  "guide.method1_desc": "为保证检定稳定，禁止使用手机或平板设备应试。",
  "guide.method2_title": "安全浏览器（SEB）",
  "guide.method2_desc": "通过从根本上阻止屏幕截图和离屏的专用安全浏览器，保障评估的可信度。",
  "guide.method3_title": "考试环境测试",
  "guide.method3_desc": "应试前请务必进行环境测试，检查系统是否处于最佳状态。",
  "notice.hero_sub": "查看 CARIS 的最新动态、考试指南及重要公告。",
  "notice.filter_all": "全部",
  "notice.tag_notice": "公告",
  "notice.tag_guide": "指南",
  "notice.tag_required": "必读",
  "notice.empty": "‘{filter}’ 分类下暂无公告。",
  "notice.more": "加载更多",
  "notice.read_more": "查看详情",
  "notice.back_list": "返回列表",
  "notice.not_found": "未找到该公告。",
  "faq.eyebrow2": "客户中心",
  "faq.hero_title": "我们能",
  "faq.hero_title_em": "为您做些什么？",
  "faq.hero_sub": "查找有关全球 AI 与机器人工程认证、考试日程及资格验证流程的全面指南与解答。",
  "faq.search_ph": "搜索问题...",
  "faq.search_go": "搜索",
  "faq.card_schedule_title": "CARIS PLAN",
  "faq.card_schedule_desc": "查看即将到来的 CARIS 考试日期与日程。",
  "faq.card_verify_title": "资格验证",
  "faq.card_verify_desc": "在“我的页面”查看您已获得的资格与证书。",
  "faq.categories": "分类",
  "faq.help_title": "还没有解决吗？",
  "faq.help_body": "提交 1 对 1 咨询，我们确认后会回复您。",
  "faq.help_link": "1 对 1 咨询",
  "faq.search_results": "搜索结果",
  "faq.searching_sub": "与“{query}”相关的问题。",
  "faq.no_results": "没有找到关于“{query}”的结果。",
  "faq.cat_empty": "该分类的问题正在准备中。",
  "faq.q1.tag": "应试环境",
  "faq.q2.tag": "安全浏览器",
  "faq.q3.tag": "结果",
  "faq.q4.tag": "评分",
  "faq.q5.tag": "重新应试",
  "faq.q6.tag": "证书",
  "faq.q7.tag": "应试中",
  "mypage.tab_attempts": "考试应试现况",
  "mypage.tab_earned": "资格取得现况",
  "mypage.tab_issuance": "证书发放现况",
  "mypage.tab_inquiry": "1对1咨询",
  "mypage.default_name": "应试者",
  "mypage.exam_fallback": "CARIS",
  "mypage.login_required": "需要登录",
  "mypage.login_desc": "我的页面需登录后使用。",
  "mypage.login_google": "使用 Google 登录",
  "mypage.login_kakao": "使用 Kakao 登录",
  "mypage.title": "我的页面",
  "mypage.greeting_hello": "您好，",
  "mypage.greeting_name": "{name}",
  "mypage.greeting_tail": "。",
  "mypage.empty_attempts": "暂无应试记录。",
  "mypage.go_exam": "参加 CARIS",
  "mypage.cta_sub": "前往 CARIS 官方应试页面。",
  "mypage.online": "在线",
  "mypage.grading": "评分中。结果将在约 {days} 天后公布。",
  "mypage.expired": "应试期间已结束",
  "mypage.view_score": "查看成绩",
  "mypage.empty_earned": "暂无已取得的资格。",
  "mypage.passed": "合格",
  // WORLD ARENA 레벨 인증서 — 레벨테스트에서 승급할 때마다 한 장씩 쌓인다(자격 취득 현황 탭)
  "mypage.cert_no": "认证编号",
  "mypage.empty_issuance": "暂无可发放的证书。",
  "mypage.tab_ebooks": "我的书架",
  "mypage.empty_ebooks": "尚未购买电子书或课程。",
  // 메인 3번째 CTA(landing.cta_learn)와 같은 이름. 브랜드 라벨이라 6개국어 동일 표기.
  "ebook.store_title": "Learning Library",
  // 안내에 쓰는 '서재' 이름은 실제 마이페이지 탭 라벨(mypage.tab_ebooks = 내 서재)과 같아야 한다.
  "ebook.store_sub": "已购买的书可在个人中心 › 我的书架阅读。",
  "ebook.empty_store": "暂无上架的电子书。",
  "ebook.buy": "购买",
  "ebook.get_free": "免费获取",
  "ebook.free": "免费",
  "ebook.owned": "已拥有",
  "ebook.read": "阅读",
  "ebook.view": "查看",
  "ebook.cover_zoom": "查看大图封面",
  "ebook.processing": "处理中…",
  "ebook.bought": "购买完成 — 已加入 我的书架。",
  "ebook.login_to_buy": "登录后即可购买。",
  // 비로그인이 구매 버튼을 눌렀을 때 뜨는 로그인 모달(제목 한 줄 + 버튼만 — 책 정보·설명은 넣지 않는다)
  "ebook.login_modal_title": "需要登录",
  "ebook.go_store": "前往 Learning Library",
  "ebook.go_library": "在 我的书架中查看",
  "ebook.load_failed": "无法加载电子书。",

  // ---- 결제(/checkout · /pay/success · /pay/fail) ----
  // ⚠️ 통화는 화면 언어와 무관하게 **원(KRW)** 이다. 금액 문자열은 여기 넣지 말고 lib/money.ts 의 krw() 로 찍을 것.
  "pay.title": "结算",
  "pay.back": "返回",
  "pay.login_title": "需要登录",
  "pay.order": "订单明细",
  "pay.preparing": "正在准备结算…",
  "pay.pay_button": "支付",
  "pay.moving": "正在打开支付窗口…",
  "pay.reopen": "重新打开支付窗口",
  "pay.reopen_hint": "关闭了支付窗口吗？尚未完成支付 — 可用上方按钮重新打开。",
  // 테스트 키로 붙어 있을 때만 뜬다 — 실키와 헷갈리면 안 되므로 문구를 부드럽게 쓰지 않는다.
  "pay.test_mode": "测试环境 — 不会产生真实扣款。",
  "pay.not_configured": "支付尚未开通，请稍后再试。",
  "pay.bad_request": "支付信息不正确。",
  "pay.error_generic": "无法继续支付。",
  "pay.confirming": "正在确认支付",
  "pay.confirming_body": "请不要关闭此页面。",
  "pay.success_title": "支付完成",
  "pay.free_title": "已加入书架",
  "pay.free_body": "免费资料，已直接加入书架。",
  "pay.free_title_exam": "考试券已发放",
  "pay.free_body_exam": "该级别免费，无需支付即已发放。",
  // 가상계좌 — 계좌만 발급된 상태다. 여기서 '완료'라고 하면 안 된다(입금 전이라 지급도 안 됐다).
  "pay.waiting_title": "等待入款",
  // 결제는 성공했는데 지급이 보류된 상태(paid + fulfilled_at=null). **실패 문구를 쓰면 안 된다** — 돈은 이미 빠졌다.
  // 실패로 읽히면 사용자가 다시 결제하려다 '이미 결제 완료'를 보고 두 화면이 정반대로 말하게 된다.
  "pay.hold_title": "支付已完成",
  "pay.hold_body": "但发放处理已暂缓，我们的团队会处理 — 请不要重复支付。",
  "pay.waiting_body": "款项到账后将自动发放。",
  "pay.fail_title": "支付未完成",
  "pay.fail_body": "支付已取消或未获批准。",
  "pay.retry": "重试",
  "ebook.reader_back": "我的书架",
  "ebook.reader_lang": "阅读语言",
  "ebook.reader_fs": "全屏",
  // 러닝 라이브러리(/ebooks) — 레벨 | 교재 | 강의 3열. 레벨 이름·설명은 lv.N.name / lv.N.desc 를 그대로 쓴다.
  //   ⚠️ "레벨을 고르면 교재와 강의가 나타납니다" 같은 사용법 설명문은 넣지 않는다 — 화면을 보면 아는 것이다(2026-08-06 삭제).
  //   카탈로그 이름(LEVELTEST / CARIS)은 여기 없다 — 급수 이름(Beginner…)처럼 브랜드
  //   고유명이라 언어 무관 영문 고정이고, 단일 출처는 Ebooks.tsx 의 CATALOG_LABEL 이다.
  "ll.catalog": "教材类别",
  "ll.level_col": "等级",
  "ll.tier_col": "级别",
  // ⚠️ 브랜드 표기라 6개국어 모두 같은 글자다(ko.ts 주석 참고).
  "ll.books": "E-Book",
  "ll.lectures": "课程",
  "ll.no_books": "该等级的教材正在准备中。",
  "ll.no_lectures": "该等级的课程正在准备中。",
  "ll.no_books_tier": "该级别的教材正在准备中。",
  "ll.no_lectures_tier": "该级别的课程正在准备中。",
  "ll.any_level": "不限等级",
  "ll.any_level_desc": "不限等级都可以看的资料。",
  "ll.any_tier": "不限级别",
  "ll.any_tier_desc": "不限级别都可以看的资料。",
  "ll.play": "播放",
  // 페이지 넘김(한 페이지에 한 개). 화면엔 ‹ 1 / 3 › 만 보이고 이 문구는 읽어주는 이름표다.
  "ll.prev": "上一个",
  "ll.next": "下一个",
  "ll.watch": "观看",
  "ll.playing": "播放中",
  "ll.empty_owned": "没有已购买的内容。",
  // 전체구매(2026-08-19) — 왼쪽 열 맨 위 칸. {n} = 할인율(BUNDLE_OFF_PCT).
  "ll.bundle": "全部购买",
  "ll.bundle_desc": "可以挑选教材和课程，一次性加入。",
  "ll.bundle_hint": "{c} 项全部加入立减{n}%",
  "ll.bundle_on": "{c} 项已全部加入 · 立减{n}%",
  "ll.pick": "选择",
  "ll.picked": "已选择",
  "ll.pick_all": "全选",
  "ll.pick_none": "取消选择",
  "ll.pick_count": "已选 {n} 项",
  "ll.pick_of": "已选 {a} / {b}",
  "ll.total": "合计",
  "ll.bundle_buy": "购买所选",
  "ll.bundle_empty": "暂时没有可添加的项目。",
  "mypage.reissue": "重新发放",
  "mypage.issue": "申请发放",
  "mypage.view_sample": "查看样本",
  "mypage.sample_title": "证书样本",
  "mypage.sample_desc": "看看证书长什么样。",
  "gate.btn_check": "考试环境测试",
  "gate.login_required": "应试需要 Google 登录。（未登录时将自动引导）",
  "gate.format_value": "多选一客观题",
  "gate.instr_result_h": "成绩公布（{d}天后）",
  "gate.instr_result_d": "考试结束后 {d} 天内单独通知。",
  "gate.instr_security_h": "安全规定（禁止截屏）",
  "gate.instr_security_d": "考试期间严禁截屏及使用外部设备。",
  "gate.instr_pc_h": "环境要求（仅限PC）",
  "gate.instr_pc_d": "为顺利进行，请务必在桌面环境中应试。",
  "mobile.title": "仅可在 PC 上应试",
  "mobile.desc": "出于安全与画面布局考虑，CARIS 仅可在台式机/笔记本上应试。手机·平板无法开始考试。",
  "mobile.home": "返回首页",
  "run.question": "题目",
  "notice.title": "公告",
  "notice.eyebrow": "公告 · 通知",
  "notice.lead": "查看 CARIS 的最新动态与重要公告。",
  "notice.cat.notice": "公告",
  "notice.cat.guide": "指南",
  "notice.cat.required": "必读",
  "notice.item1.title": "CARIS 正式开放公告",
  "notice.item1.body": "评估 AI 应用能力的 CARIS 已正式开放。可在 PC 上使用安全浏览器（SEB）应试。",
  "notice.item2.title": "安全浏览器（SEB）应试指南",
  "notice.item2.body": "本考试仅可在阻止屏幕截图·复制·离开的 Safe Exam Browser 中应试。应试前请在「考试环境测试」中提前检查安装与环境。",
  "notice.item3.title": "防作弊须知",
  "notice.item3.body": "考试期间，屏幕截图·复制·切换到其他窗口都会被阻止并记录。若确认作弊，应试可能被判无效，请注意。",
  "faq.title": "常见问题",
  "faq.eyebrow": "帮助 · FAQ",
  "faq.lead": "汇总了应试前的常见问题。若没有找到答案，请查看公告。",
  "faq.q1.q": "可以用手机或平板应试吗？",
  "faq.q1.a": "不可以。CARIS 仅限 PC（台式机·笔记本）。无法在手机·平板上应试。",
  "faq.q2.q": "安全浏览器（SEB）是什么？",
  "faq.q2.a": "这是官方考试安全程序，可在考试期间阻止屏幕截图·复制·切换到其他程序。开始应试时按提示安装一次即可。",
  "faq.q3.q": "考试结果什么时候出？",
  "faq.q3.a": "提交一周后，可在我的页面「成绩查询」中查看是否合格及分数。",
  "faq.q4.q": "合格标准是什么？",
  "faq.q4.a": "答对全部题目的 60% 以上即为合格。",
  "faq.q5.q": "可以重新应试吗？",
  "faq.q5.a": "每场 CARIS 仅可应试一次，提交后无法重考同一场，但可报名参加下一场。",
  "faq.q6.q": "如何获得证书？",
  "faq.q6.a": "合格后，可在我的页面「证书发放状态」或成绩查询界面将证书以 PDF 形式发放·打印。",
  "faq.q7.q": "考试中有未作答的题目会怎样？",
  "faq.q7.a": "若有未作答的题目则无法提交，警告后会跳转到未作答题目。时限结束时将自动提交。",
  "nav.exam": "CARIS",
  "nav.guide": "CARIS 指南",
  "nav.caris": "CARIS",
  // FAB 네비 전용 라벨 — 옆의 WORLD ARENA·CARIS 와 맞춰 전 언어 영문 대문자 고정.
  //   (본문에서 쓰는 common.home · ebook.store_title 은 현지화 그대로 둔다)
  "fab.home": "HOME",
  "nav.apply": "CARIS 报名",
  "nav.mypage": "我的页面",
  "nav.certpreview": "证书预览",
  "nav.certgatepreview": "证书付款引导页",
  "nav.notice": "公告",
  "nav.faq": "常见问题",
  "nav.support": "客户中心",
  "fab.dark": "深色模式",
  "fab.light": "浅色模式",
  "nav.assoc": "协会简介",
  "fab.login": "使用 Google 登录",
  "fab.loginhint": "登录后即可应试",
  "fab.morebtn": "更多",
  "fab.changeChar": "更换头像",
  "fab.editName": "修改姓名",
  "fab.logout": "退出登录",
  "fab.uploadImg": "上传图片",
  "fab.uploadFail": "上传失败。",
  "fab.toTop": "回到顶部",
  // FAB 의 빨간 점(1:1 문의 새 답변) 안내 — 점 자체는 aria-hidden 이라 이 문구가 유일한 설명이다.
  "fab.newanswer": "您的咨询有新回复",
  // ── 의견함(/feedback) — FAB 패널의 빨간 항목. 1:1 문의와 달리 답변이 없다(수집 전용). ──
  "fab.feedback": "提交意见",
  "feedback.title": "提交意见",
  "feedback.sub": "在网站正式上线之前，我们希望听到各位成员的宝贵意见。\n使用过程中感到不便的地方，或者希望增加的功能，都欢迎自由留言。\n我们难以对每一条反馈单独回复，但负责团队会逐条查看，并积极用于打造更好的服务。",
  "feedback.f_org": "单位",
  "feedback.f_name": "姓名",
  "feedback.f_path": "位置",
  "feedback.f_body": "内容",
  "feedback.ph_org": "例：战略企划室",
  "feedback.ph_name": "例：张三",
  "feedback.ph_path": "例：https://gara-cbt.airobotassn.workers.dev/hub",
  "feedback.ph_body": "例：希望背景颜色再深一些。",
  "feedback.hint_path": "请写明意见所对应的页面或菜单。",
  "feedback.f_files": "附件（选填）",
  "feedback.files_drop": "把文件拖到这里，或直接粘贴截图（Ctrl+V）。",
  "feedback.files_pick": "选择文件",
  "feedback.files_hint": "最多 3 个，每个 20MB。支持图片、PDF、PPT、Word、Excel、HWP、录屏和 ZIP。",
  "feedback.files_up": "上传中…",
  "feedback.files_remove": "移除附件",
  "feedback.err_file_type": "该格式无法上传。",
  "feedback.err_file_size": "有文件超过 20MB。",
  "feedback.err_file_many": "最多只能添加 3 个文件。",
  "feedback.err_file_quota": "短时间内上传过多，请稍后再试。",
  "feedback.err_file_fail": "文件上传失败，请稍后再试。",
  "feedback.submit": "发送",
  "feedback.again": "再写一条",
  "feedback.done_title": "已发送",
  "feedback.done_body": "您的意见已送达管理团队。我们会认真阅读并改进。",
  "feedback.err_fail": "发送失败，请稍后再试。",
  "feedback.err_too_long": "内容过长，请精简后再发送。",
  "feedback.err_too_many": "短时间内发送次数过多，请稍后再试。",
  "landing.hero_pre": "实体 AI 时代，",
  "landing.hero_em": "你的能力",
  "landing.hero_post": "用 CARIS 来验证",
  "landing.hero_cta": "参加 CARIS",
  "landing.cta_diagnose": "WORLD ARENA",
  "landing.cta_exam": "CARIS",
  // WORLD ARENA·CARIS 와 나란한 3번째 버튼이라 브랜드 라벨처럼 6개국어 동일 표기. 목적지 = /ebooks.
  "landing.cta_learn": "Learning Library",
  "landing.cta_learn_main": "Learning Library",
  "landing.card.guide.d": "一目了然地查看考试构成、评估领域与应试方法。",
  "landing.card.check.d": "应试前提前检查安全程序与环境。",
  "landing.card.notice.d": "汇总开放动态与应试前必看的公告。",
  "nav.exampreview": "应试界面预览",
  "nav.resultpasspreview": "合格界面预览",
  "nav.resultfailpreview": "不合格界面预览",

  // ── CARIS 자격 데이터(caris.ts) 다국어 — getTracks/getRolling 이 tr() 로 참조 ──
  // 공용 스펙 라벨(Guide·ExamApply 공유)
  "caris.lbl.subjects": "检定科目",
  "caris.lbl.format": "考试构成",
  "caris.lbl.duration": "考试时间",
  "caris.lbl.method": "检定方式",
  "caris.lbl.practical": "实操",
  "caris.lbl.pass": "合格标准",
  "caris.lbl.eligibility": "报考资格",
  "caris.lbl.target": "对象",

  // ── CARIS-Ⅰ (전국민 AI·로봇 리터러시): Beginner / Pro / Elite — 티어별 독립 시험, 고정 60% 합격 ──
  // 트랙 표기는 브랜드 하나로 통일 — 화면에서 'CARIS-Ⅰ/Ⅱ' 숫자는 쓰지 않는다(내부 키 t1/t2 는 유지).
  "caris.t1.name": "CARIS",
  "caris.t1.tagline": "全民AI·机器人素养",
  "caris.t1.eligibility": "无报考资格限制",
  "caris.t1.caption": "Beginner·Pro·Elite 三个等级，从日常素养到专家入门，每个等级通过各自的考试取得。",
  "caris.t1.beginner.target": "人人可取得的基础素养",
  "caris.t1.beginner.format": "四选一客观题40题 · 40分钟",
  "caris.t1.beginner.pass": "60分（24题）以上",
  "caris.t1.beginner.subj.0": "生成式AI的日常应用",
  "caris.t1.beginner.subj.1": "日常中的机器人技术与实体AI理解",
  "caris.t1.beginner.subj.2": "人工智能·机器人伦理与数字安全素养",
  "caris.t1.pro.target": "中学生及职场人士基础",
  "caris.t1.pro.format": "四选一客观题50题 · 50分钟",
  "caris.t1.pro.pass": "60分（30题）以上",
  "caris.t1.pro.subj.0": "生成式AI工具应用与提示工程基础",
  "caris.t1.pro.subj.1": "AI·机器人自动化技术的理解与应用",
  "caris.t1.pro.subj.2": "实体AI积木编程与机器人控制基础",
  "caris.t1.elite.target": "管理者·讲师及专家入门课程",
  "caris.t1.elite.format": "客观题50题 + 简答题10题 · 60分钟",
  "caris.t1.elite.pass": "60分（36题）以上",
  "caris.t1.elite.subj.0": "边缘AI设备与传感器数据处理",
  "caris.t1.elite.subj.1": "AI·机器人系统设计与服务规划",
  "caris.t1.elite.subj.2": "基于Python与API的AI·机器人联动编程",

  // ── CARIS-Ⅱ (피지컬 AI 전문가): Master / Grand Master / Zenith — 기존 Master 내용 유지, 이름만 교체 ──
  "caris.t2.name": "CARIS",
  "caris.t2.tagline": "实体AI专家课程",
  "caris.t2.eligibility": "须逐级取得下位等级",
  "caris.t2.caption": "取得CARIS-Ⅰ Elite后，从Master起按等级由低到高顺序应试的专家课程。",
  "caris.t2.master.prereq": "Elite取得者",
  // ⚠️ method·pass 는 ' · ' 로 잘라 줄바꿈한다(ExamApply). 구분자를 다른 문자로 바꾸면 한 줄로 뭉친다.
  //    문항 수·시간은 caris.ts 의 TIER_EXAM_SPEC 과 한 쌍이다 — 한쪽만 고치면 문항 관리 화면과 어긋난다.
  "caris.t2.master.method": "笔试 客观50+主观10（共60题）/ 60分钟 · 实操 PC作业型 / 120分钟",
  "caris.t2.master.subj.0": "AI · 机器人硬件与模型优化",
  "caris.t2.master.subj.1": "ROS 2 机器人软件开发",
  "caris.t2.master.subj.2": "基础AI API对接、基于Python/C++的单机器人控制与LLM集成",
  "caris.t2.master.practical": "基础AI API对接、基于Python/C++的单机器人控制与LLM集成",
  "caris.t2.master.pass": "笔试 各科≥40且平均≥60 · 实操≥70",
  "caris.t2.grandmaster.prereq": "Master取得者",
  "caris.t2.grandmaster.method": "笔试 客观50+主观10（共60题）/ 60分钟 · 实操 复合作业型 / 120分钟",
  "caris.t2.grandmaster.subj.0": "数字孪生设计与基于 AI 的仿真验证",
  "caris.t2.grandmaster.subj.1": "AI · 机器人融合系统架构设计与智能控制应用",
  "caris.t2.grandmaster.subj.2": "基于 Isaac Sim·Gazebo 的自动驾驶·视觉流水线搭建与虚实优化",
  "caris.t2.grandmaster.practical": "基于 Isaac Sim·Gazebo 的自动驾驶·视觉流水线搭建与虚实优化",
  "caris.t2.grandmaster.pass": "笔试 各科≥40且平均≥60 · 实操≥70",
  "caris.t2.zenith.prereq": "Grand Master取得者",
  // ⚠️ Zenith 는 **필기 서술·논술형 하나**다(2026-08-13). 옛 값은 '포트폴리오 제출 + 심층 면접 30분'
  //    이었는데 성격이 통째로 바뀌었다. 실기가 없으므로 caris.t2.zenith.practical 키는 계속 안 쓴다.
  "caris.t2.zenith.method": "笔试 简答·论述型 / 120分钟",
  "caris.t2.zenith.subj.0": "大规模 AI · 机器人系统集成(SI)与端到端项目管理",
  // ⚠️ Zenith 는 **3과목**이다(2026-08-13). 예전엔 기능안전과 거버넌스·윤리가 subj.1 한 과목에 묶여 2과목이었는데,
  //    둘을 갈라 각각 과목으로 세우고 '보안'·'DX 전략'을 넣었다. 표준 3종은 각자 해당 과목을 따라갔다
  //    (ISO 10218=기능안전 · IEC 62443=보안 → subj.1 / ISO/IEC 42001=AI 거버넌스 → subj.2).
  //    과목 수는 caris.ts 의 T2_TIERS(subj)가 정한다 — 키만 늘리면 화면에 안 나온다.
  "caris.t2.zenith.subj.1": "基于国际标准(ISO 10218、IEC 62443)的功能安全与安全防护应用",
  "caris.t2.zenith.subj.2": "AI 治理(ISO/IEC 42001)、伦理与数字化转型(DX)战略",
  "caris.t2.zenith.pass": "评分量表审查 · 3名评委平均≥80",
  // 상시(Rolling) 항목
  "caris.rolling.pro_cbt.name": "CARIS 常规检定 (CBT)",
  "caris.rolling.pro_cbt.badge": "常年报名",
  "caris.rolling.pro_cbt.date": "全年常态 · 预约日应试",
  "caris.rolling.pro_cbt.desc": "预约所需日期，通过在线(CBT)应试的常规检定。",

  // ── Guide 히어로 (2026-07 개편: 로고 락업 + 일정 패널 → 카피 + CARIS PLAN 버튼 + 로봇 이미지) ──
  // h1 은 2줄. 1줄은 브랜드 표기라 전 언어 'AI·Robot' 고정, 2줄만 번역 + 끝의 'CARIS' 는 컴포넌트가 파란색으로 붙인다.
  "guide.hero_h1_l2": "融合能力",
  // 소개 문단 — '|' 로 줄바꿈(2줄). 1줄=지향점, 2줄=CARIS 가 하는 일.
  "guide.hero_lead": "成为理解并运用AI与机器人技术的未来型人才|CARIS 检验并认证您的融合能力。",
  "guide.plan_cta": "CARIS PLAN",

  // ── Guide '무엇인가요' 섹션 — 제목 + 영문 정식명 + 한 줄 정의 + 특징 카드 8장 ──
  "guide.what_title": "是什么？",
  "guide.what_def": "CARIS 是 AI·Robot 融合能力资格检定。",
  "guide.f1.t": "AI·Robot 融合能力认证",
  "guide.f1.d": "体系化的能力验证系统",
  "guide.f2.t": "体系化的资格等级",
  "guide.f2.d": "提供阶梯式成长路线",
  "guide.f3.t": "人人皆可应试",
  "guide.f3.d": "无年龄·专业·经历限制",
  "guide.f4.t": "可在全球使用",
  "guide.f4.d": "基于国际标准",
  "guide.f5.t": "技术理解",
  "guide.f5.d": "理解AI·机器人技术的基本原理",
  "guide.f6.t": "实务应用",
  "guide.f6.d": "用于工作·日常的实务能力",
  "guide.f7.t": "创意融合",
  "guide.f7.d": "以AI·机器人融合创造新价值",
  "guide.f8.t": "未来素养",
  "guide.f8.d": "掌握未来社会的核心能力",

  // ── Guide '자격 체계' 섹션 제목/부제 ──
  "guide.ladder_title": "资格体系",
  "guide.ladder_sub": "一步一个台阶，向着你的梦想前进！",

  // ── Plan(/plan · 시험 일정) ──
  "plan.title": "CARIS PLAN",
  "plan.sub": "CARIS 资格检定每月定期运营日程说明。",
  "plan.back": "CARIS",
  // ── /plan 접수중 회차 일정표(2026-08-20) — 줄 이름 4개. 날짜는 그 회차 값에서 온다. ──
  "plan.step_apply": "报名",
  "plan.step_exam": "应试期间",
  "plan.step_grade": "评分期间",
  "plan.step_result": "合格查询",

  // ── Guide(자격검정 안내) 하드코딩 라벨 ──
  "guide.cert_intro_title": "AI·机器人融合能力资格考试",
  // 피라미드 우측 그룹 라벨 — '|' 로 줄바꿈(브레이스 옆 2줄 세로 배치). 위 3티어=피지컬 AI, 아래 3티어=AI·로봇 리터러시
  "guide.group_physical": "实体AI|专家",
  "guide.group_literacy": "AI·机器人|素养",
  // CARIS-Ⅱ(피지컬 AI) 카드 배너 문구 — 응시화면의 prereq(응시자격)과 별개로 Guide 배너 전용. Master=초급/GM=중급/Zenith=고급
  "guide.ptrack.master": "实体AI 初级专家",
  "guide.ptrack.grandmaster": "实体AI 中级专家",
  "guide.ptrack.zenith": "实体AI 高级专家",
  "guide.ladder_hint": "点击等级查看考试科目",
  "guide.aria_prev_track": "上一个资格",
  "guide.aria_next_track": "下一个资格",
  "guide.aria_prev_grade": "上一级别",
  "guide.aria_next_grade": "下一级别",

  // ── ExamSchedule(자격검정 접수) 하드코딩 라벨 ──
  "sched.badge": "考试日程",
  "sched.title": "CARIS 报名",
  "sched.desc": "请选择要报名的考试。仅可申请报名中的日程。",
  "sched.regular": "定期考试日程",
  "sched.rolling": "常规考试",
  "sched.exam_date": "考试日",
  "sched.exam_period": "应试期间",
  "sched.apply_period": "报名期间",
  "sched.apply": "报名",
  "sched.empty": "暂无考试日程。",

  // ── ExamApply(원서접수) 하드코딩 라벨 ──
  "apply.back": "CARIS PLAN",
  "apply.title": "报名申请",
  "apply.select_cert": "选择资格",
  "apply.track": "赛道",
  "apply.tier": "等级",
  "apply.pay_summary": "支付摘要",
  "apply.sel_cert": "所选资格",
  "apply.round": "场次",
  "apply.fee": "应试费",
  // exam_fees 에 그 티어의 행이 없을 때 — 금액 자리에 숫자를 지어내지 않고 이걸 띄우고 결제를 막는다.
  // (현재 CARIS-Ⅱ Master·Grand Master·Zenith 가 여기 해당)
  "apply.fee_tbd": "准备中",
  "apply.fee_free": "免费",
  "apply.free_btn": "免费报名",
  "apply.total": "应付总额",
  // 추천 교재(원서접수 가운데 열) — 응시료와 **함께** 결제되는 곁다리다.
  "apply.book_col": "推荐教材",
  "apply.book_add": "购买",
  "apply.book_added": "已加入",
  "apply.book_row": "教材（{name}）",
  "apply.book_note": "报名时一并购买教材更方便。",
  "apply.book_owned": "您已购买该教材。用这本书一起备考吧。",
  "apply.book_owned_cta": "在我的书架中查看",
  "apply.pay_btn": "去支付",
  "apply.pay_note": "支付需实名认证。应试费·实名认证·支付将于稍后接入（预览）。",
  "apply.modal_title": "支付功能准备中",
  "apply.modal_body": "当前为报名界面预览。实名认证·支付(PG)即将接入。",
  "apply.confirm": "确定",
  "apply.closed_title": "当前不在报名期间",
  "apply.closed_body": "该场次已截止或尚未开放。请在考试日程中查看正在报名的场次。",
  "apply.closed_cta": "查看考试日程",

  // ── SEB 설치 안내(SebInstall 컴포넌트) — ExamGate 모달 · ExamCheck Step1 공유 ──
  "seb.download": "下载安全程序(SEB)",
  "seb.dl_meta": "约 {size} · 仅需安装一次 · 发布者 ETH Zürich（正常）",
  "seb.steps_title": "安装方法（约2分钟）",
  "seb.step1_t": "下载",
  "seb.step1_d": "点击上方按钮即可下载安装文件。",
  "seb.step2_t": "运行（出现警告是正常的）",
  "seb.step2_d_mac": "打开 .dmg，将 SEB 拖入“应用程序”，首次启动请右键 → 打开。",
  "seb.step3_t": "打开考试",
  "seb.step3_d": "安装完成后返回本页，用下方按钮在 SEB 中打开考试。",
  "seb.launch_btn": "在 SEB 中打开考试",
  "seb.dialog_title": "Windows 已保护你的电脑",
  "seb.dialog_more": "更多信息",
  "seb.dialog_run": "仍要运行",
  "seb.chip_once": "仅装一次",
  "seb.chip_publisher": "ETH Zürich 签名",
  "seb.chip_size": "约 {size}",
  "seb.warn_title": "安装时出现警告是正常的",
  "seb.warn_title_win": "安装时出现「{dialog}」窗口属于正常",
  "seb.warn_body_pre": "这是正式程序，点击",
  "seb.warn_body_post": "即可继续安装。",
  "seb.fact_program": "程序",
  "seb.fact_maker": "开发方",
  "seb.fact_maker_v": "瑞士苏黎世联邦理工学院（ETH）官方开源 — 全球高校与考试机构使用",
  "seb.fact_install": "安装",
  "seb.entry_loading": "正在准备考试…",
  "seb.entry_retry": "重试",
  // SEB 탈출 버튼. '취소'·'닫기' 처럼 모호하게 쓰지 말 것 — 갇힌 사람이 한눈에 알아봐야 하는 문구다.
  "envcheck.saving": "正在保存检测结果…",
  "envcheck.save_failed": "未能保存检测记录。请关闭安全浏览器后重试。",
  "envcheck.ok_title": "环境检测完成",
  "envcheck.ok_desc": "本机可以应试。请用下方按钮关闭安全浏览器。",
  "envcheck.warn_title": "有需要确认的项目",
  "envcheck.warn_desc": "请解决下方标记 ✕ 的项目后重新检测。",
  "envcheck.row_seb": "已在安全浏览器中打开",
  "envcheck.row_fs": "全屏切换",
  "envcheck.row_net": "网络连接",
  "envcheck.row_screen": "屏幕尺寸",
  "seb.exit": "退出安全浏览器",
  // SEB 로 로그인을 넘기는 인계표가 주소에 없을 때. 옛 .seb 파일로 들어왔거나 설정에서
  // startURLAppendQueryParameter 가 빠진 경우다 — SEB 안에서는 로그인할 방법이 없으므로 나가서 다시 시작해야 한다.
  // 재진입 무효 안내 — 사유와 다음 행동(문의)까지 말해줘야 한다. 무감독이라 옆에서 설명해 줄 사람이 없다.
  // ⚠️ "도와드립니다" 로 끝내면 안 된다 — 응시자는 (1) 남은 시간이 사라졌는지 (2) 응시 기간이 끝나면
  //    끝인지 (3) 언제 처리되는지를 모른 채 기다리게 된다. 세 가지를 다 말해준다.
  //    24시간 상주 운영이 아니므로 "바로 처리"를 약속하지 않는다.
  "seb.voided_how": "若因设备故障、断电或网络中断而中断，请联系我们。我们将核查中断记录，恢复后可按中断时的作答与剩余时间继续应试。但重新应试仅限于应试期间内，核查可能需要若干工作日。",
  "seb.err_no_handoff": "无法确认应试信息。",
  "seb.err_no_handoff_how": "请关闭安全浏览器，并从原浏览器的应试准备页面重新开始。",

  // ── 월드 아레나(/arena) — 지도·랭킹 패널·하단 런처 ──
  //   arena.b* = 하단 이동 버튼(Hub · 레벨테스트 · 오늘의 문제 · 미니게임)
  "arena.low": "低",
  "arena.high": "高",
  // ⚠️ arena.avgLevel 은 레벨테스트 시절 문구다. 지도 지표가 레벨 → 랭킹점수(season_total 평균, 베이지안 보정)로
  //    바뀌면서 arena.regionScore 로 대체했다. 다른 곳에서 안 쓰면 avgLevel 은 지워도 된다.
  "arena.avgLevel": "平均等级",
  "arena.regionScore": "地区得分",
  // ⚠️ 세계 지도의 칸은 '나라'고, 나라 안으로 들어가야 '지역'이다 — 그래서 한 쌍으로 둔다(`level === 0` 이 고른다).
  "arena.countryScore": "国家得分",
  "arena.part": "参与人数",
  "arena.rankL": "排名",
  "arena.ourRank": "排名",
  "arena.topRegion": "最高地区",
  "arena.topCountry": "最高国家",
  "arena.totalPart": "参与人数",
  "arena.search": "搜索地区…",
  "arena.searchCountry": "搜索国家…",
  "arena.world": "世界",
  "arena.worldLeague": "世界联赛",
  "arena.league": " 联赛",
  "arena.ppl": "人",
  "arena.unit": "名",
  "arena.avg": "平均",
  "arena.drillHint": "已选“{n}” · 再点一次进入市郡区",
  "arena.our0": "· 世界",
  "arena.our1": "· 本地区",
  "arena.our2": "· 本区",
  "arena.bLevel": "等级测试",
  "arena.bLevelS": "AI & 机器人能力测试",
  "arena.bHub": "我的主页",
  "arena.bHubS": "我的角色",
  "arena.bDaily": "DAILY QUIZ",
  "arena.bDailyS": "今日一题",
  // 아레나 화면 제목 — 제품명은 6개국어 영문 유지(ko 만 기존 표기 보존)
  "arena.title": "WORLD ARENA",
  "arena.bGame": "小游戏",
  // 용어 퀴즈 게임 3종 + 로봇 조작/코딩 퍼즐 2종이라 '용어'로 못 묶는다 → AI·로봇 전체로 넓힌 문구.
  "arena.bGameS": "AI与机器人游戏",
  "arena.loading": "正在加载地图…",
  "arena.zoom_in": "放大",
  "arena.zoom_out": "缩小",
  "arena.zoom_reset": "重置",
  "arena.numbers_hide": "隐藏排名数字",
  "arena.numbers_show": "显示排名数字",
  "arena.tabLeague": "世界联赛",
  "arena.tabChat": "聊天",
  "arena.panelToggle": "切换面板",
  "arena.dokdo": "独岛",
  // 유사채팅(pseudo-chat) 보드
  "chat.title": "聊天",
  "chat.placeholder": "输入消息…",
  "chat.send": "发送",
  "chat.sending": "发送中…",
  "chat.empty": "还没有消息，来发第一条吧！",
  "chat.report": "举报",
  // 아바타 탭 → 그 사람 카드. 실패(랭킹 기록 없음·익명·탈퇴)는 조용히 삼키지 않고 한 줄로 알려준다.
  "chat.cardOf": "{name} 的卡片",
  "chat.noCard": "该用户暂无排名记录",
  "chat.reported": "已举报",
  // 삭제 안내문은 남긴다 — 관리자 가림(chatHide)으로 여전히 이 상태가 나온다.
  //  ⚠️ 사용자 수정·삭제는 2026-08-13 제거됐다(chat.edit/delete/editedMark/editWindow/confirmDelete 키도 같이 삭제).
  //     수정이 있으면 욕설을 쓰고 신고당한 뒤 10분 안에 본문을 고쳐 증거를 지울 수 있었다.
  "chat.deleted": "消息已删除",
  // 번역 토글(2026-08-13). 대상 언어는 국가에서 정해지므로 문구에 언어 이름을 넣지 않는다
  //  — 넣으려면 전 세계 언어 이름을 6개국어로 들고 있어야 하고, 그건 사전이 아니라 Intl.DisplayNames 의 일이다.
  "chat.trOff": "翻译",
  "chat.trOn": "查看原文",
  "chat.trLoading": "翻译中…",
  "chat.trMark": "已翻译",
  "chat.trFailed": "翻译失败，请稍后重试",
  "chat.blockedLocal": "包含不当内容",
  "chat.blockedLink": "不能发送链接",
  "chat.justNow": "刚刚",
  "chat.minutesAgo": "{n}分钟前",
  "chat.blockedMod": "违反内容政策，无法发布",
  "chat.modUnavailable": "内容审核暂不可用，请稍后重试",
  "chat.tooFast": "发送太快，请稍后再试",
  "chat.duplicate": "你刚发送过相同内容",
  "chat.rateLimited": "请求过于频繁，请稍后重试",
  "chat.loginToJoin": "登录后即可参与聊天",
  "chat.scamNotice": "CARIS 运营人员绝不会索要账号信息、验证码或财物。对于冒充行为及用户之间私下交易造成的损失，本站概不负责。",
  // 방(room) — World 1개 + 나라별 1개. 어느 방인지는 지도 선택이 정한다(/arena).
  // ⚠️ 'World' 는 브랜드 영문 고정(2026-08-11) — 6개국어 모두 같은 글자. 돌아가기 버튼도 같은 글자다
  //    (나라 방에 있을 때만 보이므로 '어디로 가는지'가 이름만으로 읽힌다).
  "chat.roomGlobal": "World",
  "chat.roomBack": "World",
  "chat.anonBadge": "匿名",
  "chat.reportTitle": "请选择举报原因",
  "chat.reportSpam": "垃圾信息或广告",
  "chat.reportAbuse": "辱骂或仇恨言论",
  "chat.reportSexual": "色情内容",
  "chat.reportFlood": "刷屏",
  "chat.reportPrivacy": "泄露个人信息",
  "chat.reportOther": "其他",
  "chat.reportDetail": "详细说明（选填）",
  "chat.reportSubmit": "举报",

  // ══════════════════════════════════════════════════════════════════════════
  //  응시권(exam_tickets) · 응시료 결제 — 2026-08 추가
  //  한 기능이 여러 화면(원서접수 · 결제 · 마이페이지 · 응시 게이트)에 걸쳐 있어서
  //  네임스페이스별로 흩지 않고 여기 한 덩어리로 모았다. 위쪽 apply.* / pay.* / gate.* /
  //  prep.* / mypage.* 블록에도 같은 접두사의 옛 키가 있으니 검색으로 찾을 것.
  // ══════════════════════════════════════════════════════════════════════════

  // ── 응시권 상태·라벨 (ticket.*) — 마이페이지 '보유 응시권' 블록이 주 사용처 ──
  "ticket.section_title": "我的应试券",
  "ticket.empty": "您还没有应试券。",
  "ticket.empty_cta": "去报名",
  "ticket.count": "{n} 张",
  // status_issued 를 '발급됨' 이 아니라 '미사용' 으로 쓰는 이유: 목록에 서는 모든 응시권은 이미 발급된 것이라
  // '발급됨' 은 정보가 0이다. 사용자가 알아야 하는 건 "아직 안 썼다" 는 사실이다.
  "ticket.status_issued": "未使用",
  // consumed 는 '응시 완료' 가 아니다 — 응시를 시작한 순간 소진되므로 진행 중일 수도 있다.
  "ticket.status_consumed": "已使用",
  "ticket.status_void": "已作废",
  "ticket.status_expired": "已过期",
  // 서버(my-attempts)가 내려주는 usableReason 코드 5종과 1:1 로 대응한다.
  //   before_exam_day · window_closed · already_taken · in_progress · expired
  // 서버는 코드만 주고 문구는 여기가 정한다 — 새 코드가 생기면 여기에도 키를 추가할 것.
  "ticket.usable": "现在即可应试",
  "ticket.reason_before_exam_day": "{date} 起可以应试",
  "ticket.reason_window_closed": "应试期间已结束",
  "ticket.reason_already_taken": "您已经应试过了",
  "ticket.reason_in_progress": "应试正在进行中",
  "ticket.reason_expired": "该应试券已过期",
  "ticket.go_exam": "去应试",
  // 시험환경 점검 게이트 — 점검을 마쳐야 응시 버튼이 열린다(2026-08-11).
  //   잠금 브라우저가 안 켜지는 PC 라는 걸 시험 당일에 알면 손쓸 방법이 없어서 미리 걸러낸다.
  "ticket.env_do": "考试环境测试",
  "ticket.env_done": "环境测试完成",
  "ticket.env_required": "完成考试环境测试后才能应试。",
  "ticket.open_now": "现在可应试的考试 {n} 个",
  "ticket.open_now_sub": "在应试券中完成环境测试后应试。",
  // 필드 라벨 — 회차·등급은 원서접수 화면(apply.round / apply.tier)과 같은 말을 써야 한다.
  "ticket.round": "场次",
  "ticket.tier": "等级",
  "ticket.issued_at": "发放日期",
  "ticket.exam_period": "应试期间",
  "ticket.price_paid": "支付金额",
  // 발급 출처(exam_tickets.source) — pg 는 평상시 굳이 안 띄우지만, 관리자/무료 발급과 구분이 필요할 때 쓴다.
  "ticket.source_pg": "支付发放",
  "ticket.source_admin": "管理员发放",
  "ticket.source_free": "免费应试券",

  // ── 원서접수(/exam/apply) 추가분 ──
  // 회차가 연 급수(exam_rounds.open_tiers)에 없는 티어는 숨기지 않고 비활성 + 이 배지로 보여준다
  // — 어떤 급수가 존재하는지 알리는 값이 있어서다.
  "apply.tier_not_open": "本场次未开设",
  "apply.owned": "已购买",
  "apply.owned_cta": "查看我的应试券",
  "apply.already_applied": "您已报名该等级",
  "apply.login_required": "登录后即可报名。",
  // 짧은 인라인 배지용. 전체 화면 안내는 기존 apply.closed_title / apply.closed_body 를 쓴다.
  "apply.period_closed": "不在报名期间",
  "apply.pay_go": "去支付",
  // ⚠️ 기존 apply.pay_note 는 '결제는 추후 연결(미리보기)' 라고 적혀 있어 결제가 실동작하면 거짓말이 된다.
  //    실결제 연결 후에는 이 키로 갈아끼울 것(옛 키는 지우지 않고 남겨둔다).
  //    문구 안의 '마이페이지 › 시험 응시 현황' 은 mypage.tab_attempts 와 같은 말이어야 한다.
  "apply.pay_note_live": "支付完成后，可在个人中心 › 考试应试现况中查看应试券。",

  // ── 결제(/checkout · /pay/success) 추가분 ──
  "pay.go_tickets": "查看我的应试券",
  "pay.go_plan": "查看考试日程",
  "pay.exam_success_title": "应试券已发放",
  "pay.exam_success_body": "请在个人中心 › 考试应试现况中查看，到应试期间即可应试。",
  // 응시료는 카드·간편결제만 판다(가상계좌 제외). 그래도 가상계좌 결제가 들어오면 응시권을 발급하지 않으므로
  // 이북과 같은 '입금하면 자동 지급' 문구(pay.waiting_body)를 쓰면 안 된다.
  "pay.exam_waiting_body": "应试费仅支持银行卡和便捷支付。即使汇入虚拟账户也不会自动发放应试券，请联系客服。",
  // 자격증 발급비 — 결제로 끝나는 게 아니라 **발급이 한 걸음 남아 있다**. '결제 완료'로만 닫으면
  // 사용자는 자격증이 어디 있는지 못 찾는다(지급물이 따로 없는 유일한 상품이라 더 그렇다).
  "pay.go_cert": "领取证书",
  "pay.go_attempts": "查看应试记录",
  "pay.cert_success_title": "发放费用支付完成",
  "pay.cert_success_body": "接下来将发放证书，请点击下方按钮。",
  "pay.cert_waiting_body": "款项到账后即可发放证书。",
  // 통화 고지 — 화면 가격은 달러인데 토스 결제창은 원화로 뜬다. 이 문구가 없으면 사용자는 금액이 다르다고 느낀다.
  //   {krw} = lib/money.ts 의 krw() 로 찍은 실제 청구액 문자열.
  // ⚠️ 문장 안의 '1,500' 은 하드코딩이다 — lib/money.ts 의 KRW_PER_USD 를 바꾸면 6개국어를 전부 같이 고칠 것.
  // ⚠️ '○월○일 기준 환율' 이라고 쓰지 마라. 시장 환율이 아니라 우리가 정한 고정 환산값이다.
  "pay.currency_note": "实际扣款金额为 {krw}（按今日汇率换算）。",
  // 해외 결제(엑심베이)는 **달러로 청구**된다 — 원화 고지문을 그대로 쓰면 화면과 결제창이 다른 돈을 말한다.
  //   {usd} = 실제 청구되는 달러 금액(서버가 정한 값 그대로).
  "pay.currency_note_usd": "海外支付以美元扣款，实际扣款金额为 {usd}。",
  // 엑심베이 결제창은 우리 페이지에 아무것도 그리지 않는다 — 안내가 없으면 화면이 빈 것으로 읽힌다.
  "pay.cert_fee_note": "通过考试后申请发放证书时，将另行收费。",
  "pay.pg_eximbay_note": "点击“支付”后将打开 Eximbay 支付窗口，在该窗口中选择支付方式。",
  // ── 결제 전 취소·환불 규정 동의(2026-08-20) ──
  //    표 4줄은 응시료·자격증 발급비용, terms_ebook 은 이북·묶음용(디지털 콘텐츠라 기준이 다르다).
  //    ⚠️ 법적 고지라 임의로 줄이거나 의역하지 말 것 — 문구를 바꾸려면 규정 자체를 먼저 고쳐야 한다.
  "pay.terms_title": "取消及退款规定",
  "pay.terms_col_when": "取消时点（以当日24:00为准）",
  "pay.terms_col_rate": "退款比例",
  "pay.terms_col_note": "备注",
  "pay.terms_none": "不可",
  "pay.terms_r1_when": "应试日7天前为止",
  "pay.terms_r1_note": "全额退款",
  "pay.terms_r2_when": "应试日6天前 ~ 3天前",
  "pay.terms_r2_note": "半额退款",
  "pay.terms_r3_when": "应试日2天前 ~ 当日应试开始前",
  "pay.terms_r3_note": "原则上不可",
  "pay.terms_r3_note2": "例外全额退款 — 直系亲属死亡、住院，传染病隔离等不可抗力事由并提供证明时",
  "pay.terms_r4_when": "应试开始之后",
  "pay.terms_r4_note": "绝对不可取消及退款（含未应试）",
  "pay.terms_ebook": "电子书与课程为数字内容。付款后一旦开始阅览即限制解除合同，仅未曾阅览的商品可在付款之日起7日内退款。",
  "pay.terms_agree": "本人已确认并同意上述取消及退款规定。（必填）",
  "pay.terms_required": "需同意退款规定后才能付款。",
  // 위 고지문의 짧은 버전 — 가격만 달러로 보여주는 목록(/ebooks · /exam/apply)용. 청구액 보간이 없다.
  "pay.currency_hint": "国内支付按付款当日汇率以韩元扣款。",

  // ── 응시 게이트(/exam) 거절 안내 ──
  // 여기서 막는 건 보안이 아니라 UX 다(준비 7단계를 다 밟고 마지막에 403 을 받지 않게 하는 것).
  // 실제 차단은 start-exam 이 응시권으로 한다.
  "gate.no_ticket_title": "没有应试券",
  "gate.no_ticket_body": "应试前需先完成报名并支付应试费。",
  "gate.no_ticket_cta": "去报名",
  "gate.pick_ticket_title": "请选择要应试的考试",
  "gate.pick_ticket_body": "您有多张应试券，请选择要应试的考试。",
  "gate.not_exam_period_title": "当前不在应试期间",
  "gate.not_exam_period_body": "应试期间为 {from} ~ {to}。",
  // 익명(게스트) 세션에는 응시권이 붙을 수 없다 — 결제 자체가 로그인 계정에만 열려 있기 때문이다.
  "gate.login_paid_title": "请使用支付时的账号登录",
  "gate.login_paid_body": "应试券发放至支付账号。访客（未登录）无法应试。",

  // ── 응시 준비(/exam/prepare) — start-exam 이 돌려주는 에러 코드를 사람이 읽을 문구로 ──
  //   no_ticket · pick_ticket · attempt_exists · (응시창 밖) · (익명)
  "prep.err_no_ticket": "没有应试券，无法开始考试。",
  "prep.err_pick_ticket": "请选择要应试的考试。",
  "prep.err_exam_closed": "当前不在应试期间。",
  "prep.err_login_paid": "必须使用支付账号登录才能应试。",
  "prep.err_attempt_exists": "该考试您已应试过。",

  // ── SEB 진입로(/exam/seb) — 익명 세션으로는 응시권을 가질 수 없어 로그인으로 돌린다 ──
  "seb.login_required": "应试请使用支付账号登录。",

  // ── 마이페이지 '시험 응시 현황' 빈 상태 분기 (응시권 없음 → 접수 / 응시권 있음 → 기존 mypage.go_exam) ──
  "mypage.empty_no_ticket": "您还没有报名任何考试。",
  "mypage.go_apply": "报名考试",

  // ── DAILY QUIZ(/daily) · 미니게임(/games) ────────────────────────────────
  // ⚠️ 여기 있는 건 **화면 문구뿐**이다. 문제 자체(용어·설명·보기)는 src/lib/terms.ts 와
  //    public/games/*.html 의 POOL 에 한국어로 들어 있고 아직 다국어가 아니다.
  //    레벨테스트(questions 다국어 JSONB + translate-questions)처럼 콘텐츠 파이프라인을 붙이면
  //    그때 문항도 언어를 따라간다 — 그 전까지는 틀만 번역되고 문제는 한국어로 나온다.
  "daily.title": "DAILY QUIZ",
  "daily.login_note": "登录后才会记录 DAILY QUIZ 完成",
  "daily.term_label": "今日术语",
  "daily.correct": "答对了！🎉 今日 DAILY QUIZ 完成。",
  "daily.wrong": "差一点 — 正确答案是 {answer}。尝试过就算完成！",
  "daily.already": "今日 DAILY QUIZ 已完成。正确答案是 {answer}。",
  "daily.theory": "理论",
  "daily.hint_lead": "拿不准的话",
  "daily.reward_head": "完成后",
  "daily.done_note": "今日 DAILY QUIZ 完成 ✓ 明天开放新题。今天的可以再看（奖励每日一次）。",
  "daily.saving": "记录中…",
  "daily.pop_title": "DAILY QUIZ 完成！",
  "daily.pop_bonus": "满 7 天 +{b}P",
  "daily.pop_grew": "你的角色今天又长大了一点。",
  "daily.pop_already": "今天签到已领取硬币。DAILY QUIZ 记录已保存。",

  "mg.title": "小游戏",
  "mg.preparing": "这个小游戏还在准备中。",
  "mg.to_list": "返回小游戏列表",
  "mg.guest_hint": "成绩不会保存 · 登录",
  "mg.locked_hint": "登录后即可游玩",
  "mg.locked_title": "登录后解锁",
  "mg.locked_body": "未登录只能试玩《{game}》。登录后即可解锁全部游戏，并保留最高纪录和排名。",
  "mg.not_saved": "本次成绩未保存",
  "mg.not_saved_body": "登录后可保存最高分并进入游戏排行榜。目前只能浏览。",
  "mg.keep_playing": "继续玩就好",
  "mg.rank_title": "{title} 排行榜",
  "mg.rank_fail": "排行榜加载失败。",
  "mg.rank_rule_level": "按到达关卡由高到低 · 相同则用时短者优先",
  "mg.rank_rule_score": "按分数由高到低 · 相同则先达成者优先",
  "mg.rank_players": " · {n} 人参与",
  "mg.rank_empty": "还没有成绩，来当第一个吧！",
  "mg.rank_need_login": "登录后可查看我的排名。",
  "mg.rank_no_mine": "你还没有成绩 — 玩一局就会出现。",
  "mg.sec": "{n} 秒",
  "mg.min_sec": "{m} 分 {s} 秒",

  // 미니게임 카드(제목·소개·뱃지) — 'CARI' 는 캐릭터 이름이라 번역하지 않는다.
  "mg.beat-cari.title": "撑住吧 CARI",
  "mg.beat-cari.tagline": "从压下来的天花板下救出 CARI",
  "mg.beat-cari.badge": "AI · 机器人术语生存",
  "mg.shoot-cari.title": "射击吧 CARI",
  "mg.shoot-cari.tagline": "挡下来袭的敌机，护住 CARI",
  "mg.shoot-cari.badge": "AI · 机器人术语射击",
  "mg.pick-cari.title": "快选吧 CARI",
  "mg.pick-cari.tagline": "踏板塌陷前把 CARI 挪走",
  "mg.pick-cari.badge": "AI · 机器人术语判断生存",
  "mg.reach-cari.title": "够到吧 CARI",
  "mg.reach-cari.tagline": "转动 CARI 的机械臂去够到星星",
  "mg.reach-cari.badge": "机械臂 · 运动学解谜",
  "mg.program-cari.title": "来编程吧 CARI",
  "mg.program-cari.tagline": "给不认路的 CARI 排好步骤",
  "mg.program-cari.badge": "机器人 · 积木编程解谜",
  "mg.build-cari.title": "建造吧 CARI",
  "mg.build-cari.tagline": "在 CARI 的工厂里铺好传送带",
  "mg.build-cari.badge": "智能工厂 · 产线设计解谜",
  "mg.block-cari.title": "拦住吧 CARI",
  "mg.block-cari.tagline": "CARI 要发的文件，把危险的地方遮起来",
  "mg.block-cari.badge": "输入 AI 前的信息遮蔽",
  "mg.order-cari.title": "下指令吧 CARI",
  "mg.order-cari.tagline": "让 CARI 照着图纸做出来",
  "mg.order-cari.badge": "AI 指令设计解谜",
  "mg.feel-cari.title": "摸索前进吧 CARI",
  "mg.feel-cari.tagline": "给看不见路的 CARI 打开传感器",
  "mg.feel-cari.badge": "传感器 · 边缘AI探索",

  // ── 공유 카드(ShareCardModal + lib/shareCard.ts) ──────────────────────────
  // ⚠️ 카드 안 글자는 캔버스에 그려진다 — 훅을 못 쓰므로 renderShareCard 가 lang 을 받아 tr() 로 뽑는다.
  //    카드는 이미지로 밖으로 나가는 물건이라, 만든 사람의 화면 언어를 그대로 따라가는 게 맞다.
  "share.modal_title": "分享我的卡片",
  "share.making": "正在生成卡片…",
  "share.make_fail": "卡片生成失败",
  "share.img_fail": "图片生成失败",
  "share.saved": "已保存图片",
  "share.copied": "已复制到剪贴板",
  "share.copy_unsupported": "此浏览器不支持复制",
  "share.do_share": "分享",
  "share.do_save": "保存图片",
  "share.do_copy": "复制图片",
  "share.note": "这张卡片基于您当前的排名与段位。",
  // 카드 안(캔버스)에 그려지는 글자
  "share.card.title": "赛季记录",
  "share.card.rank_n": "第 {n} 名",
  // ⚠️ 'World' 는 브랜드 영문 고정(2026-08-11) — 6개국어 모두 같은 글자.
  "share.card.world": "World",
  "share.card.country": "国家",
  "share.card.region": "地区",
  "share.card.season_score": "赛季积分",
  "share.card.joined": "注册日",
  "share.card.friend_code": "好友代码",

  // ── 캐릭터 허브(/hub) ─────────────────────────────────────────────────────
  // Hub.tsx 는 오래 한국어 하드코딩이었다(2026-08-07 일괄 이관). 문구를 새로 넣을 때 6개국어를 다 채울 것.
  // ⚠️ 토스트 아이콘은 예전에 문구를 정규식(/부족|필요|오류/)으로 검사해 골랐다 — 번역하면 그대로 깨져서
  //    Hub.tsx 가 종류(kind)를 들고 다니도록 바꿨다. 여기 문구를 고쳐도 아이콘은 영향받지 않는다.
  "hub.err.insufficient_points": "金币不足",
  "hub.err.already_owned": "您已拥有该限定道具",
  "hub.err.unauthorized": "需要登录",
  "hub.err.generic": "发生错误，请稍后再试",
  // 방 저장 거절 사유(room 함수). 정상적으로 쓰면 안 뜬다 — 화면이 면 안 맞는 가구를 후보에서 이미 거른다.
  "hub.err.not_owned": "您还没有这件家具",

  // ── 방 꾸미기(미니룸) ──

  // 가구 이름 — 상점·방 고르기가 같이 쓴다.

  // ── 남의 방(/room/:handle) ──
  "room.visit": "参观房间",
  "room.copy": "复制链接",
  "room.copied": "已复制",
  "room.someone": "未命名",
  "room.season_pt": "赛季 {n} 分",
  "room.not_found": "找不到这个房间。",
  "room.my_room": "前往我的房间",
  "room.my_room_edit": "布置我的房间",

  // 꾸미기 파츠 이름 — 상점·토스트가 같이 쓴다.
  // ⚠️ 파츠 6종은 2026-08-14 에 상점에서 내려갔다(방 가구로 일원화). 이미 산 사람의 목록에는 남아 있어
  //    이름은 계속 필요하다 — 지우면 그 사람 화면에 키가 그대로 뜬다.
  "hub.part.hat_common_01": "嫩芽帽",
  "hub.part.hat_common_02": "毛线帽",
  "hub.part.shoe_common_01": "暖暖袜子",
  "hub.part.glasses_common_01": "圆框眼镜",
  "hub.part.wing_rare_01": "闪耀之翼",
  "hub.part.crown_rare_01": "小王冠",

  // 상단·공통
  "hub.gate_title": "需要登录",
  "hub.gate_sub": "登录后即可使用签到和商店",
  "hub.banner_login": "签到和商店需要登录后使用",
  "hub.share": "炫耀我的排名",
  "hub.gift_btn": "赠送",
  "hub.help_aria": "如何获得积分",
  "hub.coin_tip": "持有的 CARI 币",
  "hub.mission_title": "今日任务",
  "hub.confirm": "确定",

  // 오른쪽 레일
  "hub.rail.closet": "装扮",
  "hub.rail.title": "称号",
  "hub.rail.invite": "邀请奖励",

  // 오늘의 미션 칩
  "hub.mission.attendance": "签到",
  "hub.mission.daily_learn": "DAILY QUIZ",
  "hub.mission.minigame": "小游戏",

  // 도크(출석 보상)
  "hub.reward_head": "签到奖励",
  "hub.attend.title": "签到记录",
  "hub.attend.help": "只要打开网站，当天的签到就会自动记录。",
  "hub.daily.claim": "今日签到",
  "hub.daily.done": "今日已签到",
  "hub.day_n": "第 {n} 天",

  // 토스트
  "hub.toast.no_points_item": "金币不足：{name}（{price}金币）",

  // 구매/교환 완료 팝업
  "hub.buy.purchased": "购买成功！",


  // 상점 모달
  "hub.shop.balance": "持有的 CARI 币",
  "hub.shop.owned": "已拥有",
  "hub.shop.buy": "购买",
  "hub.shop.empty": "商店暂无商品。",
  "hub.shop.login": "登录后即可使用商店。",
  // ── 装扮（商店＋背包）· 角色选择 · 新手引导 (2026-08-20) ──
  "hub.shop.free": "免费",
  "hub.closet.title": "装扮",
  "hub.closet.tab_shop": "商店",
  "hub.closet.tryon_on": "预览中",
  "hub.closet.tryon_back": "还原",
  "hub.closet.tryon_buy": "用{n}金币购买",
  "hub.score_line": "赛季 {n} 分",
  "hub.score_top": "前{n}%",
  "hub.closet.preview": "预览",
  "hub.closet.tab_items": "背包",
  "hub.closet.g_character": "角色",
  "hub.closet.g_skin": "背景 · UI 皮肤",
  "hub.closet.g_part": "道具",
  "hub.closet.worn": "使用中",
  "hub.closet.wear": "使用",
  "hub.closet.empty_character": "你还没有角色。可以到商店页看看。",
  "hub.charpick.title": "请选择你的角色",
  "hub.charpick.sub": "只能选一个。选好的角色会从 Lv.1 开始和你一起成长。",
  "hub.charpick.g_m": "男性",
  "hub.charpick.g_f": "女性",
  "hub.charpick.go": "用{name}开始",
  "hub.charpick.pick_first": "请先选择角色",
  "hub.charpick.note": "以后在商店获得其他角色后，随时可以在背包里更换。",
  "hub.tut.welcome_t": "欢迎来到 CARI 中心",
  "hub.tut.welcome_b": "这里是和你的角色一起生活的地方。我们先看看都有什么。",
  "hub.tut.mission_t": "今日任务",
  "hub.tut.mission_b": "每天完成三项就能累积赛季积分，排行榜就是按它来排的。",
  "hub.tut.closet_t": "装扮",
  "hub.tut.closet_b": "用攒下的金币购买角色和背景皮肤，然后在背包里更换。",
  "hub.tut.stamp_t": "签到印章",
  "hub.tut.stamp_b": "只要进入网站就会自动签到。在这里看连续签到了几天，集满七天可以获得奖励 CARI 金币。",
  "hub.tut.prev": "上一步",
  "hub.tut.next": "下一步",
  "hub.tut.done": "开始",
  "hub.tut.skip": "跳过",
  "hub.lvup.title": "LEVEL UP",
  "hub.lvup.before": "之前",
  "hub.lvup.now": "现在",
  "hub.lvup.ok": "确认",
  "hub.lvup.next": "下一个",
  "hub.err.invalid_character": "无法选择的角色",
  "hub.err.invalid_kind": "无法使用的类型",
  "hub.err.invalid_part": "无法使用的道具",
  "hub.part.char_a_m": "韩风角色（男）",
  "hub.part.char_a_f": "韩风角色（女）",
  "hub.part.char_b_m": "角色 B · 男",
  "hub.part.char_b_f": "角色 B · 女",
  "hub.part.char_c_m": "角色 C · 男",
  "hub.part.char_c_f": "角色 C · 女",
  "hub.part.skin_meadow": "草原",
  "hub.part.skin_palace_day": "古宫 · 白天",
  "hub.part.skin_palace_night": "古宫 · 夜晚",

  // 쿠폰함
  "hub.coupon.title": "优惠券",
  "hub.coupon.discount": "{n}% 折扣",
  "hub.coupon.sub": "达成 Lv.{n} 奖励",
  "hub.coupon.used": "已使用",
  "hub.coupon.have": "持有",
  "hub.coupon.empty": "还没有优惠券，升级即可获得折扣券！",
  "hub.coupon.login": "登录后即可查看优惠券。",

  // 칭호
  "hub.title.title": "称号",
  "hub.title.login": "登录后即可查看称号收藏。",

  // 점수 획득 방법
  "hub.earn.title": "积分与金币获取方式",
  "hub.earn.lead": "参与各种活动累积积分，冲击排行榜！",
  "hub.earn.col_act": "活动项目",
  "hub.earn.col_pt": "获得积分",
  "hub.earn.pt": "+{n} 分",
  "hub.earn.limit": "每日 {n} 次 · 赛季最多 {max} 分",
  "hub.earn.lv_head": "等级测试",
  "hub.earn.lv_sub": "通关每个等级",
  "hub.earn.foot": "通过全部 7 个等级可得 {a} 分 · 加上活动的赛季满分为 {b} 分。",
  "hub.earn.row.attendance": "签到",
  "hub.earn.row.daily_learn": "完成 DAILY QUIZ",
  "hub.earn.row.minigame": "玩小游戏",
  "hub.earn.sec_score": "赛季积分",
  "hub.earn.sec_coin": "CARI 金币",
  "hub.earn.coin_lead": "金币用于在商店装扮角色和房间，与排行榜积分是不同的钱包。",
  "hub.earn.col_coin": "获得金币",
  "hub.earn.coin_pt": "+{n}金币",
  "hub.earn.coin_any": "对方赠送的数额",
  "hub.earn.coin.daily": "签到或 DAILY QUIZ",
  "hub.earn.coin.stamp": "集满 7 天印章",
  "hub.earn.coin.referral": "邀请好友 · 填写邀请码",
  "hub.earn.coin.gift": "收到好友赠送",
  "hub.earn.coin_note.daily": "每天 1 次 · 以先完成的为准",
  "hub.earn.coin_note.stamp": "集满 7 格的当天",
  "hub.earn.coin_note.referral": "邀请人和使用者双方都有",
  "hub.earn.coin_note.gift": "由赠送者决定",

  // 친구 초대 모달
  "hub.invite.title": "邀请好友",
  "hub.invite.lead": "和朋友一起玩 CARIS！",
  "hub.invite.help": "好友输入我的邀请码，双方各得 {n} CARI 币。",
  "hub.invite.my_code": "我的邀请码",
  "hub.invite.copied": "已复制",
  "hub.invite.copy": "复制",
  "hub.invite.issuing": "正在生成邀请码。",
  "hub.invite.login": "登录后即可生成邀请码。",
  "hub.invite.redeem_head": "输入好友邀请码",
  "hub.invite.redeem_done": "✓ 邀请码已登记（仅限一次）",
  "hub.invite.checking": "确认中",
  "hub.invite.register": "登记",
  "hub.invite.hint": "输入好友给的邀请码，双方各得 {n} CARI 币。",
  "hub.invite.err_not_found": "邀请码不存在，请重新确认",
  "hub.invite.err_self": "不能使用自己的邀请码",
  "hub.invite.err_already": "您已登记过邀请码",
  "hub.invite.ok": "登记完成！你和邀请你的好友各获得 {n} 金币",
  "hub.invite.fail": "登记失败",

  // 코인 선물 모달
  "hub.gift.title": "赠送硬币",
  "hub.gift.balance": "持有硬币",
  "hub.gift.received": "收到的赠礼",
  "hub.gift.count_n": "{n} 笔",
  "hub.gift.older": "此前收到的 {n} 笔赠礼",
  "hub.gift.send_head": "赠送硬币",
  "hub.gift.nick_label": "接收者昵称",
  "hub.gift.nick_ph": "昵称",
  "hub.gift.amount_label": "赠送数量",
  "hub.gift.send": "赠送",
  "hub.gift.sending": "赠送中",
  "hub.gift.confirm_q": "要赠送 {n} 枚硬币给 {name} 吗？",
  "hub.gift.confirm_warn": "赠送后无法撤回。",
  "hub.gift.history": "赠礼记录",
  "hub.gift.empty": "还没有赠送或收到过赠礼。",
  "hub.gift.dir_in": "收到",
  "hub.gift.dir_out": "赠出",
  "hub.gift.sent_ok": "已赠送 {n} 枚硬币给 {name}",
  "hub.gift.err_not_found": "没有这个昵称的用户",
  "hub.gift.err_self_code": "这是你自己的昵称",
  "hub.gift.err_too_many": "查询次数过多，请稍后再试",
  "hub.gift.err_lookup": "无法确认",
  "hub.gift.err_amount_required": "请输入赠送数量",
  "hub.gift.err_insufficient": "硬币不足",
  "hub.gift.err_self": "不能赠送给自己",
  "hub.gift.err_invalid_amount": "赠送数量不正确",
  "hub.gift.err_too_fast": "向同一位好友赠送过于频繁，请稍后再试",
  "hub.gift.err_send_fail": "赠送失败",

  // 1:1 inquiry (My Page > Support). Category labels are keyed as `inq.cat.<code>`.
  "inq.intro": "提交咨询后，我们会确认并回复。",
  "inq.private": "仅本人与运营人员可见。",
  "inq.write": "提交咨询",
  "inq.cat.exam": "考试",
  "inq.cat.payment": "支付·退款",
  "inq.cat.account": "账号",
  "inq.cat.arena": "WORLD ARENA",
  "inq.cat.etc": "其他",
  "inq.ph_title": "标题",
  "inq.ph_body": "请填写咨询内容。考试或支付相关咨询请一并写明场次与等级，回复会更快。",
  "inq.submit": "提交",
  "inq.sending": "发送中…",
  "inq.err_fields": "请填写标题和内容。",
  "inq.err_login": "需要登录。",
  "inq.login_required": "登录后即可使用。",
  "inq.empty": "还没有咨询。",
  "inq.status_open": "等待回复",
  "inq.status_answered": "已回复",
  "inq.new_answer": "新回复",
  "inq.answer_at": "回复 · {d}",
  "inq.no_answer": "尚未登记回复。",
}

export default ZH
